pentaho/pentaho-platform

user-console/source/org/pentaho/mantle/client/commands/NewFolderCommand.java
unfortunately NewFolderCommand still works with "solutions". I've created custom NewFolder dialog and returned the original  NewFolderCommand to PUC
@mdamour1976  please review
=> [BACKLOG-1866] - REGRESSION: unable to create folder in PUC - return previous version of NewFolderCommand for PUC

repository/src/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObject.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelperTest.java
=> [BACKLOG-1493] - Fixed path for mondrian vfs data sources access check

repository/test-src/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObjectTest.java
=> [BACKLOG-1493] - Fixing unit test for SolutionRepositoryVfsFileObject

user-console/source/org/pentaho/mantle/client/solutionbrowser/tree/SolutionTree.java
More information is available here:
http://jira.pentaho.com/browse/BISERVER-12271
It's a simple nullness check, nevertheless :-).
=> [BISERVER-12271] Select button in Schedule... stops working if there is a file in the root solution folder

core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledDatasourceSystemListener.java, core/test-src/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledDatasourceSystemListenerTest.java
=> [BISERVER-12393] - Fixed Non-JNDI Datasource cache initial setup

user-console/source/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/source/org/pentaho/mantle/public/themes/onyx/mantleOnyx.css
=> [BACKLOG-1103] - Move styles to commons-gwt-widgets

assembly/package-res/biserver/pentaho-solutions/plugin-samples/exportManifest.xml
Changes for 5.3 branch:
https://github.com/pentaho/pentaho-platform/pull/2239
=> BISERVER-12353 - plugin-samples should be hidden by default

core/src/org/pentaho/platform/util/ColorHelper.java, core/test-src/org/pentaho/platform/util/ColorHelperTest.java, core/test-src/org/pentaho/platform/util/XmlHelperTest.java, extensions/src/org/pentaho/platform/plugin/services/importexport/Exporter.java, extensions/src/org/pentaho/platform/plugin/services/importexport/ImportSession.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java, extensions/test-src/org/pentaho/platform/web/http/filters/CheckRefererFilterTest.java, extensions/test-src/org/pentaho/platform/web/http/filters/PentahoAwareCharacterEncodingFilterTest.java, extensions/test-src/org/pentaho/platform/web/http/filters/ProxyTrustingFilterTest.java, extensions/test-src/org/pentaho/test/platform/plugin/services/webservices/WsdlPageTest.java
Cleaning up old tests due to http://jira.pentaho.com/browse/BACKLOG-774.
@rmansoor, please review this PR.  I have create it instead of closed https://github.com/pentaho/pentaho-platform/pull/2002.
The PR contains changings related both to test and production classes. This is because the original PR was sent far earlier @dkincade has mentioned not to affect production code winthin [test]-tasks. However, these changes are minor and safe and I'm sure they will not break anything.
=> [Test] - Cleaning up tests and refactoring

extensions/diserver-extensions-jmeter.jmx, scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
DI schedule tests was added
depends on https://github.com/pentaho/pentaho-platform-ee/pull/689
@dkincade please review.
=> BACKLOG-2108 Create REST implementation of DI scheduling service

extensions/src/org/pentaho/platform/plugin/services/security/userrole/SecuritySystemListener.java
The fix provided in (http://jira.pentaho.com/browse/ESR-4274?focusedCommentId=202084&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-202084)
=> [BACKLOG-2252]: Impossible to retrieve a valid non-active AuthenticationProvider

user-console/source/org/pentaho/mantle/public/home/js/home.js
Change the if statement to properly disable the recents widget
Original PR #2258
=> [BISERVER-12474] - Disable "Recents" widgets from PUC Home Screen

extensions/ivy.xml
PDI DataService driver has been moved from kettle core.
=> [BACKLOG-411]Add ThinDriver jar

repository/src/org/pentaho/platform/security/userroledao/DefaultTenantedPrincipleNameResolver.java, repository/test-src/org/pentaho/test/platform/security/userroledao/DefaultTenantedPrincipleNameResolverTest.java
cherry-pick https://github.com/pentaho/pentaho-platform/pull/2266
=> SP-1757 - Backport of BISERVER-12450 - Regression : pentaho_user causes issues when browsing repository (5.3 Suite)

assembly/assembly.properties, assembly/ivy.xml
=> [BACKLOG-3030] - Fixed dependency

assembly/ivy.xml
=> [BACKLOG-3030] - Fixed dependency name

extensions/build.xml
=> [BACKLOG-2452] - Tentative fix for wadl target generation

api/build-res/subfloor.xml, assembly/build-res/subfloor.xml, build-utils/build-res/subfloor.xml, core/build-res/subfloor.xml, extensions/build-res/subfloor.xml, repository/build-res/subfloor.xml, scheduler/build-res/subfloor.xml, user-console/build-res/subfloor.xml
Merge of master into future-develop
=> Auto-Merge refreshing development branch

extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, scheduler/src/org/pentaho/platform/api/scheduler2/JobParamsAdapter.java, scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> [BACKLOG-3032] - Enable editing of schedules created from either pdi-client or user console

extensions/src/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishServiceTest.java
Merged with this PR:
https://github.com/pentaho/pentaho-reporting/pull/612
=> BISERVER-12457 - REGRESSION: User with Administer Security permission can publish reports

assembly/assembly.properties, assembly/ivy.xml
Add spark plugin
https://github.com/pentaho/pentaho-kettle/pull/1230
https://github.com/pentaho/pentaho-platform-ee/pull/699
@mdamour1976 @rmansoor @mattyb149
=> [BAD-170] Support for Spark

extensions/src/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishServiceTest.java
Merged with this PR:
https://github.com/pentaho/pentaho-reporting/pull/611
=> SP-1747 - Regression of BISERVER-12457 - User with Administer Security permission can publish reports (5.3 Suite)

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml
=> [BACKLOG-3102] - Added config for session variables override blacklist

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoInst.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoInstTest.java
picked from https://github.com/pentaho/pentaho-platform/pull/2291
@mdamour1976 @rmansoor @pentaho-nbaker please someone merge
=> [PDI-13724] fixed defining of revision's creation date from update repository method

extensions/src/org/pentaho/platform/web/servlet/JAXRSPluginServlet.java
- previously we were only checking if endpoint ended in "application.wadl"
- now we check the endpoint using a regex that allows for either "application.wadl" and wall sub-resources ( ex: "application.wadl/xsd0.xsd" )
- cherry-picked from https://github.com/pentaho/pentaho-platform/pull/2290
=> [BISERVER-12558] Error accessing WADL sub-resources ( for plugins )

user-console/source/org/pentaho/mantle/public/browser/messages_supported_languages.properties, user-console/source/org/pentaho/mantle/public/home/properties/config_supported_languages.properties, user-console/source/org/pentaho/mantle/public/home/properties/messages_supported_languages.properties
What was done:
1) added languages to supported locale files
=> BACKLOG-3289 -- Home & Browse Perspective are not showing locales.

assembly/package-res/biserver/tomcat/webapps/pentaho/jsp/PUCLogin.jsp
What was done:
1) added class describing current locale to allow locale specific UI
changes
=> BACKLOG-3361 -- French - Login Page, login button text gets cut off.

repository/src/org/pentaho/platform/repository2/messages/messages_fr.properties
What was done:
1) added updated files
=> BACKLOG-3306 - Checkin 5.4 Localization files from Acclaro (2nd drop)

repository/src/org/pentaho/platform/repository2/messages/messages_fr.properties
What was done:
1) updated file
=> BACKLOG-3306 -- Checkin 5.4 Localization files from Acclaro (2nd drop)

user-console/source/org/pentaho/mantle/public/home/js/launch.js, user-console/source/org/pentaho/mantle/public/home/properties/config.properties, user-console/source/org/pentaho/mantle/public/home/properties/config_de.properties, user-console/source/org/pentaho/mantle/public/home/properties/config_en.properties, user-console/source/org/pentaho/mantle/public/home/properties/config_fr.properties, user-console/source/org/pentaho/mantle/public/home/properties/config_ja.properties
different parameter to retrieve the base url
=> [BISERVER-11812] - Remove hard coded pentaho context and used a

extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
utility does not work
What was done:
1) added usage of KettleEncoder
=> BISERVER-12584 -- Encrypted repository passwords with Import-Export

user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTab.java
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker Could you merge it?
=> [BISERVER-12524] Regression: Getting create deep link dialog does not work with proxy or when running in port 80

assembly/package-res/biserver/pentaho-solutions/system/jackrabbit/repository.xml
Goes with https://github.com/pentaho/data-access/pull/637
=> BISERVER-12579 - Non-admin User Unable to add Data Source Connection

assembly/assembly.xml, assembly/package-res/appserver/tomcat/res/datasources/h2/context.xml, assembly/package-res/appserver/tomcat/res/datasources/hsqldb/context.xml, assembly/package-res/appserver/tomcat/res/datasources/mysql5/context.xml, assembly/package-res/appserver/tomcat/res/datasources/oracle10g/context.xml, assembly/package-res/appserver/tomcat/res/datasources/postgresql/context.xml
Update the jndi configuration to tomat 8
=> [BACKLOG-3902] - Update the assembly to use tomcat 8.0.23

core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
@lucboudreau 
Please review. Backport of https://github.com/pentaho/pentaho-platform/pull/2341
=> SP-1913 - Backport of PDI-13736 - Regression: PDI Server Startup Time with invalid database connections (5.4 Suite)

extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
"@rmansoor" , review it please. This is backport of merged PR.
=> SP-1911 - Backport of BISERVER-12584 - Encrypted repository passwords with Import-Export utility does not work (5.4 Suite)

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java, user-console/source/org/pentaho/mantle/public/browser/index.jsp, user-console/source/org/pentaho/mantle/public/browser/js/browser.js
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker Could you review it? please?
=> [BISERVER-12570] - Regression: Impossible to see folder properties after selection one of the file file from this folder

assembly/package-res/biserver/pentaho-solutions/system/jackrabbit/repository.xml
@rmansoor 
Please review. Backport of https://github.com/pentaho/pentaho-platform/pull/2346
Goes with https://github.com/pentaho/data-access/pull/641
=> SP-1948 - Backport of BISERVER-12579 - Non-admin User Unable to add Data Source Connection (5.4 Suite)

user-console/source/org/pentaho/mantle/public/angular-animations.css
Please review @pminutillo @kurtwalker @bytekast @krivera-pentaho and merge thx!
=> [BACKLOG-4270] added slide down from top annimation

assembly/package-res/biserver/start-pentaho-debug.bat, assembly/package-res/biserver/start-pentaho-debug.sh, assembly/package-res/biserver/start-pentaho.bat, assembly/package-res/biserver/start-pentaho.sh
Reverts pentaho/pentaho-platform#2391
=> Revert "[BACKLOG-4343] - Pentaho Fails to start with a space

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/org/pentaho/platform/osgi/SystemPackageExtrapolator.java
=> [BACKLOG-4081] - Fixed file uri for retrieving artifact from karaf system folder

extensions/test-src/org/pentaho/test/platform/plugin/JFreeReportTest.java, extensions/test-src/org/pentaho/test/platform/plugin/services/metadata/SolutionFolderTest.java, extensions/test-src/org/pentaho/test/platform/plugin/services/metadata/steel-wheels.xmi
This functional was relocation on pentaho-platform-extension project. Some methods, which uses on the past, no actually: 
class MetadataDomainRepository is not exist. This functional was include on PentahoMetadataDomainRepository class getLocaleFromPropertyfilename() & getLocalePropertyFilenames() are not exists. This functionality was included on methods Domain.getLocaleCodes() & Domain.getLocales() & Domain.addLocale( LocaleType locale ).
Test Methods testImportPropertyFile() & testImportLocalizationEmptyPropertyFile() was deleted, because this cases was verify on PentahoMetadataDomainRepositoryTest.testLoadLocaleStrings().
=> BACKLOG-774 Uncommited old \ ignored unit tests

extensions/src/org/pentaho/platform/web/http/api/resources/JerseyUtil.java
handling of parameters was fixed
=> BACKLOG-4174 BA Server in 6.0 build: User can't save dashboard.

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java
Created REST endpoint for retrieving the list of users and corresponding unit tests.
=> [BACKLOG-4548] - Create public REST interfaces for Retrieve User List

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java
Created public REST endpoint for deleting a list of users.
=> [BACKLOG-4550] - Create public REST interfaces for Delete User

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java
REST endpoint and unit tests to expose adding runtime roles as a public API.
=> [BACKLOG-4672] - Add runtime role(s) to a specific user

extensions/src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepository.java, extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryConcurrencyTest.java
@pentaho-nbaker, @rmansoor, @mdamour1976, @mbatchelor, review it please.
These changes were sucessfully adopted by the customer (see http://jira.pentaho.com/browse/BISERVER-12642)
=> [BISERVER-12642] - Inconsistent synchronization leading to deadlock between JCR and PentahoMetadataDomainRepository

extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
Adding service layer unit tests for deleting users and adding roles to a user.
=> [TEST] - Increasing unit test coverage.

extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
Adding test coverage to UserRoleListService for adding roles to users.
=> [TEST] - Adding test coverage

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
Created rest endpoint and unit tests to delete a tab seperated list of roles from a specific user.
=> [BACKLOG-4673] - Delete runtime role(s) from a specific user

extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java
Intelij refactor does not like to refactor references from static objects
=> [TEST] - Test cleanup

scheduler/test-src/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/test/QuartzSchedulerTest.java
decreased timings, fixed tests, added unit test
@rmansoor please review
=> [BISERVER-12699] - QuartzSchedulerTest takes too long and fails often

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
Refactor the work done to expose user and role REST endpoints out of the list service. The work should be productizing the DAO object and not mutating the list service.
=> [BACKLOG-4381] - REVERT the work done in the UserRoleListService

assembly/package-res/biserver/pentaho-solutions/system/osgi/log4j.xml, assembly/package-res/biserver/tomcat/webapps/pentaho/WEB-INF/classes/log4j.xml
org.pentaho.di and org.pentaho.di.monitor packages
=> [BACKLOG-4894] - Updating log4j.xml to see the logging threshold for

user-console/source/org/pentaho/mantle/client/ui/column/HtmlColumn.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
=> BACKLOG-4399 file path not wrapping on scheduling perspective line breaks was added

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
QA found some documentation errors while running through the case.
=> [CLEANUP] - Documentation corrections found during the QA process.

assembly/ivy.xml, assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml, assembly/package-res/biserver/pentaho-solutions/system/importExport.xml
=> [BACKLOG-3825] include pdi pur repository in ce assembly; use in import

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
The documentation team review and revision of the REST endpoints.
=> [CLEANUP] - Documentation review / revision of REST comments.

api/src/org/pentaho/platform/api/data/IJndiDatasourceService.java, api/src/org/pentaho/platform/api/data/IPooledDatasourceService.java, core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/JndiDatasourceService.java, core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceService.java, extensions/src/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProvider.java, extensions/src/org/pentaho/platform/plugin/boot/PentahoBoot.java
- introduce two interfaces for sharing different data source providers
- update PlatformKettleDataSourceProvider to implement new method in DataSourceProviderInterface
@pentaho-nbaker, @rmansoor, please review it.
This PR comes together with https://github.com/pentaho/pentaho-kettle/pull/1655 and **should not be merged before it**
/cc @pamval
=> [PDI-13961] Spoon firstly tries to conect via JNDI although connection type is JDBC

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java
Send request as admin
1.	Valid username, valid password, valid new password – 200 changed successfully
2.	Wrong username, valid new password – 403 
3.	Invalid username(empty), valid new password – 400
4.	Invalid username(null), valid new password – 400
5.	Valid username, wrong password - 403
6.	Valid username, valid password, invalid new password (empty) –400
7.	Valid username, valid password, invalid new password (null) – 400
8.	Valid username, invalid password (empty), valid new password – 400
9.	Valid username, invalid password (null), valid new password – 400
Send request as simple user
1.	Valid username, valid password, valid new password –200
Send request as not existing user
1.	Valid username, valid password, valid new password –401
I put TODO comment with following message: …
=> [BACKLOG-4674] - Dev subtask for Change user password

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java
=> [BACKLOG-4446] - code for exporting metadata models.

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java
Endpoint calls the new full repository export work
=> [BACKLOG-5023] - Create REST endpoint for full repository export

assembly/package-res/biserver/pentaho-solutions/system/axis/axis2_config.xml, extensions/ivy.xml, extensions/test-src/webservices-solution/system/axis2_config.xml, repository/ivy.xml
This pull request is one of pull-requests related to PDI-13231.
If you apply this request  you have to apply other pull-requests from this set:
pentaho/pentaho-metadata#64
https://github.com/pentaho/data-access/pull/657
pentaho/pdi-agile-bi-plugin#38
@mbatchelor , @mdamour1976  please review.
=> [PDI-13231] - upgrade axis2 to 1.5 + add pentaho-concurrent dependency

extensions/test-res/AxisWebServiceManagerTest/system/axis/axis2_config.xml
@mdamour1976 this should fix AxisWebServiceManagerTest
=> [PDI-13231] - upgrade axis2 to 1.5 + add pentaho-concurrent dependency - a test config was missed

user-console/source/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js
Added trimming for new name value.
@pentaho-nbaker @rmansoor could you please review.
=> [SP-2082] Backport of BISERVER-12476 - PUC accepts invalid characters when renaming a file (5.4 Suite)

assembly/ivy.xml
=> [PDI-13231] - upgrade axis2 to 1.5 + add pentaho-concurrent dependency - remove concurrent-1.3.4 from assembly

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Added the second round documentation edits to the userroledao REST api.
=> [CLEANUP] - Documentation edits for the REST api

extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/org/pentaho/platform/plugin/services/messages/messages.properties
Create command line script option for running the system backup
=> [BACKLOG-5073] - Create Command Line interface for full backup

extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
Add support to the import / export command line script for performing a full system restore from the command line.
=> [BACKLOG-5074] - Create Command Line interface for full system restore

repository/src/org/pentaho/platform/repository2/unified/ExceptionLoggingDecorator.java
=> BACKLOG-4873 Importing error for Operation Datamart - "exception while creating file with name "ETL_Operations_Datamart_-_Job_Entry.ktr""

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/org/pentaho/platform/plugin/services/messages/messages.properties, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java
Adding the option for users to choose not to overwrite existing files during the import process.
=> [BACKLOG-5074] - Adding overwrite option to the import.

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
Fixed an issue causing new roles to not have permissions assigned to them during the import process.
=> [BACKLOG-5194] - Importing a new role does not retain permissions

extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java
Refactored the getAllRoles to use a set instead of a list for merging two collections together into one.
=> [BACKLOG-4822] - Refactored a list to a set.

extensions/src/org/pentaho/platform/web/http/api/resources/ChangePasswordUser.java, extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Updated the documentation and examples for create user, create role, administrator update password, and user update password.
=> [BACKLOG-4381] - Updated documentation

repository/src/org/pentaho/platform/repository/usersettings/UserSettingService.java, repository/test-src/org/pentaho/platform/repository/usersettings/UserSettingServiceTest.java
Implementing new UserSetting methods to support the Backup / Restore work with per user operations that can only be executed by an administrative user.
=> [BACKLOG-4444] - Implementing new UserSettings methods.

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
The documentation has been cleaned up around the errors found by QA. Since a mapping of return code to exception has been changed to match the documentation the unit test had to be updated as well.
=> [BACKLOG-4813] - Documentation edits and test case update.

extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
=> [BISERVER-12264] fix test

extensions/src/org/pentaho/platform/web/servlet/PentahoDataSourceResolver.java, extensions/src/org/pentaho/platform/web/servlet/messages/messages.properties
Master pull request https://github.com/pentaho/pentaho-platform/pull/2580
=> [BACKLOG-5217] - Adding a fallback to the datasource lookup logic to using the datsource as it is

user-console/source/org/pentaho/mantle/client/commands/SaveCommand.java
What was done:
1) added the logic for cutting extensions
=> BACKLOG-5182 -- Report tab showing Report name+.xanalyzer

extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolverTest.java
[TEST] - fixing a couple of unit tests.
=> [TEST] - fixing a couple of unit tests.

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileUtils.java
Reverts pentaho/pentaho-platform#2600
=> Revert "[BISERVER-12676] Fixing regression. Sorting children."

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Documentation drafts are generated from enunciate. Enunciate generates the index for documentation by the order the methods are found in. During the last pass at the documentation the index was reordered so that similar operations were grouped together logically. The code is being updated to reflect this ordering.
=> [CLEANUP] - Reordered method calls for documentation index

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Updating the documentation for users changing their own password.
=> [CLEANUP] - Updating documentation for change user password.

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Worked with the documentation team to make a final pass on the documentation.
=> [CLEANUP] - Updated documentation based on final draft.

extensions/src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtil.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtilTest.java
[BACKLOG-5417] - Restore (import/export) - Schedules are not being restored
=> [BACKLOG-5417] - Restore (import/export) - Schedules are not being restored

repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProviderTest.java
- move internal maps to a global cache
- add tests
@pentaho-nbaker, @rmansoor, review it please.
Please do not ignore it to let it be proceeded within October SP.
/cc @pamval
=> [BISERVER-12657] - SpringSecurityPrincipalProvider uses static maps instead of CacheManager

scheduler/test-src/org/pentaho/platform/scheduler2/blockout/PentahoBlockoutManagerIT.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerIT.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/test/QuartzSchedulerIT.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/test/QuartzThreadsIT.java, scheduler/test-src/org/pentaho/platform/scheduler2/versionchecker/EmbeddedVersionCheckSystemListenerIT.java, scheduler/test-src/org/pentaho/platform/scheduler2/ws/test/JaxWsSchedulerServiceIT.java
- JaxWsSchedulerServiceTest (1:14 min)
- test/QuartzSchedulerTest (1:03 min)
- PentahoBlockoutManagerTest (1.5 sec)
- QuartzThreadsTest (1.3 sec)
- EmbeddedVersionCheckSystemListenerTest (uses MicroPlatform)
- QuartzSchedulerTest (import change)
=> [BACKLOG-5397] - Classify Unit Test as Integration Tests

extensions/src/org/pentaho/platform/web/http/api/resources/XactionUtil.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/XActionUtilTest.java
XActionUtil  delete file which generated during executing
=> Biserver 12639

extensions/test-src/org/pentaho/platform/plugin/services/pluginmgr/PentahoSystemPluginManagerIT.java, extensions/test-src/org/pentaho/test/platform/plugin/pluginmgr/DefaultPluginManagerIT.java
[BACKLOG-5394] - Found another unit test that should be an integration test, moved it
=> [BACKLOG-5394] - Found another unit test that should be an integration test, moved it

scheduler/test-src/org/pentaho/platform/scheduler2/quartz/test/QuartzSchedulerTest.java
=> SP-2187 - ignore failing test

api/src/org/pentaho/platform/api/repository2/unified/IUnifiedRepository.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDao.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoIT.java
- catch JCR's exception and return null instead
- add test
- update java docs
- fix checkstyle violations for affected classes
@pentaho-nbaker, @rmansoor, review it please.
=> [BISERVER-12758] - DefaultUnifiedRepository.getFileById() throws exception if none was found

user-console/source/org/pentaho/mantle/client/commands/SaveCommand.java
What was done:
1) added the logic for cutting extensions
=> [SP-2174] BACKLOG-5182 -- Report tab showing Report name+.xanalyzer

repository/test-src/org/pentaho/platform/repository/RepositoryDownloadWhitelistTest.java
What was done:
1) added unit tests for download whitelist
=> TEST -- improving test coverage

extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
@pamval @pentaho-nbaker please review and merge
=> [BISERVER-12297] created new endpoint for updating a schedule saving the original owner

extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java, scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
Backport of https://github.com/pentaho/pentaho-platform/pull/2651
and backport of BACKLOG-5291, it contains implementation of using RESERVEDMAPKEY_ACTIONUSER value for owner changing
@pamval @rmansoor please merge
=> [SP-2083] created new endpoint for updating a schedule saving the original user

extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerOutputPathResolver.java
@pamval @rfellows please merge
=> [SP-2083] add check for null

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ComplexJobTriggerProxyTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ComplexJobTriggerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/CronJobTriggerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/CustomPropertyTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseAccessTypeTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseConnectionTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseTypeTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DayOfWeekQualifierTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DayOfWeekTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityAclTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityMetaDataTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestDatasourceTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestMetaStoreTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestPropertyTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/IncrementalRecurrenceTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleParamTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleRequestTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ObjectFactoryTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/PartitionDatabaseMetaTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/QualifiedDayOfWeekTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/RecurrenceListTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/SequentialRecurrenceTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/SimpleJobTriggerTest.java
focusing on packages:
* org.pentaho.platform.osgi
* org.pentaho.platform.plugin.services.importexport.exportManifest.bindings
=> [BACKLOG-5384] [TEST] - Increasing code coverage for pentaho-platform-extensions

api/test-src/org/pentaho/platform/api/ui/ModuleThemeInfoTest.java, api/test-src/org/pentaho/platform/api/ui/ThemeResourceTest.java, api/test-src/org/pentaho/platform/api/ui/ThemeTest.java
please review @bytekast @kurtwalker
=> [TEST] increase test coverage

user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
@pamval @rmansoor please review and merge
and then this related PR: https://github.com/pentaho/pentaho-analyzer/pull/852
=> [PPP-3365] fixed bug of plugin loading interaction with PUC

api/src/org/pentaho/platform/api/engine/IPentahoRegistrableObjectFactory.java, api/src/org/pentaho/platform/api/monitoring/snmp/IVariableSerializer.java, api/src/org/pentaho/platform/api/monitoring/snmp/SnmpVariable.java, api/src/org/pentaho/platform/api/repository2/unified/data/node/DataNode.java
@pminutillo @kurtwalker @bytekast please review and merge.
=> [CLEANUP] fix sonar issues

core/ivy.xml, core/src/org/pentaho/platform/engine/core/messages/Messages.java, core/src/org/pentaho/platform/engine/core/messages/messages.properties, core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java, core/src/org/pentaho/platform/util/messages/MessagesBase.java, core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java, core/test-src/org/pentaho/platform/util/JSONComparitorTest.java
=> BISERVER-12899 Deprecate the use of ChartHelper in platform

assembly/ivy.xml
@dkincade This for BA Server CE as you guys requested.
=> [PPP-3446] Add Weka to BA Server EE

assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml
Added prptstyle extension to ImportHandlerMimeTypeDefinitions.xml config file.
@pentaho-nbaker, @dkincade, @rmansoor could you please review?
=> [BISERVER-10705] PUC gives you an error if you try to upload prptstyle file

user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
This backport picked from https://github.com/pentaho/pentaho-platform/pull/2676/
@rmansoor @pamval please merge
=> [SP-2236] fixed bug of plugin loading interaction with PUC

user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
This backport picked from https://github.com/pentaho/pentaho-platform/pull/2676/
@rmansoor @pamval please merge
=> [SP-2237] fixed bug of plugin loading interaction with PUC

core/src/org/pentaho/platform/engine/core/system/status/ServerStatusProvider.java
CopyOnWriteArrayList for savely remove
=> BISERVER-12959 ConcurrentModificationException at start

assembly/package-res/biserver/tomcat/webapps/pentaho/html/InitState.html, extensions/src/org/pentaho/platform/web/http/filters/ForwardFilter.java, extensions/src/org/pentaho/platform/web/http/filters/PentahoAwareCharacterEncodingFilter.java, extensions/src/org/pentaho/platform/web/http/filters/PentahoAwareCharacterEncodingFilterImpl.java, extensions/src/org/pentaho/platform/web/http/filters/SystemInitStatusFilter.java, extensions/test-src/org/pentaho/platform/web/http/filters/PentahoAwareCharacterEncodingFilterTest.java
SystemInitStatusFilter implemented
PentahoAwareCharacterEncodingFilter renamed to PentahoAwareCharacterEncodingFilterImpl
current PentahoAwareCharacterEncodingFilter work as wrap for PentahoAwareCharacterEncodingFilterImpl and SystemInitStatusFilter
ServerStatusChangeListenerList synchronized
=> BACKLOG-5664 Repurpose PentahoAwareCharacterEncodingFilter to presenе static html page

extensions/src/org/pentaho/platform/plugin/services/connections/metadata/sql/SqlMetadataQueryExec.java, extensions/test-src/org/pentaho/test/platform/plugin/MetadataQueryComponentIT.java
@rmansoor @pamval 
Please review.
Goes with https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/271
=> PDB-1886 - PDB : Content linking broken in Pentaho 6.0 release.

repository/src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java, repository/test-src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDaoTest.java
@pentaho-nbaker, @pamval, could you please take a look?
=> BISERVER-12614 - Changing password not active on BA cluster environment

extensions/src/org/pentaho/platform/plugin/services/connections/metadata/sql/SqlMetadataQueryExec.java, extensions/test-src/org/pentaho/test/platform/plugin/MetadataQueryComponentIT.java
Cherry-pick of https://github.com/pentaho/pentaho-platform/pull/2720
Goes with https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/272
@pamval 
Please review.
=> SP-2300 - Backport of PDB-1886 - PDB : Content linking broken in Pentaho 6.0 release. (6.0 Suite)

extensions/src/org/pentaho/platform/web/http/api/resources/DirectoryResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/RepositoryPublishResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/org/pentaho/platform/web/http/api/resources/utils/FileUtils.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileService_CreateDir_IT.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/utils/FileUtilsTest.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryBase.java
- introduce new method in FileService with validation of input path
- change FileResource and DirectoryResource to use it
- extract common procedure for validation
- add tests
- fix Checkstyle violations for all affected classes and make some cleanup
@pentaho-nbaker, @rmansoor, review it please
=> [BISERVER-12506] - Folder creation: reserved character validation is only being done client-side

extensions/src/org/pentaho/platform/osgi/KarafBoot.java
=> PDI-14540 java.io.FileNotFoundException - OSGI Log4j.xml not found when start Spoon

assembly/assembly.xml
@pedrofvteixeira please review.
=> [BISERVER-12992] - Plugin-samples visible in CE by default

extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/org/pentaho/platform/web/http/api/resources/utils/FileUtils.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/FileResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/utils/FileUtilsTest.java, user-console/source/org/pentaho/mantle/client/commands/RestoreFileCommand.java
- Expanded doRestore functionality (added ability to restore files in home folder, choosing one of overwrite modes)
- Created new user dialog, suggesting user to restore files in his home folder when he has no write permissions to original file folder.
- Test written
- Checkstyle applied
@pentaho-nbaker, @mdamour1976, @rmansoor, review it please
=> [BISERVER-12794] Permissions can delete but not restore file

api/ivy.xml, assembly/package-res/biserver/pentaho-solutions/system/barrierBeans.properties, assembly/package-res/biserver/pentaho-solutions/system/server.properties, core/src/org/pentaho/platform/engine/core/system/objfac/spring/ApplicationContextPentahoSystemRegisterer.java, core/src/org/pentaho/platform/engine/core/system/objfac/spring/BarrierBean.java, core/src/org/pentaho/platform/engine/core/system/objfac/spring/BarrierBeanPostProcessor.java, core/src/org/pentaho/platform/engine/core/system/objfac/spring/BarrierBeanProcessor.java, core/test-res/solution/system/barrierBean.properties, core/test-src/org/pentaho/platform/engine/core/system/objfac/spring/BarrierBeanPostProcessorTest.java, core/test-src/org/pentaho/platform/engine/core/system/objfac/spring/BarrierBeanProcessorTest.java
Waits for the jcrRepository Bean to be created before starting the the Karaf 2 minute timeout in KarafFeatureWatcherImpl
=> [BACKLOG-5858] Introduce ServiceBarrier backed BarrierBeans

extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/FileResourceTest.java, user-console/source/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js
fixed:
- submit by another event
- dialog render only after the name init
- 'rename' servlet without the extension check
=> BACKLOG-5863 Cannot rename files in folders

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
show error message for removing role exceptions
@rmansoor please review
=> [BISERVER-12857] - manage user role issues tomcat vs jboss

assembly/ivy.xml
@tgf Please review, this is part 3 of 4.  
See also:
https://github.com/pentaho/pentaho-kettle/pull/2026
https://github.com/pentaho/pdi-ee-plugin/pull/308
https://github.com/pentaho/pentaho-platform-ee/pull/869
=> [BACKLOG-5798] Allow PDI CE to connect to the Pentaho Repository

extensions/src/org/pentaho/platform/web/http/api/resources/UserSettingsResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserSettingsResourceTest.java, user-console/source/org/pentaho/mantle/public/home/js/FavoritesController.js, user-console/source/org/pentaho/mantle/public/home/js/favorites.js
Cherry-pick of https://github.com/pentaho/pentaho-platform/pull/2757
@rfellows 
Please review.
=> SP-2361 - Backport of PPP-3464 - Security Vulnerability- Stored Cross-Site (XSS) Scripting (6.0 Suite)

extensions/src/org/pentaho/platform/web/http/api/resources/UserSettingsResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserSettingsResourceTest.java, user-console/source/org/pentaho/mantle/public/home/js/FavoritesController.js, user-console/source/org/pentaho/mantle/public/home/js/favorites.js
Cherry-pick of https://github.com/pentaho/pentaho-platform/pull/2757
@rfellows 
Please review.
=> SP-2362 - Backport of PPP-3464 - Security Vulnerability- Stored Cross-Site (XSS) Scripting (5.4 Suite)

repository/src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java, repository/test-src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDaoTest.java
@pentaho-nbaker, @pamval, here is backport of https://github.com/pentaho/pentaho-platform/pull/2718. Thanks.
=> [SP-1940] - Backport of BISERVER-12614 - Changing password not active on BA cluster environment (5.4 Suite)

extensions/src/org/pentaho/platform/web/http/context/PentahoSolutionSpringApplicationContext.java
PentahoSolutionSpringApplicationContext.java import "importExport.xml" resource into pentaho-spring-beans.xml
=> BACKLOG-6086 Implement the solution for repository usage error in the DI server after upgrade

core/src/org/pentaho/platform/engine/core/system/objfac/spring/BeanBuilder.java, core/test-src/org/pentaho/platform/engine/core/system/objfac/spring/BeanBuilderTest.java
- set default value of dampeningTimeout to *0* if undefined in system properties.
- Unit test
- checkstyle
@rmansoor @CodeOnCoffee please review
=> [BACKLOG-6391] - Administration page does not show any content

extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
@rfellows, merge it please. This is an addendum to https://github.com/pentaho/pentaho-platform/pull/2647 to let the test pass on Windows
/cc
@rmansoor
=> [TEST] - make SolutionImportHandlerTest OS-independent

user-console/source/org/pentaho/mantle/rebind/EventBusUtilGenerator.java
- replace `eval()` with `JSON.parse()` in EventBusUtilGenerator
@mdamour1976, since you are the author of this class, could you please review this PR?
/cc @rmansoor
=> [PPP-3455] - Dynamic code injection vulnerabilities found

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
- revert 4355625f369b243de81bf9a7ad000e3a28cc4880 for now
@rfellows, @pamval, merge it please. This is a revert of https://github.com/pentaho/pentaho-platform/pull/2775
=> [SP-2412] - Backport of BISERVER-12851 - Restore (import/export) - Schedules are not being restored. (6.0 Suite)

user-console/source/org/pentaho/mantle/client/admin/UserRolesAdminPanel.java, user-console/source/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/source/org/pentaho/mantle/public/themes/onyx/mantleOnyx.css
- fixed other CSS styling issues present on the Adminstration Panel
=> [BISERVER-12865] - 5.0 to 6.0 Regressions in Admin > User/Roles screen

repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryAuthorizationIT.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryBase.java
.testOwnership(), now using tiffany to remove suzy rights to a suzy
owned folder. Fixed DefaultUnifiedRepositoryBase to remove the right tmp
folder on startup
=> [BACKLOG-5879] Fixed DefaultUnifiedRepositoryAuthorizationIT

assembly/assembly.xml
- added missing file: new "Pentaho (merged) server CE" ant targets in assembly.xml
=> [BACKLOG-6636] Make the necessary code changes from EE to CE

extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
original user. This was merged into 5.4.1, but not the 6.0 branches.
=> [BISERVER-12297] created new endpoint for updating a schedule saving the

assembly/assembly.xml
- (cherry-pick from master to 6.1.0.0) https://github.com/pentaho/pentaho-platform/pull/280
=> [CHERRY-PICK][BACKLOG-6636] Make the necessary code changes from EE to CE

user-console/source/org/pentaho/mantle/client/admin/UserRolesAdminPanel.java, user-console/source/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/source/org/pentaho/mantle/public/themes/onyx/mantleOnyx.css
=> [BISERVER-13062] - Cherry pick to branch 6.1.0.0

extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
@pamval could you process my PR related to https://github.com/pentaho/pentaho-platform/commit/f0a54e89e1d1fd559465b27e926a66acbb4ec33d ?
=> [CLEANUP] clean checkstyle violations

extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java, extensions/test-src/org/pentaho/platform/web/http/filters/ProxyTrustingFilterTest.java
- in KarafBootTest, clear "karaf.data" property to eliminate other tests' influence
- ProxyTrustingFilterTest, re-implement assertions and fix Checkstyle violations
@pentaho-nbaker, @rmansoor, @pamval, review it please. This PR fixes failed tests (http://10.177.176.19/job/master-snapshot/job/platform-base/121/testReport/)
=> [TEST] - fix failed tests

assembly/package-res/biserver/tomcat/webapps/pentaho/docs/InformationMap.jsp
=> [BACKLOG-6227] Update Help URL for all products.

user-console/source/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java
authentication-provider "super" allow to administrate users and roles
=> BACKLOG-6891  SystemAdmin superuser is unable to reset the admin password

user-console/source/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java
authentication-provider "super" allow to administrate users and roles
=> BACKLOG-6891 SystemAdmin superuser is unable to reset the admin password

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/org/pentaho/platform/osgi/KarafInstance.java, extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java, extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
Switching strategy to copy Karaf dir instead of just changing location of cache in order to be consistent with config
=> [BACKLOG-7141] - Parameterizable Karaf dir

extensions/src/org/pentaho/platform/plugin/action/kettle/DIServerConfig.java, extensions/src/org/pentaho/platform/plugin/action/kettle/KettleSystemListener.java, extensions/test-src/org/pentaho/platform/plugin/action/kettle/DIServerConfigTest.java
If repository is not configured, use in-process PurRepository as current user
=> [BACKLOG-7135]Default Kettle webapp to PurRepository

assembly/assembly.properties, assembly/ivy.xml
=> [BACKLOG-7589] Added kettle-json-plugin and kettle-xml-plugin to assembly

assembly/assembly.properties, assembly/assembly.xml, assembly/ivy.xml
=> Sync with master

extensions/test-src/org/pentaho/platform/osgi/SystemPackageExtrapolatorTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/ArchiveLoaderTest.java
- SystemPackageExtrapolatorTest.testJBossProvider()
- ArchiveLoaderTest.testWillContinueToLoadOnException()
- ArchiveLoaderTest.testWillImportAllZipsInADirectory()
=> [TEST] fix failing unit tests in pentaho-platform

extensions/src/org/pentaho/platform/osgi/KarafInstance.java, extensions/src/org/pentaho/platform/settings/PortFileManager.java, extensions/src/org/pentaho/platform/settings/ServerPort.java, extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java, extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java, extensions/test-src/org/pentaho/platform/settings/ServerPortTest.java
PortAssigned.txt that was removed.
=> [BACKLOG-7604] Added a manager to write and update the karaf ports file

user-console/source/org/pentaho/mantle/client/MantleApplication.java, user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java, user-console/source/org/pentaho/mantle/rebind/EventBusUtilGenerator.java
Seems to be sane to merge even before reporting plugin.
@tmorgner
=> Async execution enhancements

repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java
authorization's actions refreshes after plugins loaded
=> BACKLOG-7363 Operation Permissions from plugins are not used in merged server

extensions/import-export-jmeter.jmx, extensions/src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/RepositoryImportResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorIT.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/FileResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
- Update command line processer to keep the admin role check for backup and restore
- Made the advance import options as an optional switches for command line utility
=> [BACKLOG-7846] - Allow non admin to download from their home folder

core/src/org/pentaho/platform/engine/core/audit/MessageTypes.java
We need a canceled status code, since we have started to cancel something. See original case for details.
=> [BACKLOG-7898] - add new cancelled status for better audit logging

extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperIT.java
Updated version of https://github.com/pentaho/pentaho-platform/pull/2929.
=> [BISERVER-12815] - Manage Data Sources: User can import an .xmi using "Import Analysis"

core/ivy.xml, extensions/ivy.xml, repository/ivy.xml
Reverts pentaho/pentaho-platform#2946
=> Revert " [BACKLOG-8389] - Upgrade antlr to version 3.4 across Pentaho product suite - changes for pentaho platform repository"

core/src/org/pentaho/platform/util/web/MimeHelper.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/FileResourceTest.java, repository/src/org/pentaho/platform/repository/RepositoryDownloadWhitelist.java, scheduler/src/org/pentaho/platform/scheduler2/email/Emailer.java, scheduler/test-src/META-INF/javamail.providers, scheduler/test-src/org/pentaho/platform/scheduler2/email/EmailerTest.java, scheduler/test-src/org/pentaho/platform/scheduler2/email/MockMail.java
=> BACKLOG-8067 - Embed HTML in email body

assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml, assembly/package-res/biserver/pentaho-solutions/system/importExport.xml
@tmorgner probably we should consider having another 5 places to apply your changes to in case you want to add new file extension :)
=> BACKLOG-9185 - Downloaded zip doesn't contain corresponding *.eml file

extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
=> BISERVER-13240 If browsers' primary language is not set to en_US Analyzer schemas are not shown to the users

user-console/source/org/pentaho/mantle/client/commands/AdhocRunInBackgroundCommand.java
Just for Wingman. Please don't merge.
=> BACKLOG-7817 - Location prompt in report viewer: custom prompting dialog

assembly/package-res/biserver/pentaho-solutions/system/default-plugin/resources/messages/messages.properties
- menu item name from 'Kettle Status' to 'PDI Status'
=> [BACKLOG-9331] Applying UX recommendation

user-console/source/org/pentaho/mantle/client/commands/AdhocRunInBackgroundCommand.java
=> CLEANUP - Useless logging

assembly/assembly.properties
- The new product codes are:
- PLAC - Pentaho Platform Community Edition
- PLAE - Pentaho Platform Enterprise Edition
=> [BACKLOG-9432] Update the Pentaho Server's product code

core/src/org/pentaho/platform/core/mt/Tenant.java, core/test-src/org/pentaho/platform/core/mt/TenantTest.java, core/test-src/org/pentaho/platform/engine/security/SimpleUserTest.java
Please review @pedrofvteixeira @pdesai16 @niehusa @pentaho-jlien @pentaho-mracine
=> [TEST] Adds SimpleUser and Tenant tests

extensions/src/org/pentaho/platform/web/http/api/resources/UserSettingsResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserSettingsResourceTest.java
Please review  @pedrofvteixeira @pdesai16 @niehusa @pentaho-jlien @pentaho-mracine
=> [TEST] Increase Unit Test Coverage 

extensions/ivy.xml, extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
=> SP-2771 Backport of BISERVER-13240 - If browsers' primary language is not set to en_US Analyzer schemas are not shown to the users (6.1 Suite)

extensions/ivy.xml, extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
=> SP-2770 Backport of BISERVER-13240 - If browsers' primary language is not set to en_US Analyzer schemas are not shown to the users (5.4 Suite)

extensions/src/org/pentaho/platform/plugin/action/mdx/MDXBaseComponent.java
@pamval , @lucboudreau , @rfellows , could you review it, please
=> [BISERVER-12069] fix regression

extensions/src/org/pentaho/platform/plugin/action/mdx/MDXBaseComponent.java
[BISERVER-12069] fix regression
@pamval , @lucboudreau , @rfellows , could you review it, please
=> [SP-2790] fix regression

extensions/src/org/pentaho/platform/plugin/action/mdx/MDXBaseComponent.java
pick [BISERVER-12069] fix regression
@pamval , @lucboudreau , @rfellows , @mchen-len-son ,  you review it, please
=> [SP-2791] fix regression

api/test-src/org/pentaho/platform/api/data/DBDatasourceServiceExceptionTest.java, api/test-src/org/pentaho/platform/api/monitoring/snmp/SnmpVariableTest.java, assembly/assembly.xml
@pentaho/rogueone Please review the changes.
This pull request needs to be merged along with
https://github.com/pentaho/pentaho-platform-ee/pull/950
=> [BACKLOG-9695] [TEST] Rename the 'merged-server' archive distributions to 'pentaho-server', add unit tests to increase code coverage.

api/test-src/org/pentaho/platform/api/action/ActionPreProcessingExceptionTest.java, api/test-src/org/pentaho/platform/api/engine/ActionSequenceExceptionTest.java, api/test-src/org/pentaho/platform/api/engine/SolutionFileMetaAdapterTest.java, api/test-src/org/pentaho/platform/api/engine/security/userroledao/AccessDeniedExceptionTest.java, api/test-src/org/pentaho/platform/api/engine/security/userroledao/AlreadyExistsExceptionTest.java, api/test-src/org/pentaho/platform/api/engine/security/userroledao/NotFoundExceptionTest.java, api/test-src/org/pentaho/platform/api/engine/security/userroledao/UncategorizedUserRoleDaoExceptionTest.java, api/test-src/org/pentaho/platform/api/scheduler/BackgroundExecutionExceptionTest.java, api/test-src/org/pentaho/platform/api/util/PentahoChainedExceptionTest.java, api/test-src/org/pentaho/platform/api/util/PentahoCheckedChainedExceptionTest.java
@pentaho/rogueone Just added couple unit tests, please review.
=> [TEST] Add unit tests, increasing code coverage

core/src/org/pentaho/platform/util/xml/XMLParserFactoryProducer.java, core/src/org/pentaho/platform/util/xml/w3c/XmlW3CHelper.java, core/test-src/org/pentaho/platform/util/TestAll.java, core/test-src/org/pentaho/platform/util/XmlTestConstants.java, core/test-src/org/pentaho/platform/util/XmlW3CHelperTest.java, extensions/src/org/pentaho/platform/plugin/action/kettle/KettleSystemListener.java, extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/src/org/pentaho/platform/plugin/services/importer/LocaleImportHandler.java, extensions/src/org/pentaho/platform/plugin/services/importer/XActionImportHandler.java, extensions/src/org/pentaho/platform/web/http/context/PentahoSolutionSpringApplicationContext.java, extensions/src/org/pentaho/platform/web/servlet/ContextDiscoveryServlet.java, extensions/src/org/pentaho/platform/web/servlet/SolutionEngineInteractivityService.java, extensions/test-src/org/pentaho/platform/plugin/action/kettle/KettleSystemListenerTest.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/LocaleImportHandlerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/XActionImportHandlerTest.java, extensions/test-src/org/pentaho/platform/web/http/context/PentahoSolutionSpringApplicationContextTest.java
- replaced all XMLBuilderFactory calls with a our own factory which produces security check activated builders
- added unit tests for malicious xmls
=> [PPP-3506] XXE Security Vulnerability in xml parsers

core/test-src/org/pentaho/commons/util/repository/CreateDocumentRequestTest.java, core/test-src/org/pentaho/commons/util/repository/CreateDocumentResponseTest.java, core/test-src/org/pentaho/commons/util/repository/CreateFolderRequestTest.java, core/test-src/org/pentaho/commons/util/repository/CreateFolderResponseTest.java, core/test-src/org/pentaho/commons/util/repository/GetCheckedoutDocsResponseTest.java, core/test-src/org/pentaho/commons/util/repository/exception/CmisFaultTest.java, core/test-src/org/pentaho/platform/engine/security/messages/MessagesTest.java, core/test-src/org/pentaho/platform/engine/services/connection/PentahoConnectionFactoryTest.java, core/test-src/org/pentaho/platform/uifoundation/messages/MessagesTest.java, core/test-src/org/pentaho/platform/util/LocaleHelperTest.java, core/test-src/org/pentaho/platform/util/TestAll.java
@pentaho/rogueone Working on increasing **pentaho-core** module code coverage. Please review.
=> [TEST] Increasing pentaho-core module code coverage.

core/test-src/org/pentaho/platform/util/client/ClientUtilsTest.java
=> [TEST] Test coverage for ClientUtils

repository/test-src/org/pentaho/test/platform/security/acls/TestAclPublisher.java
@pentaho/rogueone Should now run as part as regular build
=> [TEST] Test coverage for AclPublish

core/test-src/org/pentaho/platform/engine/services/metadata/MetadataPublisherTest.java, core/test-src/org/pentaho/platform/util/client/ClientUtilsTest.java, core/test-src/org/pentaho/platform/util/client/ServiceExceptionTest.java
@pentaho/rogueone Please review.
=> [TEST] Unit tests commit for pentaho-core module

repository/test-src/org/pentaho/test/platform/security/acls/AclPublisherTest.java
@pentaho/rogueone Renamed with 'Test' as suffix.
=> [TEST] Rename test to conform with convention: "Test" as suffix

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileUtils.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryContentIT.java
default node title and locale no longer linked
=> BISERVER-12725 L10N - Home folder should start with upper-case "H" letter when localized

core/test-src/org/pentaho/platform/util/versionchecker/PentahoVersionCheckReflectHelperTest.java, extensions/src/org/pentaho/platform/plugin/outputs/ApacheVFSOutputHandler.java, extensions/test-src/org/pentaho/platform/plugin/outputs/ApacheVFSOutputHandlerTest.java
=> [TEST] Test coverage for ApacheVFSOutputHandler and PentahoVersionCheckReflectHelper

.idea/misc.xml, extensions/ivy.xml, extensions/src/org/pentaho/platform/web/http/api/resources/SystemRefreshResource.java
=> [BACKLOG-10020] - Clear report content cache

.idea/misc.xml, extensions/ivy.xml, extensions/src/org/pentaho/platform/web/http/api/resources/SystemRefreshResource.java, user-console/source/org/pentaho/mantle/client/commands/PurgeReportingDataCacheCommand.java
Reverted #3031 and changed implementation to utilize https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/412
@tmorgner if this one doesn't fit will work on the solution proposed by you
=> Backlog 10020

extensions/src/org/pentaho/platform/osgi/KarafInstanceResolverException.java, extensions/src/org/pentaho/platform/osgi/SpringSecurityLoginModule.java, extensions/test-src/org/pentaho/platform/osgi/KarafInstanceResolverExceptionTest.java, extensions/test-src/org/pentaho/platform/plugin/services/security/userrole/ldap/transform/StringToGrantedAuthorityTest.java, extensions/test-src/org/pentaho/platform/web/xsl/messages/MessagesTest.java
@pentaho/rogueone [CLEANUP][TEST] Add unit tests as well as fixing checkstyle errors.
Please review and merge the PR if no problem found.
=> [CLEANUP][TEST] Add unit tests as well as fixing checkstyle errors.

assembly/ivy.xml
http://jira.pentaho.com/browse/BACKLOG-10143
pentaho/big-data-plugin#715
=> [BACKLOG-10143]Remove pdi-spark-plugin

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileUtils.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryContentIT.java
default node title and locale no longer linked
=> SP-2863 L10N - Home folder should start with upper-case "H" letter when localized

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
- fixed localization issue
- merge only after https://github.com/pentaho/pentaho-commons-gwt-modules/pull/387
=> [BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileUtils.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryContentTest.java
default node title and locale no longer linked
=> SP-2862 L10N - Home folder should start with upper-case "H" letter when localized

assembly/assembly.xml, assembly/package-res/administration-console/resource/config/console.xml, assembly/package-res/biserver/tomcat/webapps/pentaho/webHelp/concept_adding_a_jdbc_driver.html
@pentaho/rogueone Please review.
=> [BACKLOG-10262] Update the root folder name for Pentaho Server to be 'pentaho-server'

extensions/src/org/pentaho/platform/plugin/services/security/userrole/jdbc/JdbcUserRoleListService.java, extensions/test-src/org/pentaho/test/platform/plugin/services/security/userrole/jdbc/JdbcUserRoleListServiceTest.java
=> [TEST] Fix NPE and rename test with Test suffix

extensions/test-src/org/pentaho/test/platform/plugin/services/security/userrole/ldap/DefaultLdapUserRoleListServiceTest.java
=> [TEST] increase coverage for SearchResultToAttrValueList

assembly/assembly.xml
=> [ENGOPS-2420] Fix busted wkhtmltoimage links for platform assembly build

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerIT.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
-fixed
@rmansoor 
@pentaho-nbaker
@mbatchelor
@pedrofvteixeira
=> [PDI-15551] Schedules get duplicated after doing a RESTORE using the import-export utility

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java
=> [BISERVER-12715] L10N - "Created" and "Last modified" date of file's Properties ignores localization

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java
=> [PDI-15561] Hadoop clusters do not import into the EE Repo using the import-export utility

extensions/src/org/pentaho/platform/plugin/services/importexport/legacy/MondrianCatalogRepositoryHelper.java, repository/src/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObject.java
Do not merge it yet, please
There is a workflow question: it may be done as an SP of an additional issue
=> Biserver 13084

user-console/source/org/pentaho/mantle/MantleApplication.gwt.xml
=> [SP-2904]-Backport of BISERVER-12730 - L10N - Untranslated strings in Blockout time table (5.4 Suite)

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, core/src/org/pentaho/platform/engine/core/system/PentahoSystem.java, core/src/org/pentaho/platform/engine/core/system/SystemSettings.java, extensions/src/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/test-src/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
=> [SP-2910]-Backport of BISERVER-13323 - PentahoWebContextFilter hardcodes timeout for RequireJS causing reports to not load (6.1 Suite)

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, core/src/org/pentaho/platform/engine/core/system/PentahoSystem.java, core/src/org/pentaho/platform/engine/core/system/SystemSettings.java, extensions/src/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/test-src/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
=> [SP-2911]-Backport of BISERVER-13323 - PentahoWebContextFilter hardcdes timeout for RequireJS causing reports to not load (5.4 Suite)

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java
[SP-2915][BISERVER-12715] L10N - "Created" and "Last modified" date of file's Properties ignores localization
-fixed
@rmansoor @pentaho-nbaker Could you please merge it?
=> [SP-2915][BISERVER-12715] L10N - "Created" and "Last modified" date of file's Properties ignores localization

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java
[SP-2914][BISERVER-12715] L10N - "Created" and "Last modified" date of file's Properties ignores localization
-fixed
@rmansoor @pentaho-nbaker Could you please merge it?
=> [SP-2914][BISERVER-12715] L10N - "Created" and "Last modified" date of file's Properties ignores localization

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java
=> [SP-2940] Backport of PDI-15561 - Hadoop clusters do not import into the EE Repo using the import-export utility (6.1 Suite)

core/src/org/pentaho/platform/engine/security/SecurityHelper.java
- sanitized the fechting of IAuthorizationPolicy
- refactored the fetching of the object into a getter ( to make this a testable method )
=> [CLEANUP] Refactor

assembly/package-res/biserver/pentaho-solutions/system/applicationContext-spring-security-superuser.xml
=> [BACKLOG-10623] superUser work for Spring Security 4

extensions/test-src/org/pentaho/test/platform/plugin/services/security/userrole/memory/InMemoryUserRoleListServiceTest.java
=> [TEST] Rename Test and fix up test for CI execution

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java
=> [SP-2914] Backport of BISERVER-12715 - L10N - "Created" and "Last modified" date of file's Properties ignores localization (6.1 Suite)

user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java
=> [SP-2915] Backport of BISERVER-12715 - L10N - "Created" and "Last modified" date of file's Properties ignores localization (5.4 Suite)

assembly/assembly.xml
=> [BACKLOG-11377] Upgrade version of Tomcat 8.0.37

extensions/src/org/pentaho/platform/web/http/api/resources/DirectoryResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/org/pentaho/platform/web/http/api/resources/utils/FileUtils.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/DirectoryResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/utils/FileUtilsTest.java, extensions/test-src/org/pentaho/test/platform/web/http/api/DirectoryResourceIT.java
@mbatchelor , could you review it, please?
=> Biserver 12433

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/org/pentaho/platform/osgi/KarafInstance.java, extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java
Reverts pentaho/pentaho-platform#3176
We need to test this code thoroughly before we put it in the master. Take this out for now
=> Revert "Backlog 11614"

assembly/package-res-merged-server/biserver/pentaho-solutions/system/repository.spring.xml
@pentaho/rogueone please review
=> [BACKLOG-11696] provide default values

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/org/pentaho/platform/osgi/KarafInstance.java, extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java
=> [BACKLOG-11614] Karaf temporary folders are not deleted in case of

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where thetype of schedule is selected isn't fully localized

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where thetype of schedule is selected isn't fully localized (5.4)

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (5.4.1.8)

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (6.1)

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (6.1.0.7)

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
=> [BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (7.0.0.0)

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
Reverts pentaho/pentaho-platform#3192
=> Revert "[BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (7.0.0.0)"

user-console/source/org/pentaho/mantle/client/workspace/FilterDialog.java
Reverts pentaho/pentaho-platform#3193
=> Revert "Revert "[BISERVER-12719] When creating a schedule the dialog window where the type of schedule is selected isn't fully localized (7.0.0.0)""

core/src/org/pentaho/platform/engine/services/runtime/RuntimeContext.java, core/src/org/pentaho/platform/uifoundation/chart/DashboardWidgetComponent.java, core/src/org/pentaho/platform/uifoundation/component/xml/FilterPanelComponent.java, core/src/org/pentaho/platform/uifoundation/component/xml/WidgetGridComponent.java, core/src/org/pentaho/platform/util/xml/XMLParserFactoryProducer.java, core/src/org/pentaho/platform/util/xml/dom4j/XmlDom4JHelper.java, core/test-src/org/pentaho/platform/util/XmlW3CHelperTest.java, extensions/src/org/pentaho/platform/config/PentahoObjectsConfig.java, extensions/src/org/pentaho/platform/plugin/action/xml/xquery/XQueryBaseComponent.java, extensions/src/org/pentaho/platform/plugin/services/importer/mimeType/MimeTypeListFactory.java, extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java, extensions/src/org/pentaho/platform/plugin/services/pluginmgr/FileSystemXmlPluginProvider.java, extensions/src/org/pentaho/platform/plugin/services/pluginmgr/SystemPathXmlPluginProvider.java, extensions/src/org/pentaho/platform/web/html/themes/PluginThemeResolver.java, extensions/src/org/pentaho/platform/web/html/themes/ServletContextThemeResolver.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java
- additional fix
@mbatchelor, @rmansoor, @pamval, @CodeOnCoffee, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

core/src/org/pentaho/platform/engine/services/messages/messages_de.properties, core/src/org/pentaho/platform/engine/services/messages/messages_fr.properties, core/src/org/pentaho/platform/engine/services/messages/messages_ja.properties
[BACKLOG-11760] - Localization - Fixes from Acclaro.
@tmorgner please review.
=> [BACKLOG-11760] - Localization - Fixes from Acclaro.

assembly/assembly.xml
=> [ENGOPS-2510] changing oss license file names

user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
Reverts the changes from BACKLOG-7180  and BACKLOG-9340
@tmorgner  @pamval  @kcruzada
=> [BACKLOG-11964]-Bring the loading dialog back

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerIT.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
=> [SP-2934] Backport of PDI-15551 - Schedules get duplicated after doing a RESTORE using the import-export utility (6.1 Suite)

user-console/source/org/pentaho/mantle/client/commands/PurgeReportingDataCacheCommand.java
#3252 port 
@tmorgner @kcruzada @pamval @CodeOnCoffee
=> [BACKLOG-12100]-Bring back refresh data cache endpoint

extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java
=> BISERVER-13014 "Allow scheduling" and "Hidden" checkboxes are not imported properly

core/src/org/pentaho/platform/engine/security/SecurityHelper.java
@pamval @pedrofvteixeira @kcruzada @tmorgner @CodeOnCoffee @kolinus
=> [BACKLOG-12170]-Copy authorities to session roles when becoming user

user-console/source/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/source/org/pentaho/mantle/public/themes/onyx/mantleOnyx.css, user-console/source/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-11650] - Changed perspective menu to be 24px in all themes.

extensions/ivy.xml, extensions/test-src/org/pentaho/platform/plugin/services/webservices/content/AxisServiceExecutorTest.java, extensions/test-src/org/pentaho/test/platform/plugin/services/webservices/wsdl/SampleServiceRun.java, extensions/test-src/org/pentaho/test/platform/plugin/services/webservices/wsdl/ServiceStub.java
=> [PPP-3570] - revert

api/src/org/pentaho/platform/api/repository2/unified/RepositoryFile.java
=> SP-3015 "Allow scheduling" and "Hidden" checkboxes are not imported properly

api/src/org/pentaho/platform/api/repository2/unified/RepositoryFile.java
=> SP-3014 "Allow scheduling" and "Hidden" checkboxes are not imported properly

api/src/org/pentaho/platform/api/repository2/unified/RepositoryFile.java
Reverts pentaho/pentaho-platform#3288
=> Revert "SP-3015 "Allow scheduling" and "Hidden" checkboxes are not imported properly"

user-console/source/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/source/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-11820] Fixed style issue with z-index

extensions/test-src/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
=> Revert "SP-3015 "Allow scheduling" and "Hidden" checkboxes are not imported properly

user-console/source/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-11648] fixed double scrollbar issue in sapphire theme

extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/FileResourceTest.java
Reverts pentaho/pentaho-platform#3275
=> Revert "Backport of [BACKLOG-12212] - When runing in background or scheduling .prpti and …"

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importer/MondrianImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/MondrianImportHandlerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestTest.java
This is reverts 
https://github.com/pentaho/pentaho-platform/pull/3286
=> Revert "[BISERVER-13375] Added parse-safe escaping

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importer/MondrianImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/MondrianImportHandlerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestTest.java
@rmansoor , @pamval , @rfellows please review.
This PR is related to 
https://github.com/pentaho/data-access/pull/822
Previous PR with the reversion
https://github.com/pentaho/pentaho-platform/pull/3308
Previous PR
https://github.com/pentaho/pentaho-platform/pull/3286
jira issue
http://jira.pentaho.com/browse/BISERVER-13375
=> [BISERVER-13375] Added parse-safe escaping

assembly/pom.xml, extensions/pom.xml, repository/pom.xml
- Added exclusion and scope to exclude extra libs in mven assembly
=> [BACKLOG-12101] Mavenize platform

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerIT.java
=> [PPP-3398] Schedules shows wrong next run day when Manual Rerun of reports.

user-console/source/org/pentaho/mantle/public/browser/js/browser.fileButtons.js, user-console/source/org/pentaho/mantle/public/home/js/FavoritesController.js
=> Sp 3130 - Backport of BISERVER-13392 - File or Folder name with Double Quotes added to Favorites breaks the Browse Files perspective

user-console/source/org/pentaho/mantle/public/browser/js/browser.fileButtons.js, user-console/source/org/pentaho/mantle/public/home/js/FavoritesController.js
=> Sp 3131 - Backport of BISERVER-13392 - File or Folder name with Double Quotes added to Favorites breaks the Browse Files perspective. 

repository/ivy.xml
=> [SP-3086] Use of vulnerable component PDFBox v0.7.3 - CVE-2016-2175 (6.1 Suite)

user-console/source/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java
Added checking schedule permission before 'Run in Background' dialog opening when you click on button 'Run in background'. If no schedule permission the error dialog will be the same as after clicking on 'schedule' button having no schedule rights : "Error. You don't have permission to schedule this file. Contact your  administrator for assistance"
=> BISERVER-12391 - Run in background does not work for user without 'Schedule Content' permission

extensions/src/org/pentaho/platform/web/servlet/UploadFileUtils.java, extensions/src/org/pentaho/platform/web/servlet/messages/messages.properties, extensions/test-src/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java
[PPP-3630] - UploadService limit tmp upload
=> [PPP-3629] - UploadService limit file extensions

extensions/src/org/pentaho/platform/web/servlet/UploadFileUtils.java, extensions/src/org/pentaho/platform/web/servlet/messages/messages.properties, extensions/test-src/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java
[SP-3211] - Backport of PPP-3630 - UploadService limit tmp upload
=> [SP-3209] - Backport of PPP-3630 - UploadService limit file extensions

extensions/src/org/pentaho/platform/web/servlet/UploadFileUtils.java, extensions/src/org/pentaho/platform/web/servlet/messages/messages.properties, extensions/test-src/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java
[SP-3210] - Backport of PPP-3630 - UploadService limit file extensions
=> [SP-3212] - Backport of PPP-3630 - UploadService limit tmp upload

assembly/package-res/biserver/tomcat/webapps/pentaho/jsp/PUCLogin.jsp, user-console/source/org/pentaho/mantle/public/Mantle.jsp
@pamval, @mbatchelor, @duarteteixeira, could you please take a look?
=> [MOBILE-544] - Regression of MOBILE-458 - Deep links broken on iPad

extensions/pom.xml, pom.xml, repository/pom.xml
=> [BACKLOG-12101] dependency version updates

user-console/source/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-13767] text box height changed per UX

assembly/pentaho-server-manual/pom.xml, assembly/pentaho-server/pom.xml, assembly/pentaho-server/src/main/descriptors/assembly.xml, assembly/pom.xml
=> [BACKLOG-12101] fix artifactId(s) on CE assemblies

extensions/pom.xml, pom.xml, user-console/pom.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
=> [ENGOPS-2639] json GAV change

user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/510 https://github.com/pentaho/data-access/pull/834
=> [PPP-3410]-Add an API to remove glasspane listeners

user-console/src/main/resources/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css, user-console/src/main/resources/org/pentaho/mantle/public/themes/onyx/mantleOnyx.css, user-console/src/main/resources/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
Changed padding & text-align property values.
=> [BISERVER-12721] Profile pop up window has wrong size for translated "Log out" string

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> [SP-3166] Backport of PPP-3398 - Schedules shows wrong next run day when Manual Rerun of reports. (6.1 Suite)

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> [SP-3165] Backport of PPP-3398 - Schedules shows wrong next run day when Manual Rerun of reports. (7.0 Suite)

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJob.java
Don't log actions and replace nulls with empty strings.
=> [BISERVER-13444]-Don't log actions to pro audit

scheduler/src/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJob.java
=> [SP-3182][BISERVER-13444]-Don't log actions to pro audit

scheduler/src/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJob.java
=> [SP-3181][BISERVER-13444]-Don't log actions to pro audit

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java
=> [BACKLOG-14145] Always use CONTEXT_PATH when injecting scripts

core/src/test/java/org/pentaho/platform/util/ColorHelperTest.java
=> [TEST] Increasing code coverage in core package

user-console/src/main/resources/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-14587] Menu Home has all options align center in theme Sapphire

extensions/pom.xml, extensions/src/main/java/org/pentaho/platform/web/http/context/PentahoSystemReadyListener.java
- added shutdowning repository in contextDestroyed of PentahoSystemReadyListener
=> [BISERVER-12900]-Existing lock file /opt/pentaho/server/biserver-ee/pentaho-solutions/system/jackrabbit/repository/.lock detected

user-console/src/main/resources/org/pentaho/mantle/public/home/js/home.js
=> [BACKLOG-14627][BACKLOG-14145] Fix relative path in require call

assembly/.gitignore, assembly/ivy.xml, assembly/pom.xml
https://github.com/pentaho/pentaho-vertica-bulkloader/pull/44
From branch - BACKLOG-14008
@smaring @pentaho/2-1b
=> [BACKLOG-14008] updated vertica plugin

extensions/src/org/pentaho/platform/web/servlet/GetResource.java
=> [SP-3293][PPP-3641] - getResource allows .jar file downloads

extensions/src/org/pentaho/platform/web/servlet/GetResource.java
=> [SP-3294][PPP-3641] - getResource allows .jar file downloads

assembly/pom.xml, pom.xml
Reverts pentaho/pentaho-platform#3441
=> Revert "[PDI-150559]- Updated jcl-over-slf4j to 1.7.22 version in pentaho-pla…"

core/src/test/java/org/pentaho/platform/util/StringUtilTest.java, core/src/test/java/org/pentaho/platform/util/TestAll.java, core/src/test/java/org/pentaho/platform/util/VersionInfoTest.java
Additionally,  fixed test checkstyles where appropriate and converted StringUtilTest to use junit annotations.
=> [TEST] Improved code coverage for StringUtil and VersionInfo

core/src/test/java/org/pentaho/platform/util/Base64PasswordServiceTest.java
Please review my pull request.
=> [Tests] added class Base64PasswordServiceTest so that the corresponding class has 100% code coverage

core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
@pentaho/rogueone 
Please review. Changed Iterator to be typed ListIterator so that list elements can be traversed backward.
=> [BACKLOG-14605] Shutdown system listeners in reversed order

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho.xml
=> [BACKLOG-14618] - Updated Doc link to point to version 7.1

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
"Next run" time shows real next run time now.
=> [PPP-3619] Schedules shows wrong "Next run" time/date after schedule was edited.

repository/pom.xml, repository/src/main/java/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObject.java, repository/src/test/java/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObjectTest.java
Adding some more unit test coverage for SolutionRepositoryVfsFileObject
Reviewed by @diogofscmariano
=> Adding some more unit test coverage for SolutionRepositoryVfsFileObject

extensions/src/org/pentaho/platform/web/http/context/PentahoSystemReadyListener.java
- added shutdowning repository in contextDestroyed of PentahoSystemReadyListener
=> [SP-3343][[BISERVER-12900]-Existing lock file /opt/pentaho/server/biserver-ee/pentaho-solutions/system/jackrabbit/repository/.lock detected

user-console/source/org/pentaho/mantle/public/browser/js/browser.js
=> [SP-3335] Backport of BISERVER-13484 - 7.0 Manual install on Tomcat 8.0.39- Browse files is not working (7.0 Suite)

user-console/source/org/pentaho/mantle/client/MantleApplication.java
=> [SP-3339][PPP-3410]-Add an API to remove glasspane listeners

user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/index.html
@diogofscmariano please review and merge.
=> [BACKLOG-15500] - Fixed reference to jquery

core/src/main/java/org/pentaho/platform/engine/security/event/PentahoAuthenticationSuccessListener.java
- catching the InteractiveAuthenticationSuccessEvent was removed
=> [PPP-3686] Duplicate logging for session start

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SystemResource.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/SystemResourceTest.java
- elimination the NPE
- added unit test
=> [PPP-3548]-NullPointerException at org.pentaho.platform.web.http.api.resources.SystemResource.setLocaleOverride

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/client-config-folder-enabler/plugin.xml, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/client-config-folder-enabler/web/client-config-enabler-require-js-cfg.js, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/client-config-folder-enabler/web/client-config-folder-enabler-require-js-cfg.js
Sister PR: https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/112
=> [BACKLOG-14852] - Added plugin to enable global configuration for VizAPI 3.0.

build-utils/pom.xml
@lgrill-pentaho @emartin-pentaho
=> [ENGOPS-2596] fix for javadoc and resourcedoclet

user-console/src/main/java/org/pentaho/mantle/client/commands/SessionExpiredCommand.java
A simple and effective improvement.
Why to check for the expired session periodically if the expiration time can only be increased?
Let's shedule a check to the current expiration time. If there was no activity - OK, the session is dead.
If there was - create a new timer, and so on.
=> [BISERVER-12677]-Replace periodic checks with a "just in time" check

assemblies/pentaho-server/pom.xml
=> [BACKLOG-15830] Upgrades Tomcat from 8.0.37 to 8.0.41 to remove a security vulnerability

assemblies/pentaho-server/pom.xml
@pentaho/rogueone 
**Please hold off on merging until local tests are completed**
=> [BACKLOG-15830] Upgrades Tomcat 8.0.41 to 8.0.43 to remove another security vulnerability

extensions/src/org/pentaho/platform/web/http/api/resources/SystemResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SystemResourceTest.java
- elimination the NPE
- added unit test
=> [SP-3464][PPP-3548]-NullPointerException at org.pentaho.platform.web.http.api.resources.SystemResource.setLocaleOverride

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CmdParser.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorTest.java
* Created validation for charset parameter
=> [BISERVER-12808]-There is no error message if you run import-export.bat file with invalid command

core/src/org/pentaho/platform/engine/security/event/PentahoAuthenticationSuccessListener.java
- Fix was rewritten because of the backport problems
=> [SP-3432] Backport of PPP-3686 - Duplicate logging for session start (7.0 Suite)

user-console/src/main/resources/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
=> [BACKLOG-15971] "Log Out" string issue

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
=> [BISERVER-12883] Inconsistent behavior with generated/uploaded filenames

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/PermissionsPanel.java
=> [BACKLOG-15987] Added defensive coding

assemblies/pentaho-solutions/pom.xml
@e-cuellar @emartin-pentaho @lgrill-pentaho
=> [BACKLOG-13032] groupId fix for elastic plugin

extensions/src/main/java/org/pentaho/platform/admin/GeneratedContentCleaner.java, extensions/src/test/java/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
- GeneratedContentCleaner now searches hidden generated content too.
=> [BISERVER-12930] Not all generated content is deleted after scheduling deletion of generated files

scheduler/src/it/java/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerIT.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
* Removed contradictory code
* Fixed integration test
=> [PPP-3700]-Schedule's "Start time" is changing after using "Execute now" function

core/src/main/java/org/pentaho/platform/engine/services/MessageFormatter.java, core/src/test/java/org/pentaho/platform/engine/services/MessageFormatterTest.java
- Encoding was added
- Test was added
=> [PPP-3715] Need to encode inputs to Javascript Rule

assemblies/pentaho-solutions/pom.xml
@lgrill-pentaho @emartin-pentaho @e-cuellar @ViswesvarSekar
=> [ENGOPS-3148] groupId change for mavenized kettle plugins

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring pls review
gav change for https://github.com/pentaho/pentaho-kettle/pull/3852
=> [BACKLOG-13079] - GAV change for kettle-drools5-plugin

assemblies/pentaho-solutions/pom.xml
@emartin-pentaho @lgrill-pentaho
=> [BACKLOG-13059] Mavenize pentaho-kettle/plugins/googleanalytics

core/src/test/java/org/pentaho/platform/engine/security/SecurityHelperTest.java
Test is hanging wingman builds.
@pentaho/2-1b
=> [BISERVER-13627] temporarily skip test until issue is addressed

assemblies/pentaho-solutions/pom.xml
Please Review and merge @pentaho/2-1b @smaring
=> [BACKLOG-13143] due to process of mavenizing kettle-s3csvinput-plugin GAV changed 

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please review and merge
=> [BACKLOG-13149] due to process of mavenizing kettle-sap-plugin GAV changed

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties
- Corrected messages in help info and added some additional examples of import command usage
=> [PPP-3739]-Several issues with Import-export (missing information and out-of-date)

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please Review and merge
=> [BACKLOG-13169] due to process of mavenizing kettle-sap-plugin GAV changed 

assemblies/pentaho-plugin-samples/src/main/resources/plugin-samples/exportManifest.xml
- [CHERRY-PICK] https://github.com/pentaho/pentaho-platform/commit/d3f744935f2bf1b7c171a2ccb985981b742fcb28
=> [SP-3588] Backport of BACKLOG-16489 - Pentaho Server CE - Folder 'plugin-samples' is hidden (7.1 Suite)

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerIT.java
"Execute now" function (6.1 Suite)
=> [SP-3535]-[PPP-3700]-Schedule's "Start time" is changing after using

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> [SP-3535]-[PPP-3619]-Schedules shows wrong "Next run" time/date after

assemblies/pentaho-plugin-samples/src/main/resources/plugin-samples/exportManifest.xml
Reverts pentaho/pentaho-platform#3624
=> Revert "[SP-3588] Backport of BACKLOG-16489 - Pentaho Server CE - Folder 'plugin-samples' is hidden (7.1 Suite)"

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please review
=> [BACKLOG-13099]due to process of mavenizing kettle-gpload-plugin GAV changed

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please review
=> [BACKLOG-13121] due to process of mavenizing kettle-openerp-plugin GAV changed 

extensions/pom.xml, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java
- Removed unrequired dependency
- Fixed checkstyle for ActionResource
@pentaho/rebelalliance please review
=> [BACKLOG-16372]

assemblies/pentaho-data/src/main/resources/data/set-pentaho-env.bat, assemblies/pentaho-data/src/main/resources/data/set-pentaho-env.sh, assemblies/pentaho-data/src/main/resources/data/start_hypersonic.bat, assemblies/pentaho-data/src/main/resources/data/start_hypersonic.sh, assemblies/pentaho-data/src/main/resources/data/stop_hypersonic.bat, assemblies/pentaho-data/src/main/resources/data/stop_hypersonic.sh, assemblies/pentaho-server/src/main/resources/biserver/import-export.bat, assemblies/pentaho-server/src/main/resources/biserver/import-export.sh, assemblies/pentaho-server/src/main/resources/biserver/promptuser.sh, assemblies/pentaho-server/src/main/resources/biserver/set-pentaho-env.bat, assemblies/pentaho-server/src/main/resources/biserver/set-pentaho-env.sh, assemblies/pentaho-server/src/main/resources/biserver/start-pentaho-debug.bat, assemblies/pentaho-server/src/main/resources/biserver/start-pentaho-debug.sh, assemblies/pentaho-server/src/main/resources/biserver/start-pentaho.bat, assemblies/pentaho-server/src/main/resources/biserver/start-pentaho.sh, assemblies/pentaho-server/src/main/resources/biserver/stop-pentaho.bat, assemblies/pentaho-server/src/main/resources/biserver/stop-pentaho.sh
=> [PSW-229] Script files don't have an header with Copyright data

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, core/src/test/java/org/pentaho/platform/util/ActionUtilTest.java, extensions/src/main/java/org/pentaho/platform/plugin/action/ActionInvokeStatus.java, extensions/src/main/java/org/pentaho/platform/plugin/action/ActionParams.java, extensions/src/main/java/org/pentaho/platform/plugin/action/DefaultActionInvoker.java, extensions/src/test/java/org/pentaho/platform/plugin/action/DefaultActionInvokerTest.java
Cleanup work for BACKLOG-16372
@pentaho/rebelalliance 
=> BACKLOG-16372: Cleaned up the usage of 'auto create unique filename' flag and removed an unneded method and variable

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/PermissionsPanel.java
See PPP-3760 to get a full list of changes
=> [PPP-3747]-Fixed serveral issues with ui permission panel

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please Review
=> [BACKLOG-13139]due to process of mavenizing kettle-palo-plugin GAV changed

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please Review
=> [BACKLOG-13210] maven conversion lucid-db-streaming-loader-plugin

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b @smaring Please Review
=> [BACKLOG-13218] maven conversion ms-access-bulk-loader-plugin

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
Reverts pentaho/pentaho-platform#3656
=> Revert "[PDI-15338] - BAServerUtils no longer allows creation of roles"

api/src/main/java/org/pentaho/platform/api/action/IActionAdaptor.java
=> BACKLOG-17078  Added an interface that is a adaptor to the orchestration

assemblies/pentaho-solutions/pom.xml
=> [BACKLOG-13189] GAV change for kettle-xml-plugin

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java, extensions/src/main/java/org/pentaho/platform/web/http/filters/RequestIdFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/RequestIdFilterTest.java
@pentaho/rebelalliance @pentaho/rebelalliance  In conjunction with:  https://github.com/pentaho/pentaho-platform-ee/pull/1096
=> [BACKLOG-17102] add request id

extensions/src/org/pentaho/platform/plugin/services/connections/metadata/sql/SqlMetadataQueryExec.java
=> [SP-3618] Backport of PDB-1898 - PDD - Metadata Query Editor preview throws error when condition default is null (6.1 Suite)

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/Log4jResource.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/Log4jResourceTest.java
@pentaho/rogueone @pentaho/rebelalliance 
Team, please review. This is to add a REST Endpoint so that we can change log level at runtime without restart.
This PR should be merged along with https://github.com/pentaho/pentaho-platform-ee/pull/1103
=> [BACKLOG-17201] Add ability to change log level at runtime.

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, extensions/src/main/java/org/pentaho/platform/plugin/action/ActionInvokerSystemListener.java, extensions/src/main/java/org/pentaho/platform/plugin/action/WorkItemRequestPayload.java, extensions/src/test/resources/ActionInvokerListenerTestResources/environment.json
- Unit Tests will come in a subsequent PR 
Summary of changes: 
ActionInvokerSystemListener: a System Listener which on startup of the pentaho server consumes json files  and runs the Work Item described by the json.  The json files are can be read from a configurable location as a property on the spring bean in SystemListeners.xml or the SystemListener will check the default-content folder if no location is set. 
WorkItemRequestPayload: Responsible for creating a work item from the json files.  Requires an actionId, actionClass, actionUser and actionParams in order for the payload to be valid. 
ActionResource and ActionResourceUtil:  Refactored existing code so that the SystemListener could reuse pre-existing code
ActionInvokerListenerTest: 1 successful unit test is included, more unit …
=> [BACKLOG-17085] created the capability to run actions (work-items) on startup of the pentaho server via a systemListener from json files

pom.xml
@pentaho/rogueone @pentaho/rebelalliance 
Upgrade Postgres Driver version in pentaho-platform, please review.
=> [BACKLOG-17345][BACKLOG-17351]Upgrade Postgres JDBC driver to 42.1.1 for Pentaho Platform

assemblies/pentaho-solutions/pom.xml, assemblies/pentaho-war/pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12995] changes for upstream kettle mavenization

core/src/main/java/org/pentaho/platform/workitem/WorkItemLifecycleEvent.java
To be reviewed together with the pentaho-platform-ee sibling: pentaho/pentaho-platform-ee#1113
=> [CLEANUP] Some cleanup for BACKLOG-17100.

extensions/src/main/java/org/pentaho/platform/plugin/action/ActionInvokerSystemListener.java
=> [BACKLOG-17085] NPE check on ActionInvokerSystemListener

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
=> [BACKLOG-17293] Included config for 'pentaho/context' module

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
=> [BACKLOG-17293] missing new line was causing a javascript SyntaxError

api/src/main/java/org/pentaho/platform/api/action/IActionInvoker.java, api/src/main/java/org/pentaho/platform/api/action/IWorkerNodeCredential.java
passing the credential when invoking an action
- Added default implemention of this new method
- Added default implementation of existing invokeAction() to call the new
method with null credential
- Added interface to provide user credential
=> [BACKLOG-17396] Added a new method to IActionInvoker interface to allow

api/src/main/java/org/pentaho/platform/api/action/ISecureActionInvoker.java
Added interface ISecureActionInvoker that will be used by the
ActionInvokers that communicates with secure orchestration
environment
=> [BACKLOG-17396] Reverted the changes to IActionInvoker

assemblies/pentaho-war/pom.xml, core/pom.xml, core/src/main/java/org/pentaho/platform/util/client/BiPlatformRepositoryClient.java, core/src/main/java/org/pentaho/platform/util/client/ClientUtil.java, core/src/main/java/org/pentaho/platform/util/web/HttpUtil.java, core/src/test/java/org/pentaho/platform/util/client/ClientUtilsTest.java, extensions/pom.xml, extensions/src/it/java/org/pentaho/test/platform/web/HttpUtilIT.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ProxyServlet.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/ActionResourceTest.java, pom.xml
Reverts pentaho/pentaho-platform#3692
=> Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

extensions/pom.xml, pom.xml
Reverts pentaho/pentaho-platform#3705
=> Revert "[PDI-14764] Jaro algorithm glitch"

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
=> [BACKLOG-17190] Adding osgiRoot property to access osgi resources

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, core/src/test/java/org/pentaho/platform/util/ActionUtilTest.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
Corresponding pentaho-platform-ee PR: https://github.com/pentaho/pentaho-platform-ee/pull/1150
@pentaho/rebelalliance @pentaho/rogueone
=> [BACKLOG-17861] Ensure that Chronos job name is the same as the Work Item UID shown in logs

extensions/src/main/java/org/pentaho/platform/plugin/action/ActionRunner.java, extensions/src/main/java/org/pentaho/platform/plugin/action/DefaultActionInvoker.java
@pentaho/rebelalliance @pentaho/rogueone
=> [BACKLOG-17796] WorkItemLifeCycle Event Logging occurs before Work Item Execution completes

assemblies/pentaho-war/pom.xml
- temporary fix while axis2 will not be updated
=> [PPP-3735] - adding old commons-httpclient.3.0.1 jar

core/src/org/pentaho/platform/engine/services/MessageFormatter.java, core/test-src/org/pentaho/platform/engine/services/MessageFormatterTest.java, extensions/src/org/pentaho/platform/plugin/action/javascript/JavascriptRule.java
- the place where encoding happens was changed
=> [BACKLOG-17773] XActions - Chart Component does not render image, it renders an html tag

core/src/main/java/org/pentaho/platform/util/ActionUtil.java
Related pentaho-platform PR: https://github.com/pentaho/pentaho-platform-ee/pull/1167
@pentaho/rebelalliance @pentaho/rogueone
=> [CLEANUP] Updating references to workItemId to workItemUid for consistency

repository/src/main/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStream.java, repository/src/test/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStreamTest.java
- added fix for transformations and jobs
=> [PDI-16369]-Opening a transformation or job uploaded to the repository using REST API results in "no transformer found" exception

user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTab.java
@mchen-len-son, could you please take a look?
=> [BISERVER-13603] - revert

assemblies/pentaho-war/src/main/resources/datasources/h2/context.xml, assemblies/pentaho-war/src/main/resources/datasources/hsqldb/context.xml, assemblies/pentaho-war/src/main/resources/datasources/mysql5/context.xml, assemblies/pentaho-war/src/main/resources/datasources/oracle10g/context.xml, assemblies/pentaho-war/src/main/resources/datasources/postgresql/context.xml
@mbatchelor For your review and merge.  I went back and rechecked all the changes I had tried and it turns out this DID work.  Don't know how I missed it the first time.
=> [BACKLOG-17872] - Fixed connection factory and updated tags.

extensions/src/main/java/org/pentaho/platform/web/servlet/GetResource.java
Reverts pentaho/pentaho-platform#3788
=> Revert "[SP-3702][PPP-3829] - Prevent unauthenticated download of mondrian.xm…"

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml, core/src/test/java/org/pentaho/platform/util/PropertiesHelperTest.java, core/src/test/java/org/pentaho/platform/util/beans/PropertyListFactoryBeanTest.java
@pentaho/2-1b @smaring 
Nothing functional was removed.
=> [BACKLOG-16231] Remove modrian4/mongolap from platform

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
=> [BACKLOG-18380] - PUC: Create Ruby theme

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho.xml, core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java, extensions/src/main/java/org/pentaho/platform/web/servlet/LocalizationServlet.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ServletBase.java, extensions/src/test/java/org/pentaho/platform/web/servlet/ServletBaseTest.java
- https://github.com/pentaho/pentaho-platform-ee/pull/1190
=> [BACKLOG-16943] Adding cross-origin requests handling to LocalizationSerlvet

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserChangePasswordDTO.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java, user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java, user-console/src/main/java/org/pentaho/mantle/client/admin/EmailAdminPanelController.java, user-console/src/main/java/org/pentaho/mantle/client/admin/ServiceCallback.java, user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java, user-console/src/main/resources/org/pentaho/mantle/public/MantleStyle.css
Needs https://github.com/pentaho/pentaho-commons-gwt-modules/pull/606 and https://github.com/pentaho/pentaho-commons-xul/pull/127.
=> [BACKLOG-17350] Require administrator password when changing user password

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
@pentaho/kashyyyk please review
=> [BACKLOG-18123] - PDD: Update colors and icons for the Ruby theme

core/src/main/java/org/pentaho/platform/util/Emailer.java, extensions/src/main/java/org/pentaho/platform/plugin/services/email/EmailService.java, user-console/src/main/java/org/pentaho/mantle/client/admin/EmailAdminPanelController.java
=> [BISERVER-13664]-Mail Server settings configuration sends email password

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/MetadataImportHandler.java, extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileUtils.java
Reverts pentaho/pentaho-platform#3795
=> Revert "[SP-3717][BISERVER-10319] adapted for using from other projects"

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho.xml, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ThemeResource.java, extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ThemeServlet.java
=> [BACKLOG-18838] Make ruby the default theme on PUC

user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css
@pentaho/kashyyyk please review
Should be merged with [627](https://github.com/pentaho/pentaho-commons-gwt-modules/pull/627)
=> [BACKLOG-19025/BACKLOG-19089] - Fixes ktr/ kjb icons in PUC

user-console/src/main/java/org/pentaho/mantle/client/ui/UserDropDown.java, user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
=> [BACKLOG-19114] Fix logout hover color in Ruby theme

extensions/src/main/java/org/pentaho/platform/plugin/services/email/EmailService.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/email/Emailer.java, user-console/src/main/java/org/pentaho/mantle/client/admin/EmailAdminPanelController.java
=> [SP-3774]-[BISERVER-13664] - Mail Server settings configuration sends

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho.xml, core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java, extensions/src/main/java/org/pentaho/platform/web/servlet/LocalizationServlet.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ServletBase.java, extensions/src/test/java/org/pentaho/platform/web/servlet/ServletBaseTest.java
=> [SP-3767] Backport of CDE-912 - Uncaught Error: Load timeout for modules when embedding dashboard within Pentaho Server (7.1 Suite)

repository/src/main/java/org/pentaho/platform/security/userroledao/ws/UserRoleWebService.java, repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java
[PDI-14357] Need to prohibit empty names when adding new users or roles via REST
- added checking not blank for username and role name
=> [PDI-14357] Need to prohibit empty names when adding new users or roles via REST

repository/src/main/java/org/pentaho/platform/security/userroledao/ws/UserRoleWebService.java, repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java
[SP-3796][PDI-14357] Need to prohibit empty names when adding new users or roles via REST
- added checking not blank for username and role name
=> [SP-3796][PDI-14357] Need to prohibit empty names when adding new users or roles via REST

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j.xml
@VasilinaTerehova please take a view and merge
=> [BACKLOG-16494] - Ranger for YARN: job freezes if policy for current user disabled or not exist

assemblies/pentaho-server/pom.xml
@pentaho/rogueone @pentaho/rebelalliance Please review
=> [BACKLOG-19239] Upgrades to Tomcat 8.5.23

assemblies/pentaho-server/pom.xml
=> [BACKLOG-19239] Downgrades back to Tomcat 8.0.47

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml, assemblies/pentaho-war/src/main/resources-filtered/docs/InformationMap.jsp, assemblies/pom.xml
=> [BACKLOG-19262] Started using parent poms 'doc.base.url' property

assemblies/pentaho-war/src/main/resources-filtered/docs/InformationMap.jsp, user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-blogs.html, user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-documentation.html, user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-marketplace.html
@pentaho/millenniumfalcon @pentaho/2-1b please review
=> [BACKLOG-19262] Updated direct references to mindtouch links

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java
=> [BACKLOG-19367] Use the AuthenticationProvider to validate user credentials when changing passwords

repository/src/main/java/org/apache/jackrabbit/core/security/authorization/acl/PentahoCompiledPermissionsImpl.java, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/transform/SimpleRepositoryFileDataTransformer.java
=> [BISERVER-10719]-Get error when trying to make Suzy's report hidden when

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml
=> [BACKLOG-19259] Documentation link for PUC was incomplete

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/ActionAdapterQuartzJob.java
Related PR : https://github.com/pentaho/pentaho-ee/pull/850
Equivalent PRs:
8.0: https://github.com/pentaho/pentaho-platform/pull/3928
8.0.0.0: https://github.com/pentaho/pentaho-platform/pull/3929
@pentaho/rebelalliance @pentaho/rogueone
=> [BACKLOG-19889] 'Un-wrapping' the various ParamValue types in the map to make then jackson.fasterxml (de)serializable

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ThemeResource.java
@lgrill-pentaho / @smaring / @mbatchelor / @lucboudreau
=> [PPP-3936] Fixing broken QAT build

repository/src/main/java/org/apache/jackrabbit/core/security/authorization/acl/PentahoCompiledPermissionsImpl.java, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/transform/SimpleRepositoryFileDataTransformer.java
Suzy's report hidden when logged in as admin. (8.0 Suite)
=> [SP-3940]-Backport of BISERVER-10719 - Get error when trying to make

assemblies/pentaho-war/pom.xml, extensions/pom.xml, pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

repository/src/main/java/org/apache/jackrabbit/core/security/authorization/acl/PentahoCompiledPermissionsImpl.java, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/transform/SimpleRepositoryFileDataTransformer.java
Suzy's report hidden when logged in as admin. (7.1 Suite)
=> [SP-3939]-Backport of BISERVER-10719 - Get error when trying to make

assemblies/pentaho-war/src/main/webapp/js/parameters.js, user-console/pom.xml
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/649
=> [BACKLOG-20163] Update downstreams

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
=> [BISERVER-13756]-Object Permissions Do Not Restore from Backup

extensions/src/main/java/org/pentaho/platform/plugin/action/LocalActionInvoker.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/action/DefaultActionInvoker.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/messsages/Messages.java, scheduler/src/main/resources/org/pentaho/platform/scheduler2/messsages/messages.properties, scheduler/src/test/java/org/pentaho/platform/scheduler2/action/DefaultActionInvokerTest.java
Merging the refactoring work done for IActionInvoker APIs by @pentaho-amessier
=> [BACKLOG-20789]Merge the refactoring work done for IActionInvoker APIs

api/pom.xml, core/pom.xml, extensions/pom.xml, user-console/pom.xml
@pentaho/2-1b
Depends on pentaho/pentaho-commons-xul#143
=> [BACKLOG-20423] Update downstreams
