pentaho/pentaho-platform

extensions/src/org/pentaho/platform/plugin/services/importer/LocaleImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/LocaleImportHandlerTest.java
Bug fixed in two modules: pentaho-platform and pentaho-platform-migrator.
See pull request pentaho/pentaho-platform-migrator#249
=> Backport of BISERVER-11537 - Folder Name in PUC different than name attribute used in index.xml after import utility (5.0)

extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/src/org/pentaho/platform/web/http/api/resources/RepositoryImportResource.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
Mondrian schema cache to be cleared for all cubes on Server
Formerly cache clearing used an unnecessarily conservative strategy,
flushing all Mondrian catalog during any import action that caused a
reInit of the Mondrian catalog.  This may have been done in part
because the PentahoSystem cache (MONDRIAN_CATALOG_CACHE_REGION) needs
to be flushed in its entirety when changes are made, and the Mondrian
cache was being flushed at the same time.
This change separates Mondrian cache flushing from the
MondrianCatalogHelper.reInit() process, and confines cache flushing to
just the relevant catalog being added.  This eliminates cache flush
during analyzer report imports, for example, when the import does not
actually bring in a schema.  Cache clearing during .removeCatalog was
deliberately left …
=> [BISERVER-12360] Importing or uploading an Analyzer report triggers

user-console/source/org/pentaho/mantle/public/home/index.jsp
Check Fully Qualified Server URL in web.xml to determine if HTTPS should be used for BrightCove Javascript URL
=> [BISERVER-11812] Avoid HTTPS Mixed Content Warning

extensions/diserver-extensions-jmeter.jmx
What was done:
1) changed JMeters to reflect removed from doc methods (per Nick Baker we
should remove blockout/* as they are not autohandled and content related
methods as they do not have sence for DI server )
=> BACKLOG-1177  Document the Scheduling REST API for PDI

extensions/src/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java
* Adds common Require-JS properties to the `requireCfg` object.
* Also includes an `requireCfg.config.service` object, for easier configuration of the proposed Common-UI's AMD plugin (whose AMD module id is `service`).
See associated pull-request https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/361.
@pentaho-nbaker please review.
=> [BACKLOG-2467] - Implement a standard method for registering Javascript plugin objects

extensions/src/org/pentaho/platform/web/http/api/resources/JAXBContextResolver.java
This issue appeared after https://github.com/pentaho/pentaho-platform/commit/95b4b631a4ca772e2a6c05cf444e1abf169aee1a
Details:
Function "updateFolderPermissionButtons" from browser.folderButtons.js file expects array of permissions from REST (http://localhost:8080/pentaho/api/repo/files/%3Apublic/canAccessMap?permissions=1). But if result list contains single item JAXB converts it to json as object but not the array.
For example, {"setting":{"name":"1","value":"true"}}
For fixing it I added name of XmlRootElement entity Settings.java. Now response looks like: {"setting":[{"name":"1","value":"true"}]}
Now the same behavior exists for REST /plugin-manager/settings/{settingName}.
Example response: {"Item":{"@type":"setting","name":"common-ui","value":"true"}}
It's not a problem if client of …
=> [BACKLOG-3379] REGRESSION: PUC paste functionality is disabled

extensions/src/org/pentaho/platform/plugin/action/olap/impl/OlapServiceImpl.java, extensions/test-src/org/pentaho/platform/plugin/services/olap/OlapServiceImplTest.java
many unnecessary flush/load schema calls
This change splits out flushes of hosted and remote.  For hosted
connections we only need to invoke .flushSchemaCache on a single
catalog, since that will clear the schema pool.  We can't make that
assumption for remote.
=> [BISERVER-12591]  Flushing the Mondrian Schema Cache invokes

extensions/src/org/pentaho/platform/plugin/action/olap/impl/OlapServiceImpl.java, extensions/test-src/org/pentaho/platform/plugin/services/olap/OlapServiceImplTest.java
This change splits out flushes of hosted and remote.  For hosted
connections we only need to invoke .flushSchemaCache on a single
catalog, since that will clear the schema pool.  We can't make that
assumption for remote.
=> [SP-1956] - Backport of BISERVER-12591 - Flushing the Mondrian Schema Cache invokes many unnecessary flush/load schema calls (5.3 Suite)

repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoTest.java
Future-develop was merged with master and code line conflicts require updating unit tests to run.
These tests were failing because repositoryVersionManager was null, these tests existed in master
before the merge and had no knowledge of this class. Mocking out repositoryVersionManager resolves this issue.
=> [TEST] - Fixing platform unit tests

extensions/src/org/pentaho/platform/osgi/KarafBoot.java
[CLEANUP] - replacing import of org.apache.tika.io.IOUtils with one from apache commons-io
=> [CLEANUP] - replacing import of org.apache.tika.io.IOUtils with one from apache commons-io

extensions/build.xml
«Many problems with running javadoc stem from command lines that have become too long - even though the error message doesn't give the slightest hint this may be the problem. If you encounter problems with the task, try to set the useexternalfile attribute to true first.»
Full text at the page https://ant.apache.org/manual/Tasks/javadoc.html
=> BISERVER-12646  Cannot run program javadoc.exe: The filename or extension is too long

extensions/test-src/org/pentaho/test/platform/plugin/pluginmgr/PluginManagerNotConfiguredTest.java
- changed platform-core#BaseTest.getSpringApplicationContext() visibility to 'protected', need to reflect that in this platform-extensions' unit test
=> [TEST] fixed method visibility

extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
Removed canAdminister call from function and its associated test. The Jira case has this endpoint listed as not admin only.
=> [BACKLOG-4549] - Retrieve list of all runtime roles associated to a user

extensions/src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepository.java, extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryConcurrencyTest.java, extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryTest.java
- cherry picked from commit 93b5ecd
- add a test revealing a vulnerability in getMetadataRepositoryFile()
- fix the issue
- cherry picked from commit 00c98b5
- apply formatting and improve the code by explicitly setting collections' sizes, checking log level, removing useless assignments, etc
- cherry picked from commit 09f727c
- prevent getDomainIds() and getMetadataRepositoryFile() from reloading domains on each call
- add a test case with reading and storing domains
- cherry picked from commit 491ee25
- release read lock as soon as possible to prevent deadlocks
- fix PentahoMetadataDomainRepositoryTest
@pentaho-nbaker, @rmansoor, @e-cuellar, @mdamour1976, review it please.
This is a backport of https://github.com/pentaho/pentaho-platform/pull/2413 and …
=> [SP-1988] - Backport of BISERVER-12642 - Inconsistent synchronization leading to deadlock between JCR and PentahoMetadataDomainRepository (5.4 Suite)

core/test-res/solution/system/logs/audit/PentahoAuditLog.log, repository/src/org/pentaho/platform/repository2/unified/jcr/RepositoryCleaner.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/RepositoryCleanerTest.java, scheduler/ivy.xml, scheduler/src/org/pentaho/platform/scheduler2/gc/RepositoryCleanerSystemListener.java, scheduler/src/org/pentaho/platform/scheduler2/gc/RepositoryGcJob.java, scheduler/test-src/org/pentaho/platform/scheduler2/gc/RepositoryCleanerSystemListenerTest.java
- this is not a backport!
- create a class inside platform-repository to be a startpoint of running GC
- create a system listener and a job inside pentaho-scheduler to be able to run the GC
@mbatchelor, @pmalves, review it please.
/cc @pamval
=> [SP-2051] - Backport of BISERVER-12637 - Jackrabbit's ds_repos_datastore table can grow out of control causing performance issues (5.4 Suite)

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java
Exposed the REST api for operation permissions, to add permissions and remove them from existing role. Added unit tests to the REST and service layers.
=> [BACKLOG-4382] - Create public REST interfaces for Operation Permissions

api/src/org/pentaho/platform/api/data/IJndiDatasourceService.java, api/src/org/pentaho/platform/api/data/IPooledDatasourceService.java, core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/JndiDatasourceService.java, core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceService.java, extensions/src/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProvider.java, extensions/src/org/pentaho/platform/plugin/boot/PentahoBoot.java
- introduce two interfaces for sharing different data source providers
- update PlatformKettleDataSourceProvider to implement ExtendedDSProviderInterface
@pentaho-nbaker, @rmansoor, please review it.
This PR comes together with pentaho/pentaho-kettle#1657 and **should not be merged before it**
/cc @pamval
=> [SP-1979] - Backport of PDI-13961 - Spoon firstly tries to conect via JNDI although connection type is JDBC (5.4 Suite)

extensions/ivy.xml, repository/ivy.xml, repository/src/org/pentaho/platform/repository/solution/filebased/DecoratedFileContent.java, repository/src/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileContent.java, repository/src/org/pentaho/platform/repository/solution/filebased/SolutionRepositoryVfsFileObject.java
Required new methods on some classes due to interface changes.
These methods are assumed to be unused.  Most will currently
throw UnsupportedOperationException.
!! Do not merge until we get the official go-ahead for VFS2.1.
=> [BACKLOG-4922]  Upgrade to vfs2.1.

extensions/src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepository.java, extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryTest.java
- fix a problem with getting NPE when removing a domain
- update test to detect the problem
This PR fixes a problem with getting NPE on each call of ```removeDomain()```. It is easy to see, that firstly the domain is removed from the cache, when the cache is accessed to obtain the domain once again to pass it for AclHelper and apparently the cache returns ```null```.
@mbatchelor, @pentaho-nbaker, @rmansoor, review it please.
=> [BISERVER-12642] - Inconsistent synchronization leading to deadlock between JCR and PentahoMetadataDomainRepository

extensions/src/org/pentaho/platform/plugin/services/repository/RepositoryCleanerSystemListener.java, extensions/src/org/pentaho/platform/plugin/services/repository/RepositoryGcJob.java, extensions/test-src/org/pentaho/platform/plugin/services/repository/RepositoryCleanerSystemListenerTest.java, repository/src/org/pentaho/platform/repository2/unified/jcr/RepositoryCleaner.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/RepositoryCleanerTest.java
- create a class inside platform-repository to be a startpoint of running GC
- create a system listener and a job inside pentaho-extensions to be able to run the GC
- prohibit Listener returning false except the case when Scheduler has not
been found
- add tests
(adopted from commits a38048c, 191c608, 299f8b0)
@mbatchelor, @pentaho-nbaker, @rmansoor, review it please.
Since there is no enough time to implement planned solution, it was decided to move changes from 5.4  to have some.
=> [BISERVER-12637] - Jackrabbit's ds_repos_datastore table can grow out of control causing performance issues

extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java
Added new name checking for REST rename method.
@pentaho-nbaker @rmansoor could you please review.
=> [SP-2082] Backport of BISERVER-12476 - PUC accepts invalid characters when renaming a file (5.4 Suite) - REST fix

core/src/org/pentaho/platform/engine/core/system/objfac/AbstractSpringPentahoObjectFactory.java, core/src/org/pentaho/platform/engine/security/event/OrderedApplicationEventMulticaster.java, core/src/org/pentaho/platform/engine/services/audit/AuditConnection.java, core/test-src/org/pentaho/platform/engine/security/event/OrderedApplicationEventMulticasterTest.java, repository/src/org/pentaho/platform/repository/usersettings/UserSettingService.java, repository/src/org/pentaho/platform/repository2/unified/jcr/DefaultPermissionConversionHelper.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileAclUtils.java, repository/src/org/pentaho/platform/security/policy/rolebased/RoleAuthorizationPolicy.java
- UserSettingService
- replace keySet() + get() combination with entrySet()
- remove useless object instantiation
- remove useless explicit map.remove()
- AbstractSpringPentahoObjectFactory
- add logger.isDebugEnabled()
- remove useless non-null validation
- OrderedApplicationEventMulticaster
- replace ArrayList with array for faster sorting
- extract stateless Comparator to a final field to avoid useless instantiation
- replace new Integer.compareTo() with Integer.compare()
- add tests
- RoleAuthorizationPolicy
- create ArrayLists of exact size
- JcrRepositoryFileAclUtils
- iterate through List, not Set
- DefaultPermissionConversionHelper
- replace indexOf(":") with indexOf(':') as it is more effective
- AuditConnection
- change the order: first try to obtain a connection and only then …
=> [BACKLOG-4709] - Small changes in platform to improve performance

user-console/source/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js
Added trimming for new name value.
@pentaho-nbaker @rmansoor could you please review.
=> Backport of BISERVER-12476 - PUC accepts invalid characters when renaming a file

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestMondrian.java, extensions/src/org/pentaho/platform/plugin/services/importexport/legacy/MondrianCatalogRepositoryHelper.java
on export: generate the ExportManifestMondrian with a new, optional element for a reference to the annotations file in the zip for this mondrian schema.
on import: drop the annotations file into the same folder in /etc/mondrian/<catalog-name>/ as the schema.xml file. One caveat, if the annotations file is imported first, the catalog folder is hidden by default. Had to make a change on the addHostedCatalog method of MondrianCatalogRepositoryHelper to set that to not be hidden when the schema file is added. Otherwise, the model will not appear in PUC.
=> [BACKLOG-4446] - Handling inline-modeling annotations on backup/restore of mondrian schemas.

assembly/ivy.xml, extensions/ivy.xml, extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java, extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestDto.java, extensions/src/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestMetaStore.java, extensions/src/org/pentaho/platform/plugin/services/messages/messages.properties
[BACKLOG-4445] - Implementation of exporting the metastore as part of backup/restore
Overview:
- get the metastore from the pur respoitory
- convert it to an xml metastore
- zip it up
- add that zip to the export zip as metastore.zip
- add a new type in the export manifest to support this.
=> [BACKLOG-4445] - Implementation of exporting the metastore as part of backup/restore

assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml, assembly/package-res/biserver/pentaho-solutions/system/importExport.xml, extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importer/MetaStoreImportHandler.java, extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/MetaStoreImportHandlerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
Added a new import handler for metastore import (supports mime type "application/vnd.pentaho.metastore" and extension is mzip (just a regular zip file however, but different to allow for another handler other than the SolutionImportHandler).
Expects the mzip file to contain the zipped up contents of an XmlMetaStore. This is extracted to a temp location on the fs to allow it to be loaded in as an XmlMetaStore before walking the structure and copying it to the repository meta store.
=> [BACKLOG-4449] -Implement the MetaStore portion of the Import process

extensions/src/org/pentaho/platform/plugin/services/pluginmgr/DefaultPluginManager.java
This is a same changes we made to the PentahoSystemPluginManager https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/org/pentaho/platform/plugin/services/pluginmgr/PentahoSystemPluginManager.java#L715
=> [BACKLOG-4328] - Adding the PentahoBeanScopeProcessor to the plugin manager

api/src/org/pentaho/platform/api/usersettings/IAnyUserSettingService.java
This is to support working with user settings for other users than the one on the active session. Basically for backup/restore initially, but could be useful in some admin tool down the road.
The plan will be for this interface to get folded into the IUserSettingService in the future, probably at the next major release. But we can't change that interface now.
=> [BACKLOG-4444] - Adding an interface to extend the IUserSettingService

assembly/package-res/biserver/tomcat/webapps/pentaho/WEB-INF/classes/ehcache.xml, repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProviderTest.java
- re-implement the previous commit with proper usage of cache regions
- add default settings to ehcache.xml
@pentaho-nbaker, review it please.
If this is needed to be backported, then the regions will be created programmatically
/cc @mbatchelor, @pamval
=> [BISERVER-12657] - SpringSecurityPrincipalProvider uses static maps instead of CacheManager

assembly/ivy.xml
[BACKLOG-5430] - xalan 2.7.0 has a defect that causes NPE when editing XML files
=> [BACKLOG-5430] - xalan 2.7.0 has a defect that causes NPE when editing XML files

scheduler/ivy.xml, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/QuartzSchedulerTest.java, scheduler/test-src/org/pentaho/platform/scheduler2/quartz/test/QuartzSchedulerTest.java
- backport tests from scheduler2/quartz and scheduler2/quartz/test
- ignore one test that depends on unbackported changes
- add Mockito 1.8.5 dependency
@pamval, review it please. This PR makes tests in 5.4 and master consistent with an exception for one case, which depends on BACKLOG-5291 - I marked it with ```@Ignore```.
However, since http://jira.pentaho.com/browse/BISERVER-12297 is planned to be backported and it needs the changes from BACKLOG-5291, then it makes sense to leave the marked case now and to uncomment it later.
=> [TEST] - Backport QuartzScheduler's tests from master

repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProviderTest.java
- move internal maps to cache regions
- ensure the regions exists
- add tests
(cherry picked from commits 886e154, 610ed8c, 564cab9)
@pentaho-nbaker, @rmansoor, @mdamour1976, @e-cuellar, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2626, https://github.com/pentaho/pentaho-platform/pull/2630 and https://github.com/pentaho/pentaho-platform/pull/2632. I squashed the commits and didn't touch ```ehcache.xml```
=> [SP-2166] - Backport of BISERVER-12657 - SpringSecurityPrincipalProvider uses static maps instead of CacheManager (6.0 Suite)

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelper.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelperIT.java
- add additional check to prevent NPE in getAclNode()
- add tests
@rmansoor, @pentaho-nbaker, review it please.
This is a guarding condition to prevent NPEs
=> [PPP-3409] - Manage DataSources dialog can't be opened: Error retrieving ACL Node

extensions/ivy.xml, extensions/src/org/pentaho/platform/web/http/api/resources/RepositoryPublishResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishService.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/RepositoryPublishResourceTest.java, extensions/test-src/org/pentaho/test/platform/web/http/api/RepositoryPublishResourceIT.java
- introduce new endpoint '/repo/publish/file' which expects path to be encoded
- deprecate existing and fix their javadocs
- add tests
- update jersey-related artifacts in test condiguration to 1.16 that is used in compile configuration
@pentaho-nbaker, @mbatchelor, @pamval, review it please.
In addition to the tests (where the actual storing in repository is not checked), I verified the case locally, after building my own platform and my own report-designer. It became possible to publish files with quotes
=> [BISERVER-11565] - File upload names fail if the name has double quotes

api/src/org/pentaho/platform/api/repository2/unified/IUnifiedRepository.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDao.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoTest.java
- catch JCR's exception and return null instead
- add test
- add logging on JCR's exception
- update java docs
- fix checkstyle violations for affected classes
(cherry picked from commits 82ccbc0, 9fdc0ff)
@pentaho-nbaker, @rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2654 and https://github.com/pentaho/pentaho-platform/pull/2659
=> [SP-2195] - Backport of BISERVER-12758 - DefaultUnifiedRepository.getFileById() throws exception if none was found (5.4 Suite)

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelper.java
- change getFileById() handling so, that it is able to cope with both exception and null
@pamval, @bkemper-pentaho, review it please.
=> [BISERVER-12758] - DefaultUnifiedRepository.getFileById() throws exception if none was found

api/src/org/pentaho/platform/api/repository2/unified/IUnifiedRepository.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelper.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDao.java
- catch JCR's exception and return null instead
- add logging on JCR's exception
- change getFileById() handling so, that it is able to cope with both exception and null
- add test
- update java docs
- fix checkstyle violations for affected classes
(cherry picked from commits 82ccbc0, 9fdc0ff, 160fcc4)
@pentaho-nbaker, @rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2654, https://github.com/pentaho/pentaho-platform/pull/2659, https://github.com/pentaho/pentaho-platform/pull/2667
=> [SP-2196] - Backport of BISERVER-12758 - DefaultUnifiedRepository.getFileById() throws exception if none was found (6.0 Suite)

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelper.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelperTest.java
- add additional checks to prevent NPE in getAclNode()
- add tests
(cherry picked from commits 4078564, 5e6ab46)
@pentaho-nbaker, @rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2397 and https://github.com/pentaho/pentaho-platform/pull/2656
=> [SP-2193] - Backport of PPP-3409 - Manage DataSources dialog can't be opened: Error retrieving ACL Node (5.4 Suite)

repository/src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelper.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrAclNodeHelperTest.java
- add additional check to prevent NPE in getAclNode()
- add tests
@pentaho-nbaker, @rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2656
=> [SP-2194] - Backport of PPP-3409 - Manage DataSources dialog can't be opened: Error retrieving ACL Node (6.0 Suite)

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_Caching_Test.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java
- introduce "verify-user-on-emitting-principal" property to indicate whether or not to call USerDetailsService on emitting new principal
- set its default value to false
- add tests
- fix Checkstyle violations
@pentaho-nbaker, review it please.
/cc @rmansoor, @mbatchelor, @pamval
=> [BISERVER-12189] - JCR becomes very slow when there are too many home directories > 400

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_Caching_Test.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java
- introduce "verify-user-on-principal-creation" property to indicate whether or not to call USerDetailsService on emitting new principal
- set its default value to true to keep backward-compatibility
- add tests
- fix Checkstyle violations
(cherry picked from commit 6b326c2)
@pentaho-nbaker, @rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2686
=> [SP-2228] - Backport of BISERVER-12189 - JCR becomes very slow when there are too many home directories > 400 (6.0 Suite)

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java
- introduce "verify-user-on-principal-creation" property to indicate whether or not to call USerDetailsService on emitting new principal
- set its default value to true to keep backward-compatibility
- add tests
- fix Checkstyle violations
@rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2686
=> [SP-2229] - Backport of BISERVER-12189 - JCR becomes very slow when there are too many home directories > 400 (5.4 Suite)

assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml
Cherry-picked from https://github.com/pentaho/pentaho-platform/pull/2695
Added prptstyle extension to ImportHandlerMimeTypeDefinitions.xml config file.
@pentaho-nbaker, @dkincade, @rmansoor could you please review?
=> [SP-2269] Backport of BISERVER-10705 - PUC gives you an error if you try to upload prptstyle file (6.0 Suite)

assembly/package-res/biserver/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml
Cherry-picked (with conflict merge) from https://github.com/pentaho/pentaho-platform/pull/2695
Added prptstyle extension to ImportHandlerMimeTypeDefinitions.xml config file.
@pentaho-nbaker, @dkincade, @rmansoor could you please review?
=> [SP-2270] Backport of BISERVER-10705 - PUC gives you an error if you try to upload prptstyle file (5.4 Suite)

extensions/src/org/pentaho/platform/web/http/api/resources/DirectoryResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/org/pentaho/platform/web/http/api/resources/utils/FileUtils.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileService_CreateDir_IT.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/utils/FileUtilsTest.java, repository/test-src/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryBase.java
- introduce new method in FileService with validation of input path
- change FileResource and DirectoryResource to use it
- extract common procedure for validation
- add tests
- fix Checkstyle violations for all affected classes and make some cleanup
(adopted from commit bfa720450f2f982e238862dd1f040e9e054ece35)
@rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2722
=> [SP-2333] - Backport of BISERVER-12506 - Folder creation: reserved character validation is only being done client-side (6.0 Suite)

user-console/source/org/pentaho/mantle/client/admin/ContentCleanerPanel.java, user-console/source/org/pentaho/mantle/client/admin/JsEmailConfiguration.java, user-console/source/org/pentaho/mantle/client/admin/PermissionsPanel.java, user-console/source/org/pentaho/mantle/client/commands/NewDropdownCommand.java, user-console/source/org/pentaho/mantle/client/solutionbrowser/fileproperties/SelectUserOrRoleDialog.java, user-console/source/org/pentaho/mantle/client/ui/xul/JsPerspective.java, user-console/source/org/pentaho/mantle/client/ui/xul/JsTheme.java, user-console/source/org/pentaho/mantle/client/ui/xul/JsXulOverlay.java, user-console/source/org/pentaho/mantle/client/usersettings/JsSetting.java, user-console/source/org/pentaho/mantle/client/workspace/SchedulesPanel.java
- replace all eval() with JSON.parse() in self-written javascript functions
@pentaho-nbaker, @rmansoor, @mdamour1976, @e-cuellar, review it please.
Also, I'd be grateful if you give me a hint on how to implement tests for these changes
=> [PPP-3452] - Mantle uses eval() for parsing JSON - this is a tremendous security vulnerability. It should use JSON.parse

extensions/src/org/pentaho/platform/web/http/api/resources/UserSettingsResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserSettingsResourceTest.java, user-console/source/org/pentaho/mantle/public/home/js/FavoritesController.js, user-console/source/org/pentaho/mantle/public/home/js/favorites.js
@rfellows @rmansoor 
Please review.
I did not use ESAPI for encoding on the server side because client's dojox/html/entities cannot decode such values as "&#х27;", "&#х2F;", and so on, and as far as i understand esapi4js is not included in this project, so to be sure that every value will be decoded on the client side, I replaced 4 symbols manually.
=> PPP-3464 - Security Vulnerability- Stored Cross-Site (XSS) Scripting

repository/src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java, repository/test-src/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDaoTest.java
@pentaho-nbaker, @pamval, could you merge it please. This is backport of https://github.com/pentaho/pentaho-platform/pull/2718 to 6.0. Here is one for 5.4: https://github.com/pentaho/pentaho-platform/pull/2760
=> [SP - 2397] - Backport of BISERVER-12614 - Changing password not active on BA cluster environment (6.0 Suite)

extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
- backport the original fix
- make SolutionImportHandlerTest OS-independent
(adopted from commits 96dbdd5, 8ddb236)
@rfellows, review it please. This is a backport pf https://github.com/pentaho/pentaho-platform/pull/2647 and https://github.com/pentaho/pentaho-platform/pull/2774
=> [SP-2412] - Backport of BISERVER-12851 - Restore (import/export) - Schedules are not being restored. (6.0 Suite)

extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/org/pentaho/platform/web/http/api/resources/operations/CopyFilesOperation.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/org/pentaho/platform/web/http/api/resources/utils/RepositoryFileHelper.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/operations/CopyFilesOperation_CopyTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/operations/CopyFilesOperation_DeepFolderCopyTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java, extensions/test-src/org/pentaho/test/platform/web/http/api/FileResourceIT.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDao.java, repository/src/org/pentaho/platform/repository2/unified/jcr/JcrStringHelper.java, repository/test-src/org/pentaho/platform/repository2/unified/jcr/JcrStringHelperTest.java, user-console/source/org/pentaho/mantle/client/commands/RestoreFileCommand.java
**FileService**
- Move the logic of file-copy method to CopyFilesOperation class, represent copy file operation as an immutable object, and move specific method (used only from copyFiles method) to this CopyFilesOperation class.
- Small optimisation in doRestoreFilesToHomeFolder method, when no overwrite mode (passing only non-conflict files for copy operation)
**CopyFilesOperation**
- Contains all the logic of FileService  doCopyFiles method (copy with every possible mode is devided into a separete method). 
- Added a possibility to copy folders, performing deep copy folder.
*Note:* I found no reason to limit deepness of folders hierarchy (the worst possible consequence - long scanning)
**RepositoryFileHelper**
- Class, where some methods from FileService were replaced (so as to be able …
=> [BISERVER-12794] Permissions can delete but not restore file

user-console/source/org/pentaho/mantle/rebind/EventBusUtilGenerator.java
- in EventBusUtilGenerator, change JSON object generating approach: use `"` instead of `'` to follow ECMA standard
@mdamour1976, review it please. This previous commit broke PUC, as `JSON.parse` rejects `'` as quoting signs.
We need a lot of backslashes here, because  " inside "" should be escaped as `\"`, and that `\` should be escaped as well -- `\\`, and two quotes need their own escaping...
I build mantle locally, and Browse File works now.
/cc @pamval
=> [PPP-3455] - Dynamic code injection vulnerabilities found

assembly/package-res-merged-server/biserver/pentaho-solutions/system/pentahoServices.spring.xml, assembly/package-res-merged-server/biserver/pentaho-solutions/system/repository.spring.properties, assembly/package-res-merged-server/biserver/pentaho-solutions/system/repository.spring.xml, dev_build.xml, repository/src/org/pentaho/platform/repository2/unified/webservices/jaxws/DiUnifiedRepositoryJaxwsWebService.java
- the class that needs relocating from EE to CE is DiUnifiedRepositoryJaxwsWebService.java from pentaho-platform-ee to pentaho-platform
- added to pentaho-platform-repository
- package is EE was "com.pentaho..", now becomes "org.pentaho..."
- ADDITIONALLY also added new ant targets for a "Pentaho (merged) server CE" build ( we have the "assemble" target, now we have a new one "assemble-merged-server" )
=> [BACKLOG-6636] Make the necessary code changes from EE to CE

assembly/assembly.xml
Added two new targets. This will make sure that Pentaho EE and Pentaho CE is being build with same ant targets
=> [BACKLOG-6626] - Adding required ant targets to build Pentaho Server CE

extensions/test-src/org/pentaho/platform/config/SystemConfigFolderTest.java, extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java, extensions/test-src/org/pentaho/test/platform/web/http/api/JerseyTestUtil.java
- in SystemConfigFolderTest, use slashes explicitly
- in PentahoMetadataDomainRepositoryTest, ensure the path is separated with slashes
- in SchedulerResourceUtilTest, explicitly set EST timezone
- in JerseyTestUtil, replace direct strings comparing with separate elements validation, as Jersey has started adding space between mime type and parameters since some version
@rmansoor, @pamval, @kolinus, @aliakseihaidukou, review it please
=> [TEST] - fix some tests for Windows and non-EST users

extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
**UserRoleDaoResource**
- Track every update of roles, and if this update is touching a user in current session, updating IPentahoSession.SESSION_ROLES attribute, that represents the roles, avalible for current user.
We are doing it via userRoleDaoService, because data there is always up-to-date
- Added few helper methods and changed visibility of some methods for testing reasongs
**UserRoleDaoResource_RoleUpdatesTest**
- A separate test, written specially for checking, that roles were/were not (depending on whether user is session-user or not) updated.
**UserRoleDaoResourceTest**
- Changed few tests a little,(added several mocks), as method content changed.
@rmansoor, @mdamour1976, @pentaho-nbaker, @e-cuellar , review it please
=> [BISERVER-11649] Mondrian role mappers don't pass the role name of a user when his username and group are both 'Admin'

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/org/pentaho/platform/osgi/KarafInstance.java, extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
Removing config read test, adding property to tell Karaf to use working dir as parent cache dir
=> [PDI-15058] - Read only install fix

extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java, extensions/test-src/org/pentaho/platform/web/http/filters/ProxyTrustingFilterTest.java
- in KarafBootTest, clear "karaf.data" property to eliminate other tests' influence
- ProxyTrustingFilterTest, re-implement assertions and fix Checkstyle violations
@pamval, @rmansoor, @pentaho-nbaker, review it please. This is a backport of   
https://github.com/pentaho/pentaho-platform/commit/a330dd2e192146b191de9e358db2c76f5c3cec4b to fix failing test
=> [TEST] - fix failed tests

assembly/package-res/biserver/pentaho-solutions/system/jackrabbit/repository.xml
- SearchIndex tag is to be left commented-out ( rather than deleted/removed )
- Placed a small note to provide some context on this tag
=> [BACKLOG-7198] Disable jackrabbit/repository.xml's SearchIndex tag

assembly/package-res/biserver/pentaho-solutions/system/jackrabbit/repository.xml
- typo fix: incorrect comment closing tag that ended up causing a 'org.xml.sax.SAXParseException; lineNumber: 480; columnNumber: 6; The string "--" is not permitted within comments.'
=> [BACKLOG-7128] Disabling Jackrabbit Index

assembly/package-res/biserver/pentaho-solutions/system/jackrabbit/repository.xml
- SearchIndex tag is to be left commented-out ( rather than deleted/removed )
- Placed a small note to provide some context on this tag
=> [CHERRY-PICK][BACKLOG-7198] Disable jackrabbit/repository.xml's SearchIndex tag

extensions/src/org/pentaho/platform/plugin/action/kettle/DIServerConfig.java, extensions/src/org/pentaho/platform/plugin/action/kettle/KettleSystemListener.java, extensions/test-src/org/pentaho/platform/plugin/action/kettle/DIServerConfigTest.java
If repository is not configured, use in-process PurRepository as current user
BACKPORT of https://github.com/pentaho/pentaho-platform/pull/2855
http://jira.pentaho.com/browse/BACKLOG-7135
=> [BACKLOG-7135]Default Carte to PurRepository

extensions/src/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/org/pentaho/platform/web/servlet/ThemeServlet.java
* Antecipation of the declaration of the `active_theme` variable so that it is visible by require-js-cfg files is needed for the theming technique used by the VizAPI.
* The new global variable `PENTAHO_CONTEXT_NAME` is needed for the VizAPI to know the current context and provide a current/default context `pentaho.type.Context` instance/singleton.
=> [BACKLOG-8251] Webcontext.js changes

core/ivy.xml, extensions/ivy.xml, repository/ivy.xml
Replace antrl-2.7.6, antlr-runtime-3.1.1 with antlr-3.4-complete which contains antlr-2.7.7 and antlr-runtime-3.4.
antlr-2.7.6 is used by hibernate-core version 3.6.9.Final. Differences between antrl-2.7.6 and antrl-2.7.7 do not impact on hibernate-core;
antlr-runtime-3.1.1 is used by drools-compiler-5.0.1. Differences between antrl-runtime-3.1.1 and antrl-runtime-3.4 don`t impact on drools-compiler-5.0.1.
To build pentaho-platform it previously needs to build:
- pentaho-reporting (pentaho-reporting-engine-classic-core) as it was changed to use antlr-3.4-complete (https://github.com/pentaho/pentaho-reporting/pull/790);
- pentaho-kettle (kettle-engine) as it has dependency on pentaho-reporting.
=>  [BACKLOG-8389] - Upgrade antlr to version 3.4 across Pentaho product suite - changes for pentaho platform repository

user-console/source/org/pentaho/mantle/public/browser/js/browser.dialogs.templates.js
@rmansoor, this PR should be merged right after the: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/782 since in new handlebars version is included lexical validation
=> [PPP-3510] - Use of vulnerable component - handlebars.js v1.0.0-rc.3

core/ivy.xml, extensions/ivy.xml, repository/ivy.xml
Replace antrl-2.7.6, antlr-runtime-3.1.1 with antlr-3.5.2 which contains antlr-2.7.7.
antlr-2.7.6 is used by hibernate-core version 3.6.9.Final. Differences between antrl-2.7.6 and antrl-2.7.7 do not impact on hibernate-core;
To build pentaho-platform it previously needs to build:
- pentaho-reporting (pentaho-reporting-engine-classic-core) as it was changed to use antlr-complete-3.5.2 (pentaho/pentaho-reporting#792);
- pentaho-kettle (pentaho/pentaho-kettle#2665) as it has dependency on pentaho-reporting.
=> [BACKLOG-8389] - Upgrade antlr to version 3.5.2 across Pentaho product suite - changes for pentaho platform repository

extensions/ivy.xml
security vulnerability CVE-2015-3253 - groovy before version 2.4.4
=> [PPP-3536] - Updated groovy to version 2.4.7 due to CVE-2015-3253

build-utils/ivy.xml, extensions/ivy.xml, repository/ivy.xml
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

core/ivy.xml, extensions/ivy.xml, repository/ivy.xml
Set transitive to false for hibernate-core and explicitly added necessary dependencies to the core module;
Removed the exclude tag for antlr from the extensions module.
=> [BACKLOG-8389] - Upgrade antlr to latest stable version across Pentaho product suite - changes for pentaho platform repository

extensions/build.properties, extensions/ivy.xml, scheduler/.classpath
For extensions module, defined the property dependency.javassist.revision and
used it in ivy.xml
=> [BACKLOG-10323] Standardize of javassist version 3.20.0-GA

extensions/src/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java, extensions/src/org/pentaho/platform/plugin/services/importexport/ImportSession.java, extensions/src/org/pentaho/platform/web/http/api/resources/RepositoryImportResource.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/RepositoryImportResourceTest.java
ACL Information that can reappear
- now session is cleaning at the end of importfile
- added unit tests
=> [BISERVER-13309] Perminent JCR folder deletion leaving residual orpaned

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/exporter/strategies/ExportStrategyUtil.java, extensions/src/org/pentaho/platform/plugin/services/exporter/strategies/IExportStrategy.java, extensions/src/org/pentaho/platform/plugin/services/exporter/strategies/JackrabbitExportStrategy.java, extensions/src/org/pentaho/platform/plugin/services/exporter/strategies/LdapExportStrategy.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/strategies/JackrabbitExportStrategyTest.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/strategies/LdapExportStrategyTest.java
- fixed
@rmansoor 
@pentaho-nbaker
Wingman failed test, that is not connected with my changes (at first run).
=> [BISERVER-13332] The ACLs selection disappear from all groups/roles on BA server after doing a RESTORE using the Import-Export utility

extensions/src/org/pentaho/platform/web/http/api/resources/GeneratorStreamingOutput.java
[BACKLOG-10832] - guard against a null MimeTypeCallback throwing an error
=> [BACKLOG-10832] - guard against a null MimeTypeCallback throwing an error

extensions/src/org/pentaho/platform/osgi/KarafBoot.java, extensions/test-src/org/pentaho/platform/osgi/KarafBootTest.java, extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
* Used io deleteOnExit except of nio FileUtils
* Changed symlinks failure logginf from error to warns (as we still copy that files)
=> [BACKLOG-9649]-System is not able to delete the karaf folder created in the temporary folder location

assembly/ivy.xml
- Excluded the dependency streambuffer.jar that is pulled in by
jaxws-spring
=> [BACKLOG-10623] Upgrade springframework and spring security

assembly/package-res/biserver/pentaho-solutions/system/repository.spring.xml
back in.
- The repository.spring.xml defines two TransactionManager
jcrTransactionManager and jcrAdminTransactionManager of same
type but with different ids. Marking jcrTransactionManager as
primary so it can be resolved correctly
=> [BACKLOG-11374] PUC - After a session is timed out, I am unable to log

user-console/source/org/pentaho/mantle/MantleApplication.gwt.xml
table
- enabled GWT i18n for supported languages
=> [SP-2903][BISERVER-12730] L10N - Untranslated strings in Blockout time

user-console/source/org/pentaho/mantle/MantleApplication.gwt.xml
- enabled GWT i18n for supported languages
=> [BISERVER-12730] L10N - Untranslated strings in Blockout time table

core/src/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java, core/src/org/pentaho/platform/engine/services/messages/messages.properties, core/test-src/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelperTest.java
PooledDatasourceHelper.convert calls would fail when initializing big
data drivers due to not being in the caller's CL.
Modified to use the IDriverLocator.initialize where possible,
similar to what had already been done for pooled connections.
http://jira.pentaho.com/browse/BACKLOG-11273
=> [BACKLOG-11273]  ERRORs logged with big-data connections

extensions/ivy.xml
@pentaho/rogueone Upgrade to commons-fileupload-1.3.2. Please review.
=> [BACKLOG-11322] Resolve Security Vulnerabilities around Apache Common File Upload

assembly/package-res/biserver/tomcat/webapps/pentaho/jsp/PUCLogin.jsp
@pentaho/millenniumfalcon @pamval please review.
This code broke because there was a change to the ".attr()" behaviour in jquery 1.6 when ".prop()" was introduced.
Now ".attr('value', ...)" only changes the attribute's value which specifies the initial value. To change the actual value we need to use ".prop('value', ...) to change the actual property value for a given dom element.
=> [BACKLOG-11583] Login UI breaks eval login, if wrong user/pass entered

assembly/assembly.xml, extensions/ivy.xml
@CodeOnCoffee @rmansoor @mbatchelor @pentaho/rogueone Please review
Related PRs:
https://github.com/pentaho/pentaho-platform/pull/3207
https://github.com/pentaho/pentaho-reporting/pull/869
https://github.com/pentaho/pentaho-reportdesigner-ee/pull/53
https://github.com/pentaho/pentaho-kettle/pull/3087
=> [BACKLOG-11621] Removes JTDS driver dependency

assembly/package-res/biserver/tomcat/webapps/pentaho/WEB-INF/tld/c.tld, extensions/ivy.xml
@mbatchelor, @pamval, @CodeOnCoffee, here is backport of https://github.com/pentaho/pentaho-platform/pull/3112/files to 6.1. Thanks.
=> [SP-2953] - Backport of PPP-3560 - Use of vulnerable component taglibs:standard:1.0.6 CVE-2015-0254 (6.1 Suite)

user-console/source/org/pentaho/mantle/client/commands/PurgeReportingDataCacheCommand.java
Our main fix for the cache refresh works like a charm, but we forgot that the old refresh functionality now also uses the plugin endpoint.
So both refresh button and "Tools" work the same way - clean cache for one session :(
The fix is easy - bring back the old url for "Tools".
🙏 
@tmorgner @kcruzada @CodeOnCoffee @pamval
=> [BACKLOG-12100]-Bring back refresh data cache endpoint

extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalog.java, extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/test-src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogTest.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java
@rmansoor , @pamval , @rfellows please review.
BISERVER-13375 (http://jira.pentaho.com/browse/BISERVER-13375)
Ideas of this are: 
1. to get additional parameters from **dataSourceInfo**, and to put in **mondrianParameters** 
(https://github.com/VadimPolynkov/pentaho-platform/blob/ff17302cffffcabd81c9e8ee2ebc39e241659803/extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java#L266-L268)
2. to move getting of parameters in separate method of **MondrianCatalog** (https://github.com/VadimPolynkov/pentaho-platform/blob/ff17302cffffcabd81c9e8ee2ebc39e241659803/extensions/src/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalog.java#L87-L89)
3. to write unit test where it is checked that parameters were added to exportManifest.
Export execution …
=> [BISERVER-13375] Fixed export of additional parameters

extensions/src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
[PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility
- fixed problem restoring job parameters as pdi parameters
- added backup pdi parameters
- added restoring pdi parameters
@mdamour1976 Could you please review and merge it?
My changes improved unit test coverage in my changes files.
=> [PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility

extensions/src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
[SP-3056][PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility
- fixed problem restoring job parameters as pdi parameters
- added backup pdi parameters
- added restoring pdi parameters
=> [SP-3056][PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility

extensions/src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/JobScheduleRequest.java, extensions/src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java, extensions/src/org/pentaho/platform/web/http/api/resources/services/SchedulerService.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/ScheduleExportUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java, extensions/test-src/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java
[SP-3057][PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility
- fixed problem restoring job parameters as pdi parameters
- added backup pdi parameters
- added restoring pdi parameters
=> [SP-3057][PDI-15689] Log level set for schedules do not preserve after doing a RESTORE using the import-export utility

extensions/src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/org/pentaho/platform/plugin/services/importer/MondrianImportHandler.java, extensions/test-src/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importer/MondrianImportHandlerTest.java, extensions/test-src/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestTest.java
@rmansoor , @pamval , @rfellows please review.
This PR is related to [PR](https://github.com/pentaho/data-access/pull/819) in data-access.
[jira issue](http://jira.pentaho.com/browse/BISERVER-13375), [previous PR](https://github.com/pentaho/pentaho-platform/pull/3270)
This PR contains following changes:
1. ExportManifestTest has tests which check special characters is successfully processed through replacing by XML-escaped substitutes. Marshall and unmarshall methods work correctly. Sequential methods calls (toXml(), fromXml()) return original string. ([link](https://github.com/pentaho/pentaho-platform/compare/master...VadimPolynkov:BISERVER-13375-parameters?expand=1#diff-4144b3cdf3be937fedc42ba05c6dd1afR247)).
In addition, output stream contains XML-escaped characters …
=> [BISERVER-13375] Added parse-safe escaping

user-console/source/org/pentaho/mantle/client/commands/PasteFilesCommand.java
The issue is that when we click on 'paste' in a hidden folder , first, gwt paste command makes a request for the children of the folder without url parameter "showHidden" regardless of the fact whether "show hidden" option is selected or not. But since the folder is hidden it is unavailable without request param 'showHidden'. That causes NPE.
=> BISERVER-13531 - Admins are unable to copy/paste into a hidden folder

assembly/package-res/biserver/tomcat/webapps/pentaho/jsp/PUCLogin.jsp, core/src/org/pentaho/platform/engine/core/system/BasePentahoRequestContext.java, core/test-src/org/pentaho/platform/engine/core/system/BasePentahoRequestContextTest.java
@pamval, @mbatchelor, @duarteteixeira, here is fix for both server and client sides. Server side fix is done in order to prevent server from being hanged off in case of js will be turned off in browser. Thanks.
=> [BISERVER-13463] - White screen displayed forever when Pentaho accessed with wrong URL having double slash

extensions/pom.xml
@pamval , @mbatchelor , @mchen-len-son, @bmorrise
please review. These changes removes jackrabbit-data test-jar from build. Thus they should fix the (ivy-related) issue with platform-ee build. (see the similar issue: https://issues.apache.org/jira/browse/JCR-3876)
=> [BACKLOG-14709] - 7.1-QAT-187:It's impossible to connect to Pentaho Server in PUC, Spoon

assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, assembly/package-res/biserver/tomcat/webapps/pentaho/WEB-INF/web.xml, extensions/src/main/java/org/pentaho/platform/web/http/filters/PreFlightReportingFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PreFlightReportingFilterTest.java
MS Excel behaves wierd, when opening a file from IE. It sends OPTION requests ( OPTION+HEAD requests in case of XHR ) before opening a file. Pentaho responds with 401 and the file is not opened.
Also, sometimes Excel thinks that the file is broken. In such case it tries to load the content one more time ( another GET ) and repair it. When failed,  it will prompt you a warning message but will open the file anyway. We can't do anything with this particular case without setting a session cookie. And we definitely don't want to do so.
The fix is in returning 200 status for OPTION and HEAD requests for the report content urls.
It adds not so big overhead ( 2 string equals in most cases ).
Unfortunately we won't be able to use it as is in SP cases. We can't change a web.xml. I made the method …
=> [BISERVER-12916]-Add a filter to handle MS Office pre-flight requests

extensions/ivy.xml, extensions/pom.xml, pom.xml
[PDI-15929] Salesforce Input step throws a Incompatible class exception when run on server in 7.0
-old jar removed from the server platform
force-partner-api.jar from plugins contains necessary classes
@mdamour1976 @matthewtckr  Could you please review and merge it?
=> [PDI-15929] Salesforce Input step throws a Incompatible class exception when run on server in 7.0

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
Unsafe character - pipe line "|" replaced with "%7C".
=> [BISERVER-13484] 7.0 Manual install on Tomcat 8.0.39- Browse files is not working

assembly/pom.xml
Removing the salesforce artifact which by being reintroduced reverts the change for PDI-15929 orginally committed here: https://github.com/pentaho/pentaho-platform/pull/3418
=> [CLEANUP] removing salesforce dependency

extensions/pom.xml
Missing jackrabbit test dependencies were causing tests to fail.
http://cerberus.pentaho.com/job/master-snapshot/job/platform-base/44/consoleFull
=> [ENGOPS-2897] Add org.apache.jackrabbit.spi.* test dependencies

user-console/src/main/java/org/pentaho/mantle/client/commands/SaveCommand.java
@pentaho/rogueone 
Please review. 
The fix is to do a URI encoding on file name user entered. So that special characters won't break succeeding JSON response.
=> [BACKLOG-11933][PDB-1938] Encode URI for the tab name when user input contains special characters

assembly/package-res/biserver/pentaho-solutions/system/applicationContext-spring-security.xml, assembly/package-res/biserver/pentaho-solutions/system/pentaho.xml, assembly/package-res/biserver/tomcat/webapps/pentaho/WEB-INF/web.xml, extensions/src/main/java/org/pentaho/platform/web/http/filters/PreFlightReportingFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PreFlightReportingFilterTest.java
- moved the filter registration to a Spring config
- the filter is now applied only to affected urls not to /**
- only HEAD and OPTIONS http methods are anonymously accessible
- removed a URL pattern configuration from a pentaho.xml
- sending a 405 code instead of 200 for a valid semantics, Excel understands it
- reverted changes in the web.xml
- the test is updated respectively
=> [BISERVER-12916]-Refactored a PreFlightFilter

core/src/main/java/org/pentaho/platform/engine/core/system/osgi/OSGIUtils.java, core/src/test/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactoryTest.java
The 'and' filter syntax only has a `&` at the begining, not between operands. Was causing `InvalidSyntaxException`.
Also changed the util function so it returns a simple filter if only one property exists.
@pentaho/millenniumfalcon and @pentaho-nbaker please review.
=> [BACKLOG-14990] Fix OSGi 'and' filter invalid syntax

assemblies/pentaho-server/src/assembly/assembly.xml
@pentaho/2-1b pls review
removed jsp-api-2.1.jar from tomcat/lib, the jsp-api.jar is already present in a standard tomcat installation, but on linux it fails to startup PUC correctly if it loads that jar specifically.
=> [CLEANUP] removing unnecessary jsp-api-2.1.jar from tomcat/lib folder

scheduler/src/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
=> [SP-3302] Backport of PPP-3619 - Schedules shows wrong "Next run" time/date after schedule was edited. (7.0 Suite)

extensions/ivy.xml
-old jar removed from the server platform
force-partner-api.jar from plugins contains necessary classes
@mdamour1976 @matthewtckr Could you please review and merge it?
=> [SP-3324][PDI-15929] Salesforce Input step throws a Incompatible class exception when run on server in 7.0

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ldap.xml, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ClassloaderSwitcherInterceptor.java
- Fixed regression which was caused by switching to the spring-ldap-2.1.0
=> [BISERVER-13473] JMS Connection for destination 'snmpQueue' error after switching to LDAP authentication on Pentaho 7

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho.xml, extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/CasAuthenticationProvider.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilterTest.java, user-console/src/main/java/org/pentaho/mantle/client/commands/SessionExpiredCommand.java
Will fail due to unmerged gwt https://github.com/pentaho/pentaho-commons-gwt-modules/pull/559
The command is started by a script included globally https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1009
A cookie usage allows us to cover both regular and asynchronous requests without modifications in spring-security.
Checked with JCR/LDAP/CAS - works as expected.
The settings file will not be backported, the feature is enabled by default.
=> [BISERVER-12677]-Session-expiry cookie an logic

extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilterTest.java, user-console/src/main/java/org/pentaho/mantle/client/commands/SessionExpiredCommand.java, user-console/src/test/java/org/pentaho/mantle/client/commands/SessionExpiredCommandTest.java
The logic was broken in case a client clock was desynchronized with a server one. 
By desynchronized I don't mean a timezone difference, cause it won't affect a UNIX timestamp, but just a wrong time set on a client machine.
The idea of the fix is in calculating the offset between server and client time and taking it into account when making a decision about the expired session.
Was tested on a local and remote server with valid, past and future time setting.
Also covered by the unit tests.
=> [BISERVER-12677]-Eliminate difference between server and client clock

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/PermissionsPanel.java
This PR is a complement to https://github.com/pentaho/pentaho-platform/pull/3531
Inherits checkbox is disabled if:
- It's a folder at root level
- It's a folder under home folder
=> [BACKLOG-15987] Add check to disable inherits check box in root folders

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RolesWrapper.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UsersWrapper.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/SystemService.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
-XML hard-coded response is removed.  Now the answer type (XML or JSON) depends on Accept header.
-The previous type of xml aswer (as in pentaho documentation) is  retained
=> [BISERVER-13579]- REST API /userrolelist/getRolesForUser and /userrolelist/getUsersInRole don't return JSON

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/PermissionsPanel.java
before the confirmation dialog, if the user cancel in the "Inherit folder
permission" dialog.
=> [BACKLOG-15986] Reset the state of add and remove button to the value

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DriverNotInitializedException.java, core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledDatasourceSystemListener.java, core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java, core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledDatasourceSystemListenerTest.java, core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelperTest.java
The issue was caused by throwing and not handling unchecked RuntimeException. Added add a new unchecked exception, which would be catched and logged in DynamicallyPooledDatasourceSystemListener only. By doing this we won't affect other places
=> [BISERVER-13575] - DynamicallyPooledDatasourceSystemListener causing startup issues when driver can not be initialized

assemblies/pentaho-plugin-samples/src/main/resources/plugin-samples/exportManifest.xml
- CE plugin-samples's exportManifest.xml has the 'isHidden' flag set to 'true'
- https://github.com/pentaho/pentaho-platform/blob/7.1.0.0/assemblies/pentaho-plugin-samples/src/main/resources/plugin-samples/exportManifest.xml#L26 
- EE also holds a plugin-samples's exportManifest.xml, that also has the 'isHidden' flag set to 'true'
- https://github.com/pentaho/pentaho-platform-ee/blob/7.1.0.0/assemblies/pentaho-solutions-ee/src/main/resources/pentaho-solutions/plugin-samples/exportManifest.xml#L26
We switch CE plugin-samples's 'isHidden' flag to 'false', leaving EE's the way it is.
=> [BACKLOG-16489] Pentaho Server CE - Folder 'plugin-samples' is hidden

assemblies/pentaho-plugin-samples/src/main/resources/plugin-samples/exportManifest.xml
Reverts pentaho/pentaho-platform#3595
- @kcruzada , @dkincade , @pamval the EE-8.0-SNAPSHOT under which this was tested / validated gave a "false positive". A more recent EE SNAPSHOT build show that now the "plugin-samples" folder appears **visible** by default, with this change. Issuing a PR to revert this change.
Will re-open this issue and continue looking into it.
=> Revert "[BACKLOG-16489] Pentaho Server CE - Folder 'plugin-samples' is hidden"

extensions/src/main/java/org/pentaho/platform/plugin/action/olap/impl/OlapServiceImpl.java, extensions/src/test/java/org/pentaho/platform/plugin/services/olap/OlapServiceImplTest.java
Removing the logic which iterates each hosted catalog,
creating a connection and flushing individually.  That had
the effect of loading each schema, flushing it out, and
then loading again.  Big perf hit, and unnecessary, since
we were also invoking CacheControl.flushSchemaCache
http://jira.pentaho.com/browse/BISERVER-13633
http://jira.pentaho.com/browse/BISERVER-13631
=> [BISERVER-13633] Schema cache refresh takes too long

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java, extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java
- Return false to shouldUseFullyQualifiedUrl to make sure CONTEXT_PATH is relative
=> [BACKLOG-16728] - Using relative context path in WebContext

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages_de.properties, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages_fr.properties, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages_ja.properties, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorTest.java
- parameters were pulled out of the message bundle;
- only English parameters are allowed now.
=> [BISERVER-13621] All the command line parameters for import-export.sh/.bat are showing the localized parameters names.

api/src/main/java/org/pentaho/platform/api/action/IActionInvoker.java, extensions/src/main/java/org/pentaho/platform/plugin/action/DefaultActionInvoker.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java, extensions/src/test/java/org/pentaho/platform/plugin/action/DefaultActionInvokerTest.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/ActionResourceTest.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/ActionAdapterQuartzJob.java
In general, it is not ideal to change interface methods, however, due to the level of confusion, I think it is best to change it now, when it's still early on and we know that the interface is not being used by anyone other than those involved with worker node work, rather than live with this bad method name that only causes confusion.
@pentaho/rebelalliance 
=> Renaming IActionInvoker.runInBackgorund to invokeAction, as the original name was a misnomer and caused a lot of confusion

extensions/src/main/java/org/pentaho/platform/plugin/action/ActionInvokerSystemListener.java, extensions/src/main/java/org/pentaho/platform/plugin/action/ActionParams.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java, extensions/src/main/java/org/pentaho/platform/web/servlet/jaxrs/JacksonContextResolver.java, extensions/src/main/java/org/pentaho/platform/web/servlet/jaxrs/JacksonMessageBodyBase.java, extensions/src/main/java/org/pentaho/platform/web/servlet/jaxrs/JacksonMessageBodyReader.java, extensions/src/main/java/org/pentaho/platform/web/servlet/jaxrs/JacksonMessageBodyWriter.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/ActionResourceTest.java
This PR should be reviewed and merged together with https://github.com/pentaho/pentaho-platform-ee/pull/1117.
The purpose of this PR is to add a JAXRS message-body provider  for jackson (faster xml) json serialization. This provider will handle POJOs decorated with the JsonRootName annotation (just like JAXB POJOs are decorated with XmlRootElement). The reason for this so the provider does not interfere with the "main path" of handling json, but only when asked explicitly (by the virtue of using this decoration). Note the use of this annotation in the ActionParams class. 
This change allows a proper signature for the REST resources (not only the ActionResource) moving foward instead of failing back to plain text and having the user code in the resource be responsible for writing it …
=> [Cleanup] ActionParams auto serialization/deserialization.

core/src/test/java/org/pentaho/platform/engine/services/SoapHelperTest.java
This PR adds unit tests for SoapHelper.java
Some unusual behavior in SoapHelper was found:
- `SoapHelper.createSoapResponseDocument(String, String)` adds `"\"http://pentaho.org\""` as an activity response. All other versions of the method add `"http://pentaho.org"`.
- Calls to `SoapHelper.createSoapFaultElement()` result in a `org.dom4j.IllegalAddException`, no matter what arguments are passed. 
Given that this behavior has been present for four years, these potential issues were ignored in test cases. They may be worth addressing in the future.
=> [TEST] add tests for org.pentaho.platform.engine.services.SoapHelper

assemblies/pentaho-war/pom.xml, pom.xml
Upgrading jackrabbit version to 2.14.2
Refer to BACKLOG-17562 and PPP-3714 for details. 
Related PRs being opened to upgrade other projects that depend on jackrabbit.
@pentaho/rogueone @pentaho/rebelalliance 
pentaho-kettle: pentaho/pentaho-kettle#4174
pdi-ee-plugin: pentaho/pdi-ee-plugin#340
data-access: https://github.com/pentaho/data-access/pull/917
=> BACKLOG-17562 : Upgrading jackrabbit version to 2.14.2

extensions/src/main/java/org/pentaho/platform/plugin/action/ActionInvokerSystemListener.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/ActionResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/WorkerNodeActionInvokerAuditor.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/ActionResourceTest.java
@pentaho/rebelalliance @pentaho/rogueone 
Adds audit entry for start / finish. Since the same id is used for the complete audit trail the duration per item is cumulative -- which is the accurate duration.
=> [BACKLOG-17675] audit entry for remote execution

extensions/ivy.xml, extensions/test-src/org/pentaho/platform/web/http/api/resources/utils/EscapeUtilsTest.java
- org.codehaus.jackson.jackson-core-asl and org.codehaus.jackson.jackson-mapper-asl versions were updated to 1.9.13
- added test
=> [SP-3696] Backport of CDE-909 - It is not possible to save a CDE Dashboard with a query longer than 2000 characters (6.1 Suite)

assemblies/pentaho-solutions/pom.xml
With the effort of decoupling the steps from kettle, we need to add back the new artifact to the platform assemblies.
https://github.com/pentaho/pentaho-kettle/pull/4311
@pentaho/2-1b @smaring pls review
=> [BACKLOG-18429] adding pdi-core-plugins to pentaho-solutions assembly

core/src/main/java/org/pentaho/platform/util/ActionUtil.java
=> [BACKLOG-18791] Changed workitem invalid chars for chronos 2.4.0

assemblies/pentaho-war/pom.xml, extensions/pom.xml
Reverts pentaho/pentaho-platform#3830
Decision is to remove karaf.jaas.module from WEB-INF/lib, custom build of the artifact is not needed for now.
=> Revert "[ENGOPS-3554] Update jaas group ID for Pentaho"

assemblies/pentaho-war/pom.xml
@pentaho/rebelalliance @pentaho/rogueone 
This PR is to remove karaf.jaas.modules karaf bundle FAT jar from being packaged in WEB-INF/lib.
Please review and merge if it looks good to you.
=> [BACKLOG-18473] Removing karaf.jaas.modules karaf bundle jar from WEB-INF/lib

repository/src/main/java/org/pentaho/platform/security/userroledao/jackrabbit/JcrUserRoleDao.java, repository/src/main/java/org/pentaho/platform/security/userroledao/ws/UserRoleWebService.java, repository/src/main/resources/org/pentaho/platform/security/userroledao/messages/messages.properties, repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java
[PDI-14357] Need to prohibit empty names when adding new users or roles via REST
- added  clearing stack trace for AlreadyExistsException for cases create an user and a role
- added a correct message
=> [PDI-14357] Need to prohibit empty names when adding new users or roles via REST

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/ActionAdapterQuartzJob.java
=> [BACKLOG-18438] add scheduledFireTime param before invokeAction call to avoid NPE in BlockoutAction

scheduler/src/main/java/org/pentaho/platform/scheduler2/action/DefaultActionInvoker.java, scheduler/src/test/java/org/pentaho/platform/scheduler2/action/DefaultActionInvokerTest.java
Type safe checking looking for a stream provider was missed during one of the refactoring of the action invoke classes.
https://github.com/pentaho/pentaho-platform/blob/bdd32aeb1f6d87df00333b633e3827786034aead/scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/ActionAdapterQuartzJob.java#L152-L157
=> [BACKLOG-19002] Added type checking before casting.

repository/src/main/java/org/pentaho/platform/security/userroledao/jackrabbit/JcrUserRoleDao.java, repository/src/main/java/org/pentaho/platform/security/userroledao/ws/UserRoleWebService.java, repository/src/main/resources/org/pentaho/platform/security/userroledao/messages/messages.properties, repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java
[SP-3796][PDI-14357] Need to prohibit empty names when adding new users or roles via REST
- added  clearing stack trace for AlreadyExistsException for cases create an user and a role
- added a correct message
=> [SP-3796][PDI-14357] Need to prohibit empty names when adding new users or roles via REST

core/src/main/java/org/pentaho/platform/util/StringUtil.java, core/src/test/java/org/pentaho/platform/util/StringUtilTest.java
=> [BACKLOG-19316] Updated String util with functions to trim whitespace from lists, strings and maps. For use in workernodes

extensions/src/main/java/org/pentaho/platform/plugin/action/kettle/KettleSystemListener.java
- the order was changed: the property sets first, then the property is used in the KettleLogStore.init
=> [PDI-16368] Unable to start blueprint container for bundle pdi-dataservice-server-plugin due to unresolved dependencies

repository/src/main/java/org/apache/jackrabbit/core/security/authorization/acl/PentahoACLProvider.java, repository/src/test/java/org/apache/jackrabbit/core/security/authorization/acl/PentahoACLProviderTest.java
Related PRs:
https://github.com/pentaho/pentaho-ee/pull/817
https://github.com/pentaho/pentaho-platform-ee/pull/1223
Note that the method is being only added here, but not used within the platform code, but rather used by a sub-class in the pentaho-ee repo.
=> [BACKLOG-19566] Adding a method that checks for the existence of the jcr access control privilege

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css, user-console/src/main/resources/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css
-added overflow-y: scroll for Ruby and Sapphire themes
for avaliable and selected roles on Manage Users tab, avaliable and selected
user on Manage Roles tab
=> [BISREVER-13750]-Missing scroll bar on Manage Users Perspective when using Chrome

core/src/main/java/org/pentaho/platform/engine/core/system/BasePentahoRequestContext.java
JIRA: http://jira.pentaho.com/browse/BACKLOG-17248
Paths are filtered to remove groups of multiple slashes (as per [this](http://jira.pentaho.com/browse/BISERVER-13463) ticket). The `http://` we need gets caught in this filter though, so it gets turned into `http:/`. 
The regex was adjusted to allow an `http://` at the beginning of the string.
=> [BACKLOG-17248] Fix images/CSS in single-page HTML reports generated in background

assemblies/pentaho-solutions/pom.xml
@pentaho/2-1b depends on https://github.com/pentaho/pentaho-platform-plugin-jpivot/pull/65
=> [BACKLOG-13894] - Downstream updates

extensions/src/main/java/org/pentaho/platform/web/servlet/UIServlet.java, extensions/src/test/java/org/pentaho/platform/web/servlet/UIServletTest.java
- UIServlet was deprecated
- added escaping for the retrieved parameter
- mime type retrieving was modified in order to strongly match known mime types
- test was added
- a little refactoring was done
=> [PPP-3963] UIServlet.java needs to be removed from platform

assemblies/pentaho-server/pom.xml
Updated to the most recent release of Tomcat 8.5.X
JIRA: https://jira.pentaho.com/browse/BACKLOG-21349
The new artifact in nexus here: http://nexus.pentaho.org/content/groups/omni/org/apache/tomcat/tomcat-windows-x64/8.5.27/
Merge along with: https://jira.pentaho.com/browse/BACKLOG-21354
=> [BACKLOG-21349] Update Tomcat to 8.5.27

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, core/src/main/java/org/pentaho/platform/workitem/WorkItemLifecycleEventUtil.java
@pentaho/rogueone please review
The request of execution returns the newly generated UUID back in the Response; PS can merely log it, as it logs nowadays lines pertaining the `SUBMITTED` and `DISPATCHED` actions
To be merged on `master` alone ( i.e. 9.0 work ), and to be merged alongside https://github.com/pentaho/pentaho-ee/pull/1197
=> [BACKLOG-22228] write to log a UUID, if one was passed along

build-utils/pom.xml
=> [BACKLOG-23247] javadoc version override for build-utils

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzJobKey.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
1. Changed `QuartzJobKey` to use `randomUUID `instead of `currentTimeInMillis `to create unique QuartzJobKeys
2. Changed `QuartzScheduler` to add `MISFIRE_INSTRUCTION_FIRE_NOW` for `SimpleTrigger `with `repeatCount = 0`
3. Added more logs on `QuartzScheduler`
=> [BACKLOG-22942] Use randomUUID to generate quartzJobKey, added misfire instruction and logs

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml, extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
This PR fixes the double auth issue. For this we need the new `PentahoBasicAuthenticationEntryPoint` and we need to point the bean _basicProcessingFilterEntryPoint_ to this new class.
The change in line 26 changes the default behavior to redirect to the configured login page when an unauthenticated user tries to access a report, instead of using the browser's popup dialog. After a successful authentication, the user will e redirected back to the report.
@pmalves @pamval @mbatchelor @pedrofvteixeira
=> [BISERVER-13648] Double login after logout when viewing a report

core/src/main/java/org/pentaho/platform/util/ActionUtil.java, core/src/main/java/org/pentaho/platform/workitem/WorkItemLifecycleEventUtil.java, core/src/test/java/org/pentaho/platform/util/ActionUtilTest.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/action/ActionRunner.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/action/DefaultActionInvoker.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/ActionAdapterQuartzJob.java
Cherry-picking commits for [PR 4114](https://github.com/pentaho/pentaho-platform/commit/1e8f279e716890c438e1bc6b968909e207b2136a) and [PR 4141](https://github.com/pentaho/pentaho-platform/commit/1e8f279e716890c438e1bc6b968909e207b2136a)
Just cherry-picking commit for BACKLOG-23124 would not work as it was built on some changes for BACKLOG-22228. 
To me merged alongside https://github.com/pentaho/pentaho-ee/pull/1267
@pentaho-apandit @befc @pdesai16  @kcruzada
=> Cherry picking fix for [BACKLOG-23124] The current method of generating workItem Name is not generating unique name, causing the workItems to fail

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzJobKey.java
Changed `QuartzJobKey` to use Pentaho platform's `UUIDUtil.getUUIDAsString()` instead of `java.util.UUID.randomUUID().toString()` to generate random uuids which is much faster and Pentaho platform has been using `UUIDUtil` ( which internally uses LGPL library - Jug ) for years now.
@pentaho/rogueone @mbatchelor
=> [BACKLOG-22942] Changing java.util.UUID with Pentaho's UUIDUtil

core/src/main/java/org/pentaho/platform/workitem/WorkItemLifecycleEventUtil.java, core/src/main/java/org/pentaho/platform/workitem/WorkItemLifecyclePhase.java
Added utility method on `WorkItemLifecycleEventUtil ` and new constants on `WorkItemLifecyclePhase` to support events posting from etl-execution plugin.
To be merged alongside https://github.com/pentaho/pentaho-ee/pull/1384
=> [BACKLOG-22672] Added utility method and new work item constants

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml, core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryImportResource.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/utils/SystemUtils.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/utils/SystemUtilsTest.java, extensions/src/test/resources/SystemConfig/system/pentaho.xml, user-console/src/main/resources/org/pentaho/mantle/public/browser/index.jsp, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
1. Created a new config property `download-roles` on `pentaho.xml`. This property holds a comma-separated list of roles that can download ( outside of their home folder ) content from repository
2. Added two end endpoints on `FileResource `- `/canUpload` and `/canDownload`
3. These endpoints now calls `SystemUtils` utility methods `canUpload` and `canDownload` and defer the decision of uploading/downloading content
Per this new logic, rules for
1. Downloading content:
If a user has permissions to "Read content" and "Create content", plus one of 2: "Administrator" OR "has a role listed on `<download-roles>`
2. Uploading content: ( no changes here )
If a user has permissions to "Read content" and "Create content", plus one of 2: "Administrator" OR "Publish Content"
=> [BACKLOG-23730] As an admin I would like to have a user that could upload/download files using PUC outside of its home folder

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.folderButtons.js
JavaScript changes to display/hide file action separator. 
Essentially this is a revert of PR https://github.com/pentaho/pentaho-platform/pull/4206 - here we're  explicitly checking for a condition whether upload/download buttons are being displayed rather than not being displayed, as sometimes these buttons ( and the css for them ) are `undefined` 
=> [BACKLOG-25016] PUC File Action separators duplicated

extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/servicemgr/AxisWebServiceManager.java, extensions/src/main/java/org/pentaho/platform/plugin/services/webservices/AxisUtil.java
`setExecuteServiceId` and `setWsdlServiceId` were never used in our code base.
Should we delete these methods or deprecate them and change them so they'll throw an exception?
See JIRA case for further details and explanation of why we're doing this.
Please review and merge. @pedrofvteixeira @mbatchelor
=> [PPP-4190] Malicious code vulnerability AxisUtil.java

assemblies/pentaho-server/src/main/resources/biserver/import-export.bat, assemblies/pentaho-server/src/main/resources/biserver/import-export.sh, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorPasswordTest.java
The import/export util was using `KettleTwoWayPasswordEncoder` directly when it should use `Encr` so that high strength encryption plugins can be used, namely the `AESTwoWayPasswordEncoder`.
@pedrofvteixeira @ricardosilva88 @cravobranco @mbatchelor
=> [PPP-4160] Import-Export tool requires plain-text password

extensions/src/test/java/org/pentaho/test/platform/plugin/services/cache/CacheExpirationRegistryTest.java
Test case to stress the `CacheExpirationRegistry` class with 50 threads running `register()` / `unRegister()` 100K times each. The test shows no concurrency issues and the performance is better than any other alternative: `Lock`, `ReadWriteLock`, `synchronized` blocks, etc.
From the tests conducted, the use of the synchronized `HashMap` shows the best performance.
Using a non synchronized `HashMap` the test case fails with plenty of exceptions as expected.
Please review and merge: @mbatchelor @ricardosilva88 @pedrofvteixeira
=> [BISERVER-7181] CacheExpirationRegistry needs reviewed

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
- `canUpload` / `canDownload` are GET methods and the path to file is sent as a request parameter
- reserved chars such as `&` in the `dirPath` param were creating an incomplete/inconsistent value
@pentaho/rogueone please review
=> [BACKLOG-26250] Not able to download a file with special characters

assemblies/pentaho-war/pom.xml
Adding fasterxml jackson providers to the main classloader. This makes the provider available to serialize the `org.pentaho.database.model.DatabaseConnection` object when publishing the model with the Publish Model step in the Pentaho Server.
@pedrofvteixeira please review
=> [BACKLOG-26329] - Adding fasterxml jackson providers to the main classloader.

assemblies/pentaho-war/pom.xml
This makes the provider available to serialize the `org.pentaho.database.model.DatabaseConnection` object when publishing the model with the Publish Model step in the Pentaho Server.
@pamval Cherry picked from master.
=> [BACKLOG-26329] - Adding fasterxml jackson providers to the main classsloader.

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/system.properties, core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java, repository/src/main/java/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
It has been creaed a new property in the file system.properties, named "hideUserHomeFolderOnCreate", which by default it is set to "false". To activate the feature in this story, it is necessary to change it to "true" and restart the server.
When a new user is added/created (both through PUC interface or through Spoon interface), depending on the value of the above mentioned property, the user home folder is automatically hidden or not (hidden if the property's value is set to true, not if the property's value is set to false or any other value).
=> [BACKLOG-26593] - CLONE: Ability to Disable user folder creation under Home directory in PUC

extensions/pom.xml, pom.xml
This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/86
=> [SP-4827] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/main/resources/org/pentaho/platform/web/http/messages/messages.properties, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java
Reverts pentaho/pentaho-platform#4329
A better solution to BISERVER-14087 is in PR https://github.com/pentaho/pentaho-commons-gwt-modules/pull/712
=> Revert "[BISERVER-14087] Localized file/folder names are not shown in the Save As window"

extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSPluginServlet.java, extensions/src/test/java/org/pentaho/platform/web/servlet/JAXRSPluginServletTest.java
JAX-RS Response return objects do not trigger the "error state" in the HttpServletResponse. Forcing all HTTP Error Status into "sendError" enables the configuration of custom error pages in web.xml.
=> [CDE-896] - Map Http Error Status into HttpServletResponse Error

assemblies/pentaho-war/pom.xml
=> [BACKLOG-27567] Fixes missing org.osgi.compendium-4.3.1.jar in the webapp assembly

assemblies/pentaho-war/pom.xml
Merge after https://github.com/pentaho/maven-parent-poms/pull/105.
@graimundo please review.
=> [BACKLOG-27567] Remove org.osgi.core version override

assemblies/pentaho-war/pom.xml, extensions/pom.xml, pom.xml
@graimundo and @Pancho7 please review.
Note that this targets pentaho:karaf_update, so wingman will not run. Our build pipeline will, when all related PRs are merged.
Needs [pentaho/maven-parent-poms#107](https://github.com/pentaho/maven-parent-poms/pull/107).
=> [BACKLOG-27577] Centralize karaf dependencies management

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp
- Remove the 'locale' definition from 'bounceToReturnLocation()' so that it aways defaults to the browser's locale
- Remove the 'locale' value assignment from the input form (as hidden value), since it was only used n the 'bounceToReturnLocation()' function
=> [BISERVER-14220] Remove the 'locale' definition from 'bounceToReturnLocation()' 

extensions/src/main/java/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepository.java, extensions/src/test/java/org/pentaho/platform/osgi/KarafInstanceTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryTest.java
Code was assuming the file type could be determined from the extension,
but at some point the filename was made into a uuid.
This change retrieves locale files and info explicitly using
PentahoMetadataInformationMap.getLocaleFiles rather than using naming.
https://jira.pentaho.com/browse/BISERVER-14265
=> [BISERVER-14265]  Exporting XMI fails when localization files present.

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PRPTImportHandler.java
@pentaho/rogueone 
https://jira.pentaho.com/browse/BISERVER-14231
Before this PR, the visibility of imported PRPTs in the repository was based on the `visible` attribute in the PRPT's metadata. This PR changes the `PRPTImportHandler` to leave this to the `RepositoryFileImportFileHandler` which pull from `ImportHandlerMimeTypeDefinitions.xml` instead.
=> [BISERVER-14231] Change PRPTImportHandler to respect ImportHandlerMimeTypeDefinitions.xml

pom.xml
aws-java-sdk-core depends on a later version, so bringing this to the latest
=> [BACKLOG-27345] - upgrading joda-time

extensions/src/main/java/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepository.java
Broken with the fix for BISERVER-14265, with this change:
https://github.com/pentaho/pentaho-platform/pull/4454/files#diff-032e7ddd40c89218e2561a2f06684ed0R426
That made the domain map immutable, but downstream logic expects to be able to add to the same map.
Making the map mutable again.
https://jira.pentaho.com/browse/BACKLOG-29432
=> [BACKLOG-29432] DSW model export fails

core/src/main/java/org/pentaho/platform/util/web/MimeHelper.java, core/src/test/java/org/pentaho/platform/util/web/MimeHelperTest.java
@pentaho/tatooine @wseyler @pentaho-lmartins 
* [PRD-6031] Modifying MimeHelper to create public references so that we can use those references in other projects (pentaho-platform-plugin-reporting, where we decide to use attachment or inline for Content-Disposition depending on what mime-type is used).
* [PRD-6031] Create test to validate the references and verify the static methods behave appropriately.
This Pull Request is depended on by the following PR:
https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/714
=> [PRD-6031] Exporting a report in Excel via IE gives the filename as "content" instead of giving the prpt's name as filename

extensions/src/main/java/org/pentaho/platform/web/WebUtil.java, extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilter.java, extensions/src/test/java/org/pentaho/platform/web/WebUtilTest.java, extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilterTest.java
- Added extra CORS headers configurations (**Access-Control-Expose-Headers**), to make Csrf's service independent of users own CORS configuration.
=> [BACKLOG-29696] CSRF Marketo Use Case

assemblies/pentaho-server/pom.xml
Reverts pentaho/pentaho-platform#4505
@RPAraujo @pentaho-lmartins
=> Revert "[SP-5178] Backport of PPP-4372 - Not possible to use '[' and ']' on r…"

user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
@pentaho/tatooine @dcleao @pentaho-lmartins 
* [ANALYZER-3802] Issue lived in the Mantle Tab Panel, fix was to ensure that when purging a tab, we make sure that under certain circumstances, we shouldn't send null resource. This allows a fix for the ticket by giving an about:blank, rather than a null resource (which was what was being triggered when cancel was clicked). So with the null not being sent, the service doesn't try and run and run into an error.
=> [ANALYZER-3802] Error pressing Cancel in Select Data Source window when creating a new PAZ

user-console/pom.xml, user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/tabs/IFrameTabPanel.java, user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTab.java, user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
* Tab poling would leak global frame variables and yet bring no observable improvements.
* Fix memory leaks in `IFrameWatcher` code.
Merge after:
* https://github.com/pentaho/pentaho-commons-gwt-modules/pull/731
* https://github.com/pentaho/pentaho-analyzer/pull/1984
=> [BACKLOG-30195] Fixing memory leaks.

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java
@pentaho/tatooine @RPAraujo @ssamora 
* [BISERVER-14294] Updated code to check for available users and to make sure the acl owner has to exist, otherwise throw a bad response back.
=> [BISERVER-14294] "Browse File" crashes when changing the owner of a folder/file with "<script>alert(999)</script>"

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/mondrian/mondrian.properties
@mkambol @kurtwalker @lucboudreau  Hi Guys, I did my best to try to document this existing property from an admin point of view trying to tune their Mondrian query performance.  Please let me know if you have any suggestions or if anything is inaccurate.  Thanks
=> [MONDRIAN-1713] cellBatchSize should be included in mondrian.properties

assemblies/pentaho-war/pom.xml, extensions/pom.xml, pom.xml
This is part of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/170 for details.
**Don't merge before the PR above.**
With the exclusions in `pentaho-metadata` we no longer need to explicitly declare dependencies for `xstream`, it will be included as a transitive and the `pentaho-war` assemply will include it.
=> [PPP-4448] Use of Vulnerable Component - XStream 1.4.10

assemblies/pentaho-war/pom.xml, extensions/pom.xml, pom.xml, repository/pom.xml
Replaces #4569. Changes to `pentaho-war` will produce a war file with all artifacts.
**Do not merge before https://github.com/pentaho/maven-parent-poms/pull/178!**
@ssamora @RPAraujo
=> [PPP-4447] Use of vulnerable component - Tika Core 1.1x

core/src/main/java/org/pentaho/platform/util/Emailer.java
Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Pentaho/pentaho-platform/commit/a0162bc0d36b96ec26fb45aa2fd0e03ac7b14c92
=> [SP-5361] Backport of BISERVER-14364 - Email Attachments with long non-ascii filenames are garbled when report is scheduled (8.3 Suite)

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/sejcr/GuavaCachePoolPentahoJcrSessionFactory.java, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/sejcr/PentahoJcrTemplate.java, repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/sejcr/PentahoJcrTemplateTest.java
Cause of the issue was identified as a gradually increasing number of orphaned
JCR sessions.  This occurred because our caching strategy would skip logout
for certain sessions to allow them to be reused, but never did a logout
on eviction from the cache.
This change logs out on eviction when a session has no active use.  In general
at the time of eviction _all_ sessions should be ready for logout, given 5 minutes
of inactivity, but if cache settings are more restrictive, or if activity is
very high, this will prevent killing an in-use session.
https://jira.pentaho.com/browse/BISERVER-14398
=> [BISERVER-14398] Pen server Perf Degradation when importing objects

extensions/pom.xml, pom.xml, repository/pom.xml, repository/src/main/java/org/pentaho/platform/repository/solution/filebased/MondrianVfs.java
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Removing version reference, maven parent pom will control version.
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/102
- https://github.com/pentaho/pdi-plugins-ee/pull/139
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/82
- …
=> [PDI-17775] Process Files step no longer supports HTTP scheme

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/sejcr/GuavaCachePoolPentahoJcrSessionFactory.java, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/sejcr/PentahoJcrTemplate.java, repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/sejcr/PentahoJcrTemplateTest.java
Cause of the issue was identified as a gradually increasing number of orphaned
JCR sessions. This occurred because our caching strategy would skip logout
for certain sessions to allow them to be reused, but never did a logout
on eviction from the cache.
This change logs out on eviction when a session has no active use. In general
at the time of eviction all sessions should be ready for logout, given 5 minutes
of inactivity, but if cache settings are more restrictive, or if activity is
very high, this will prevent killing an in-use session.
https://jira.pentaho.com/browse/BISERVER-14398
=> [SP-5367] Pen server Perf Degradation when importing objects

assemblies/pentaho-war/pom.xml
* [PPP-4496] Upgrading to version 0.10.2.2
* [PPP-4496] Removing version reference, maven-parent-pom will control version info.
This is from a series of Pull Requests:
- https://github.com/pentaho/maven-parent-poms/pull/218
- https://github.com/pentaho/big-data-plugin/pull/2032
- https://github.com/pentaho/pdi-plugins-ee/pull/168
- https://github.com/pentaho/pentaho-platform/pull/4649
- https://github.com/pentaho/pentaho-reporting/pull/1327
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/152
- https://github.com/pentaho/pentaho-metadata-editor/pull/190
- https://github.com/pentaho/pentaho-metadata-editor-ee/pull/85
- https://github.com/pentaho/pentaho-kettle/pull/7309
- https://github.com/pentaho/pentaho-big-data-ee/pull/441
=> [PPP-4496] Use of Vulnerable Component: Components/kafka

extensions/src/main/java/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/DatabaseConnectionConverter.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseConnection.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseType.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestDto.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/MapExport.java, extensions/src/test/java/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/DatabaseConnectionConverterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ExporterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseTypeTest.java
Original PRs:
- [#4620](https://github.com/pentaho/pentaho-platform/pull/4620)
- [#4648](https://github.com/pentaho/pentaho-platform/pull/4648)
Don't forget to squash the commits.
@pentaho-lmartins @ssamora @ppatricio @bcostahitachivantara
=> [SP-5446] Backport of BISERVER-14353 - Database Connection's Password is exposed in clear text in exportManifest.xml (8.3 Suite)

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties
- Made logImportResponseMessage global -> now called logResponseMessage
- Add a hasEntity validation before printing Entity (prevent empty prints on log)
- Restore now uses the new logResponseMessage method.
@pentaho-lmartins @ssamora
=> [BISERVER-14419] Repository Restore not logging as expected

extensions/src/main/java/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporter.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/DatabaseConnectionConverter.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseConnection.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseType.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestDto.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/MapExport.java, extensions/src/test/java/org/pentaho/platform/plugin/services/exporter/PentahoPlatformExporterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/DatabaseConnectionConverterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ExporterTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseTypeTest.java
Original PRs:
- [#4620](https://github.com/pentaho/pentaho-platform/pull/4620)
- [#4648](https://github.com/pentaho/pentaho-platform/pull/4648)
Don't forget to squash the commits.
@pentaho-lmartins @ssamora @ppatricio
=> [SP-5447] Backport of BISERVER-14353 - Database Connection's Password is exposed in clear text in exportManifest.xml (9.0 Suite)

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ldap.xml, assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/ehcache.xml, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticator.java, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulator.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticatorTest.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulatorTest.java
[BISERVER-14418] Add a caching LDAP authenticator to reduce traffic against an LDAP server when running frequent spoon/pan/kitchen jobs against the repo. Keeps the default behavior as the original non-caching authenticator, allowing the customer to enable as desired
=> [BISERVER-14418]

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ldap.xml, assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/ehcache.xml, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticator.java, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulator.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticatorTest.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulatorTest.java
against an LDAP server when running frequent spoon/pan/kitchen jobs
against the repo.  Keeps the default behavior as the original
non-caching authenticator, allowing the customer to enable as desired.
=> [SP-5768] Add a caching LDAP authenticator to reduce traffic

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ldap.xml, assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/ehcache.xml, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticator.java, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulator.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthenticatorTest.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/PentahoCachingLdapAuthoritiesPopulatorTest.java
against an LDAP server when running frequent spoon/pan/kitchen jobs
against the repo.  Keeps the default behavior as the original
non-caching authenticator, allowing the customer to enable as desired.
This commit is a cherry-pick from master 89902fa4
=> [SP-5767] Add a caching LDAP authenticator to reduce traffic

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j.xml, core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java, extensions/src/main/java/org/pentaho/platform/web/servlet/PluginDispatchServlet.java
@bennychow please review
/cc @jcarneirohv
- CDA uses the websocket feature of the pentaho platform but requires extra information to be injected into the websocket's ServerEndpointConfig to be able to replicate the Pentaho session and request context on the websocket session side. This information is required to properly log and audit the data access.l
=> [BISERVER-5014] Adding new log4j category and extra information to web socket configurations

user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java
@ssamora 
@smmribeiro 
I did not write more unit test because GWT always mock internal packages so was impossible to test a result of JSONArray created inside the method for instance.
=> [BISERVER-14291] - Append Timestamp to generated content option does not work on reports with no parameters

core/src/main/java/org/pentaho/platform/util/messages/LocaleHelper.java, core/src/test/java/org/pentaho/test/platform/engine/core/BaseTestCase.java, extensions/src/it/java/org/pentaho/test/platform/web/ProxyServletIT.java, extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java, extensions/src/main/java/org/pentaho/platform/web/http/filters/ProxyTrustingFilter.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ProxyServlet.java, extensions/src/main/resources/org/pentaho/platform/web/servlet/messages/messages.properties, extensions/src/test/java/org/pentaho/platform/web/http/filters/ProxyTrustingFilterTest.java, user-console/src/main/resources/org/pentaho/mantle/public/Mantle.jsp, user-console/src/main/resources/org/pentaho/mantle/public/MantleDebug.jsp
- `ProxyServlet`, `ProxyTrustingFilter` - send and receive the new `_TRUST_LOCALE_OVERRIDE_` argument
- `LocaleHelper.parseAndSetLocaleOverride` now accepts `null` or empty, simplifying some use cases
- `Mantle.jsp`, `MantleDebug.jsp`, `HttpSessionPentahoSessionIntegrationFilter` - simplified to use the new interface of `LocaleHelper.parseAndSetLocaleOverride`
These changes allow CGG to request localized resources, via the `/i18n` service (the address of the platform's `LocalizationServlet`). The `/i18n` address is configured to allow being proxied/fetched from _localhost_ ([web.xml configuration of localhost](https://github.com/pentaho/pentaho-platform/blob/master/assemblies/pentaho-war/src/main/webapp/WEB-INF/web.xml#L86-L88) and [web.xml configuration of …
=> [ANALYZER-3942] Add ability to set the locale via ProxyTrustingFilter

extensions/pom.xml, extensions/src/main/java/org/pentaho/platform/web/http/request/MultiReadHttpServletRequest.java, extensions/src/main/java/org/pentaho/platform/web/http/security/RequestParameterAuthenticationFilter.java, extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSPluginServlet.java, extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSServlet.java, extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileServlet.java
- Removed `@MultipartConfig` annotations which revealed unnecessary for the final `MultiReadHttpServletRequestWrapper` implementation.
- Deprecated the existing `MultiReadHttpServletRequest` class in favor of the improved `MultiReadHttpServletRequestWrapper`
- `RequestParameterAuthenticationFilter` now uses `MultiReadHttpServletRequestWrapper`, which integrates better with `CsrfGateFilter`, as a multi-read wrapper is only used if there isn't one already in the request wrapper chain. This also makes the filter more standard in that it will allow downstream use of the new `HttpServletRequest` `getPart` and `getParts` methods.
Very indirectly related with recent story: https://jira.pentaho.com/browse/BISERVER-14701.
Depends on: 
- https://github.com/pentaho/security-web/pull/11
- …
=> [BACKLOG-35298] Fix requestParameterAuthenticationEnabled due to CSRF changes

extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileServlet.java
This annotation is required to be able to use the `Request#getPart` API. It would work when CSRF was enabled, because, then, the request would be an instance of the `MultiReadHttpServletRequestWrapper` which does not have this requirement.
@bennychow please review and merge.
=> [BACKLOG-35436] Not able to create a Data Source from CSV File using Wizard

assemblies/pentaho-war/pom.xml, pom.xml
Remove old log4j version references that exist on the 8.3 branch.
@smaring @rmansoor
=> [SP-6106] backport of BISERVER-14720 - Upgrade log4j2

api/src/main/java/org/pentaho/platform/api/util/LogUtil.java
appenders bridging them to the kettle log system to avoid mixing log
messages from separate processes together.
=> [BACKLOG-35556] Ensure logs from sqoop jobs get their own

api/src/main/java/org/pentaho/platform/api/util/LogUtil.java
appenders bridging them to the kettle log system to avoid mixing log
messages from separate processes together.
This commit is a cherry-pick from master 6bdb815a65
=> [SP-6107] [BACKLOG-35556] Ensure logs from sqoop jobs get their own

api/src/main/java/org/pentaho/platform/api/util/LogUtil.java
appenders bridging them to the kettle log system to avoid mixing log
messages from separate processes together.
This commit is a cherry-pick from master 6bdb815a65
=> [SP-6106] [BACKLOG-35556] Ensure logs from sqoop jobs get their own

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoServices.spring.xml, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/system.properties
- `AggregatedRequestSetCsrfConfiguration` -> `AggregatedCsrfConfiguration`
- `CsrfRequestSetConfiguration` -> `PartialCsrfConfiguration`
- Using the new `DefaultCsrfProcessor` class
- Using the new `DefaultCsrfHelper` class
- Switched the order of CSRF and CORS filters; CORS filter first.
- Removed CSRF filter from the CSRF token service endpoint
Please see main PR: https://github.com/pentaho/maven-parent-poms/pull/336.
=> [BACKLOG-35003] Change security-web to latest version

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledOrJndiDatasourceService.java, core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledOrJndiDatasourceService.java, core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicConnectionDatasourceServiceTest.java
@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5073/
=> [SP-6148] - Backport of BISERVER-14682 - Database connections from different pools mixed up when using SQL Server (8.3 Suite)

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/kettle-registry-extensions.xml
provided by kettle plugins available to other plugins.
=> [BACKLOG-36137] ServicePluginLoader required in order to make services

assemblies/pentaho-server/pom.xml, assemblies/pentaho-server/src/assembly/assembly.xml, pom.xml, tomcat-logs/pom.xml, tomcat-logs/src/main/java/org/pentaho/tomcat/logvalve/FilteredAccessLogValve.java
Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster
(cherry picked from commit 65147a695e3135277bd5859c970ce3324bdd4ac2)
=> [SP-6181][PDI-18988]:Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

user-console/src/main/java/org/pentaho/mantle/client/dialogs/FileDialog.java
@pentaho/wcag please review.
Part of PR group: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/839.
=> [BACKLOG-37004] Change FileDialog to not duplicate GlassPane management with FileChooserDialog

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.js
@pentaho/wcag, please, review.
=> [BACKLOG-37034] Fixed restore focus on ESC key for Rename dialogs

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
@pentaho/wcag, please review and merge, asap.
Regression caused by https://github.com/pentaho/pentaho-commons-gwt-modules/pull/881 et al.
The regression caused the Schedule perspective to show no scrollbars.
Also, the Administration perspective to only show the vertical scrollbar, albeit remaining scrollable with the scroll wheel...
=> [BACKLOG-37325] FIX scrollbars for Schedule and Administration perspectives

core/src/test/java/org/pentaho/platform/util/versionchecker/PentahoVersionCheckReflectHelperTest.java
Cherry-pick changes from BACKLOG-38038 that solve this issue PentahoVersionCheckReflectHelperTest.performVersionCheckTest()
=> Fixing unit tests 9.5

core/src/test/java/org/pentaho/platform/util/versionchecker/PentahoVersionCheckReflectHelperTest.java
Cherry-pick changes from BACKLOG-38038 that solve this issue PentahoVersionCheckReflectHelperTest.performVersionCheckTest()
=> Fixing unit tests 9.3

user-console/src/main/resources/org/pentaho/mantle/public/Mantle.jsp, user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
@pentaho/wcag , Please Review.
toolbars using `display:contents` made it difficult to navigate toolbar using keyboard. This PR fixes that.
=> [BACKLOG-37966] Toolbar improvements in PUC

assemblies/pentaho-solutions/pom.xml
included in the "pentaho-solution/system" folder
=> BACKLOG-38036 - Fixed assembly so that "scheduler-plugin" will be

api/src/main/java/org/pentaho/platform/api/ui/Theme.java, assemblies/pentaho-war/src/main/webapp/js/themeResources.js, extensions/src/main/java/org/pentaho/platform/web/html/themes/PluginThemeResolver.java, extensions/src/main/java/org/pentaho/platform/web/servlet/ThemeServlet.java
- Responsive themes will have CSS class `responsive-theme` be added to the html element
- Allows responsive primitives' CSS rules to be shared across themes and between the `responsive` and the new `responsive-content` CSS classes
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/41
=> [BACKLOG-37873][BACKLOG-38655] Added ability for a theme to indicate it is responsive

scheduler/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java, scheduler/src/main/java/org/pentaho/platform/scheduler2/ws/ISchedulerService.java
Added the method to obtain permissions from the server, and permission validation to the execution methods.
@smmribeiro 
@renato-s
=> [PDI-19868] - Schedule perspective for the Administrator Role is different between PUC and PDI

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
Two commits on this PR: the first is the actual fix for this issue's problem; the second is a refactoring of the class to fix some sonar issues and some architectural problems found during the test and development of the first.
@bcostahitachivantara @renato-s @andreramos89
=> [BISERVER-14935] import-export.bat/.sh does not work on Pentaho 9.3 or higher if requestParameterAuthenticationEnabled=true

user-console/src/main/resources/org/pentaho/mantle/public/MantleStyle.css, user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
- Move display:none on #pucTabsMenuBar to MantleStyle.css, so that it is hidden for all themes by default instead of just ruby
=> [BACKLOG-39182] Ensure TabsMenu does not show up in themes other than Ruby

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml, assemblies/pentaho-war/src/main/webapp/WEB-INF/web.xml, extensions/src/main/java/org/pentaho/platform/web/servlet/PentahoPluginWSSpringServlet.java
endpoints in plugins. Endpoints must be defined in a plugin.ws.spring.xml file within the plugin, endpoint path must be of the form webservices/plugins/<plugin-id>/<endpoint>.  Updated filter to handle relocating scheduler web service endpoint.
=> [BACKLOG-39324] Created PentahoPluginWSSpringServlet to handle jaxws

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/AbstractSpringPentahoObjectFactory.java, core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/SpringPentahoObjectReference.java, extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSPluginServlet.java
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/68
For each Pentaho plugin the [`PentahoSystemPluginManager`](https://github.com/pentaho/pentaho-platform/blob/21bd70d66c1575c6a9746ee6cfe0ec06b5115e81/extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/PentahoSystemPluginManager.java#L291C24-L291C24) creates a Spring application context for it, and a corresponding`StandaloneSpringPentahoObjectFactory`, which kind of manages the Spring context. The plugin manager [initializes the object facory](https://github.com/pentaho/pentaho-platform/blob/21bd70d66c1575c6a9746ee6cfe0ec06b5115e81/core/src/main/java/org/pentaho/platform/engine/core/system/objfac/StandaloneSpringPentahoObjectFactory.java#L63). 
When initialized, the object factory installs …
=> [BACKLOG-37872] Fixed session scope for Pentaho plugin spring beans used from jax-rs api

api/src/main/java/javax/ws/rs/core/NoContentException.java
[BACKLOG-39494]-javax.ws.rs.WebApplicationException: com.sun.jersey.api.MessageException
[BACKLOG-39494]: https://hv-eng.atlassian.net/browse/BACKLOG-39494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-39494]-javax.ws.rs.WebApplicationException: com.sun.jersey.api.MessageException

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/SolutionBrowserPanel.java, user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java, user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
To be merged with https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1019
- Fix tab-width when Solution Browser is present
- Ensure fix works when SolutionBrowser isn't present and hasn't loaded
- Add setElementWidth helper method in CssUtils to bypass restrictions on GWT style helper methods
The only way I could figure out how to get a horizontal scroll is by setting a width value in `.css` file or in-line `style` attribute.
GWT style helper methods do not like units that aren't px, so, I created a helper method in lieu of rewrapping GWT classes down to Style
=> [BACKLOG-39648] Dashboard interface is cropped on the right side

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-jdbc.properties, assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-jdbc.xml
org.pentaho.di.core.database.util.DecryptingDataSource to match org.apache.commons.dbcp2.BasicDataSource after dbcp2 library update.
=> [BACKLOG-39797] Updating properties of

pom.xml
[BACKLOG-39454]- Lots of errors coming up on logs when server 10.1 is configured to use Java 8. Updating JBoss-Logging jar.
[BACKLOG-39454]: https://hv-eng.atlassian.net/browse/BACKLOG-39454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-39454]- Lots of errors coming up on logs when server 10.1 is configured to use Java 8. Updating JBoss-Logging jar.

user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
- provide temporary workaround so that opened, deep-linked reports will render in new tabs
- this breaks burger tabs menu in that this first tab will not be accessible in burger mode
=> [BACKLOG-39812] PIR report doesnt render in New Window or Via Deeplink

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
=> Addresses BACKLOG-39950: fix zoom after 400% hides content

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java
DTDs to prevent XXE attacks oon FileResource endpoint. The better solution would involve configuring secure XML parsing across the entire application, but our framework does not allow that easily and it would require more rework and testing than currently feasible.
=> [PPP-5021] Use a secure SAX parser which forbids external entities and

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryResource.java
Adding validation to allowed formats for PRPTI files, according to documentation: 
https://help.hitachivantara.com/Documentation/Pentaho/Data_Integration_and_Analytics/9.5/Developer_center/Embed_Pentaho_Server_functionality_into_web_applications#Execute_a_report_from_a_HTML_form_(POSTing.0D.0A____parameters)
@smmribeiro 
@renato-s
=> [BISERVER-15031] - Limit the PIR Export via REST API to the allowed types

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryResource.java
Null protection was missing from the validation
@smmribeiro 
@renato-s
=> [BISERVER-15031] - Limit the PIR Export via REST API to the allowed types - null protection missing

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryResource.java
Removed options to download .xls files
=> [BISERVER-14864] - Empty file when downloading PIR to Excel 97-2003 format once data is past Excel limitations

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml, extensions/src/it/resources/repository.spring.xml, extensions/src/test/resources/repository.spring.xml, extensions/src/test/resources/solution1-no-config/system/repository.spring.xml, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/SchedulerExecuteAction.java, repository/src/main/resources/org/pentaho/platform/security/policy/rolebased/messages/messages.properties, repository/src/main/resources/org/pentaho/platform/security/userroledao/messages/messages.properties, repository/src/main/resources/repository.spring.xml
=> Addresses BACKLOG-40066: New schedule execution permission

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.fileButtons.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.folderButtons.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
Issue: https://hv-eng.atlassian.net/browse/BACKLOG-40086
Depends on:
- https://github.com/pentaho/pentaho-scheduler-plugin/pull/145
To also be merged with:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/191
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1028
--
- Maintain repository folder/file actions and disable all for VFS Connections for now
- Utilize scheduler-plugin api for REST calls
- Refactor FileBrowserFolderTreeModel.fetchData to fetchTreeRootData as it is only ever used for fetching the root tree and associated scheduler-plugin/api endpoint
- Refactor FileBrowserFileListModel.reformatResponse, customSort, the trash folder, and browser.templates to match the response objects returned by scheduler-plugin/api endpoints
- Ensure hyperlinked folder …
=> [BACKLOG-40086] Schedule Output Perspective : Allow user to browse Scheduled contents from a VFS location folder

core/src/main/java/org/pentaho/platform/engine/services/solution/SimpleContentGenerator.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/GeneratorStreamingOutput.java, extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResource.java, extensions/src/test/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java, extensions/src/test/java/org/pentaho/platform/plugin/services/webservices/content/AxisServiceExecutorTest.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceTest.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/webservices/AxisServiceWsdlGeneratorTest.java, extensions/src/test/java/org/pentaho/test/platform/plugin/services/webservices/WsdlPageTest.java, user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
Original PR:
- https://github.com/pentaho/pentaho-scheduler-plugin/pull/138/
- https://github.com/pentaho/pentaho-platform/pull/5559
=> [SP-6512] - Backport of PPP-5053 - Intercepting few Get request with Burp Suite allows un-authorised user to access data (9.3 Suite)

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.multiSelectButtons.js
[BACKLOG-40086] Schedule Output Perspective : Allow user to browse Scheduled contents from a VFS location folder
Follow up sub-task:
[BACKLOG-40485] Disable file action buttons for multi-select, and disable double-click to "open" for VFS Connections
- These blocks/code will be modified in BACKLOG-40475 wherein we investigate enabling "open" for VFS Connection files
[BACKLOG-40486] Investigate ctrl+click in VFS Connection Files (cannot ctrl+click to add >1 to selection, only remove)
- Add `id` to file elements in cases wher `objectId` is missing in response object, use `path` instead
[BACKLOG-40086]: https://hv-eng.atlassian.net/browse/BACKLOG-40086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BACKLOG-40485]: …
=> [BACKLOG-40086] Testing feedback subtasks [BACKLOG-40485][BACKLOG-40486]

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
- Encoded `expandedPath` param
- Escape special characters (in paths) in jquery css selectors
PR Set:
1. https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1034
2. https://github.com/pentaho/pentaho-platform/pull/5593
3. https://github.com/pentaho/pentaho-scheduler-plugin/pull/169
=> [BACKLOG-40489] Error when accessing browse files with a user with special characters

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelper.java, repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelperTest.java
Change in the way the thrashed files are being returned to the PUC UI. Now all files should be visible for admin users.
@smmribeiro 
@befc 
@renato-s 
@joana-fb 
@miguelappleton
=> [BISERVER-14948] - Using LDAP authentication, Admin user is not able to view, identify and hence empty the non-admin user’s trash.

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
[BISERVER-15027] MySQL8 database repository for pentaho server does not work properly with mysql8 jar
[BISERVER-15027]: https://hv-eng.atlassian.net/browse/BISERVER-15027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BISERVER-15027] MySQL8 database repository for pentaho server does not work properly with mysql8 jar

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
Refactored the code according to the suggestion made in the [ticket's description](https://hv-eng.atlassian.net/browse/PPP-5105) by @dcleao. This will effectively correct the performance issue with the previous implementation by using the regex without wildcards and make usage of the `find()` method, that performs a lot better than `matches()`.
The target code is being covered by `FileResourceTest.validateSecurityPrincipal()`, from my evaluation, no further UTs seem to be necessary with this change.
Conducted some benchmark tests with JMH to better understand the impact and improvements with this change for both valid and invalid strings, before and after refactor:
Short strings (~10 char.):
```
Benchmark                                                       Mode  Cnt    Score    Error …
```
=> [PPP-5105] Denial Of Service when changing file ACLs

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
=> [BACKLOG-40443] - Closing a folder's "Properties..." dialog via "OK" in Browse Perspective returns focus to the folder's parent

user-console/pom.xml, user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/SolutionBrowserPanel.java, user-console/src/main/resources-filtered/org/pentaho/mantle/public/browser/index.jsp, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.fileButtons.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.folderButtons.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.multiSelectButtons.js
PR Set:
1. https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1039
2. https://github.com/pentaho/pentaho-platform/pull/5616
3. https://github.com/pentaho/pentaho-scheduler-plugin/pull/178
4. https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/243
`SolutionBrowserPanel`:
- added spotbugs dependency so that we can use GenericFileNameUtils
- in this effort we will be supporting the following extensions for PVFS file "Open" actions
-- `supportedGenericFileExtensions = Arrays.asList( "html", "pdf", "txt", "rtf", "xlsx" );`
-- helper function to check if a fileName has an acceptable extension
- created general error dialog function to support existing plugin missing error along with new unsupported file type/extension error
-- made these functions accessible to other js files, …
=> [BACKLOG-40475] Browse Perspective: "Open" PVFS file actions

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml, repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelper.java, repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelperTest.java
Added the property `adminAccessAllUsersTrash` to the `pentaho.xml` configuration file, by default it will keep the current behaviour of showing all user thrash to admin users, if disabled trash items of other users will not be shown to admins.
Should be merged together with: https://github.com/pentaho/pentaho-platform-ee/pull/1764
=> [BISERVER-15067] Add toggle property to enable/disable admin access to other users trash

user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
- Disable all Folder Actions for root folders "Repository" and "VFS Connections"
- Hide icons for root folders, to communicate to users that they shouldn't be considered standard folders
- Fix title == null conditional. This should have originally been handled in browser.js reformatResponse and not done in the template.
=> [BACKLOG-41134] [BACKLOG-40475] Disable Folder Actions under Repository

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js, user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
Start using IGenericFile#getNameDecoded() for purposes of UI display
PR Set:
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1042
https://github.com/pentaho/pentaho-platform/pull/5652
https://github.com/pentaho/pentaho-scheduler-plugin/pull/187
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/256
=> [BACKLOG-41091] Use Decoded File Name and Title Values in Scheduler Perspective + Browse Perspective missed case

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
Issues: [BACKLOG-41394](https://hv-eng.atlassian.net/issues/BACKLOG-41394) and [BACKLOG-41395](https://hv-eng.atlassian.net/issues/BACKLOG-41395)
Regression caused by [BACKLOG-41091](https://hv-eng.atlassian.net/issues/BACKLOG-41091), https://github.com/pentaho/pentaho-platform/pull/5652
The lack of the `nameDecoded` property in the Trash folder and contained files/folders data structures was causing an error evaluating the folder/file templates.
/cc @pentaho/hoth 
[BACKLOG-41394]: https://hv-eng.atlassian.net/browse/BACKLOG-41394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BACKLOG-41395]: https://hv-eng.atlassian.net/browse/BACKLOG-41395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> [BACKLOG-41394][BACKLOG-41395] Trash folder is always empty

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml, assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
- Added documentation about the existing system setting `default-scheduler-output-path` to `pentaho.xml`
- Changed default log4j configuration to log WARN entries generated by `resources/SchedulerOutputPathResolver` and `action/SchedulerOutputPathResolver` classes
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin/pull/189.
Issue: https://hv-eng.atlassian.net/browse/BACKLOG-41349
=> [BACKLOG-41349] Improve logging for schedule output location fallback

extensions/src/main/java/org/pentaho/platform/osgi/KarafBoot.java, extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java
from booting at the same time, which may lead to config file corruption or instances starting without a proper karaf environment.
=> [PDI-20086] Implement a file lock to prevent multiple karaf instances

extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java
- changing the pid for a stale process to -1, instead of 0 to work with all systems
**suggested fix**, set stale/unused pid to `-1`, since it is a valid PID for an invalid process for windows and *nix:
- https://devblogs.microsoft.com/oldnewthing/20040223-00/?p=40503
- https://www.linfo.org/pid.html#:~:text=A%20PID%20(i.e.%2C%20process%20identification,always%20a%20non%2Dnegative%20integer.
**Backstory:**
On my local M2 Chip Mac, I was having the unit test `KarafBootTest#verifyStaleLockBehavior` fail, the process id (pid) `0` was actually being used
When I set it to really high number pid `999999..`. that isn't used, the test pass:
When I set the pid to `-1`, the test pass:
=> [CLEANUP] fixing failing test KarafBootTest#verifyStaleLockBehavior

assemblies/pentaho-solutions/pom.xml
PR Set for https://hv-eng.atlassian.net/browse/PPP-4582:
- https://github.com/pentaho/pdi-plugins-ee/pull/1290
- https://github.com/pentaho/pentaho-platform/pull/5676
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1452
Remove unused plugins with vulnerabilities from assembly:
- pentaho-googledrive-vfs
- pdi-google-analytics-plugin
=> [PPP-4582] Use of Vulnerable Component: Components/oauth_client_library_for_java

core/src/main/java/org/pentaho/commons/util/encoding/Decoder.java, extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ldap/DefaultLdapAuthenticationProvider.java, extensions/src/test/java/org/pentaho/platform/plugin/services/security/userrole/ldap/DefaultLdapAuthenticationProviderTest.java, repository/src/main/java/org/pentaho/platform/repository2/userroledao/jackrabbit/security/DefaultPentahoPasswordEncoder.java
As part of BISERVER-14644, it was missing to decode the passwords for LDAP authentication in the server. This PR reuses the method done in the previous issue (with some slight improvements) to also apply the same decodification on LDAP authentication.
@pentaho/tatooine_dev please review
=> [PDI-20206] Add base64/url decoding for passwords in LDAP authenticator

assemblies/pentaho-solutions/pom.xml
BACKPORT of:
[PPP-4582] Use of Vulnerable Component: Components/oauth_client_library_for_java
Remove unused plugins with vulnerabilities from assembly:
- pentaho-googledrive-vfs
- pdi-google-analytics-plugin
[PPP-4582]: https://hv-eng.atlassian.net/browse/PPP-4582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Backport of PPP-4582 - Use of Vulnerable Component: Components/oauth_client_library_for_java (10.2 Suite)

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
This PR makes the required frontend changes in order to address the new result of a query with `expandedPath` where it will have its children return with the same `maxDepth`: https://github.com/pentaho/pentaho-scheduler-plugin/pull/216
=> feat: add children with same depth to expanded path [BACKLOG-41878]

assemblies/pentaho-war/pom.xml
[BACKLOG-42817]-Upgrading fasterxml jaxrs to fasterxml jakarta rs to support with jersey 3.x and jakarta 3.x
[BACKLOG-42817]: https://hv-eng.atlassian.net/browse/BACKLOG-42817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42817]-Upgrading fasterxml jaxrs to fasterxml jakarta rs to support with jersey 3.x and jakarta 3.x

extensions/pom.xml
[BACKLOG-41287]-Upgrading pentaho-platform from Java-EE to Jakarta-EE to support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading pentaho-platform from Java-EE to Jakarta-EE to support with Tomcat-10.X

extensions/pom.xml, extensions/src/test/java/org/pentaho/platform/web/servlet/DefaultSpringWadlResourceDocumentTest.java, repository/pom.xml, user-console/pom.xml
[BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10
[BACKLOG-42885]: https://hv-eng.atlassian.net/browse/BACKLOG-42885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10

assemblies/pentaho-war/pom.xml, pom.xml, repository/pom.xml
- [PPP-4895] Update jettison version to 1.5.4
[PPP-4895]: https://hv-eng.atlassian.net/browse/PPP-4895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6635] Backport of PPP-4895 - Vulnerable Component: Jettison

core/src/main/java/org/pentaho/platform/engine/services/connection/PentahoConnectionFactory.java, core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java, extensions/src/main/java/org/pentaho/platform/plugin/services/connections/sql/SQLConnection.java, extensions/src/test/java/org/pentaho/platform/plugin/services/connections/sql/SQLConnectionTest.java
This PR needs to be merged together with https://github.com/pentaho/data-access/pull/1295
@pentaho/tatooine_dev please review
=> fix: Invalid database connection is saved AND used despite "CANCEL"

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/mimeType/MimeTypeListFactory.java, extensions/src/main/java/org/pentaho/platform/plugin/services/importer/mimeType/bindings/ImportHandlerMimeTypeDefinitionsDto.java
[BACKLOG-42169] - Changes for enabling plugin to register new file type extensions
[BACKLOG-42169]: https://hv-eng.atlassian.net/browse/BACKLOG-42169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42169] - Changes for enabling plugin to register new file type extensions

api/src/main/java/org/pentaho/platform/api/util/IPdiContentProvider.java
This reverts commit adbc4ad416cba0e06825bda6dc3c3cc39d8f8c22.
=> [BISERVER-15176] reverting the changes from BISERVER-15051 - Revert "[BISERVER-15051] hide internal variables PUC side" 

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp
=> [BISERVER-15135] - Username with prefix or suffix blank spaces on Login page triggers UsernameNotFound Exception, but session is created

assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.bat, assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.sh, assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.bat, assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.sh
java.time. Needed for Gson to handle java.time.LocalDate fields in the marketplace code.
=> [BACKLOG-43025] Update startup scripts to include add-opens for

core/src/main/java/org/pentaho/platform/engine/core/system/SystemSettings.java, core/src/main/resources/org/pentaho/platform/engine/core/messages/messages.properties, core/src/test/resources/org/pentaho/platform/engine/core/messages/messages.properties
This works around an issue where it may be possible to inject things into an XPath query used for retrieving system settings. We don't actually take user input in this scenarios, but its possible we accidentally could introduce something like that in the future. It is also possible for third party code to use this in an unsafe way.
We can't use variables, which would be the more typical approach here, because we need to allow `/` in the `settingName`. Instead we can check for potentially illegal characters and bail early.
=> [PPP-5594] handle potentially unsafe XPath queries

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java
=> fix: NPE when tree is null [BISERVER-15190]

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java
This pull request includes changes to the `FileService.java` file to improve the handling of null or empty collections. The most important changes include updating conditional checks to use the `isEmpty` method for better readability and consistency.
Improvements to null or empty collection handling:
* Updated the null or empty check for `tree.getChildren()` in the `doGetTree` method to use `isEmpty()` instead of checking the size.
* Added a new line to separate the block of code in the `doGetTree` method for better readability.
* Updated the null or empty check for `tree.getChildren()` in the `sortByLocaleTitle` method to use `isEmpty()` instead of checking the size.
* Updated the null or empty check for `repositoryFileDtoList` in the `sortByLocaleTitle` method to use `isEmpty()` instead …
=> fix: NPE when tree has no children [BISERVER-15190]

api/pom.xml, api/src/main/java/org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDto.java, api/src/main/java/org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileTreeDto.java
[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE

user-console/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

api/src/main/java/org/pentaho/platform/api/engine/ICacheManager.java, extensions/src/main/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/src/test/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
SME-849
This PR fixes the behavior that prevents that a catalog already load to the cache to be updated when used override as true. Currently, when a catalog is loaded to the cache is not possible to update it.
Main keys:
- init is always performed at add catalog, despite the configuration used.
- loadCatalogIntoCache when used with overwrite = true, complete the full function workflow, not returning immediatelly
=> fix: fix behavior that prevents that a catalog already load to the cache to be updated when used override as true [SME-849]

api/src/main/java/org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileAclAceDto.java
[BACKLOG-44113]-400 Bad Request Due to Unrecognized Field in ACL DTO Payload
[BACKLOG-44113]: https://hv-eng.atlassian.net/browse/BACKLOG-44113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44113]-400 Bad Request Due to Unrecognized Field in ACL DTO Payload

extensions/src/it/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperIT.java, extensions/src/main/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java, extensions/src/test/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java
[SME-1082]
- This PR fix the issues related with the execution of integration tests. Currently tests are not runnable as one method was renamed and they have broken scenarios.
- Minor fixes were also added to the main and unit test class files
- testAddCatalogWithException was removed as no longer applies after this PR https://github.com/pentaho/pentaho-platform/pull/5900
- [] Relevant tests have been added
[SME-1082]: https://hv-eng.atlassian.net/browse/SME-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: revise MondrianCatalogHelper integration tests [SME-1082]

api/src/main/java/org/pentaho/platform/api/engine/IAuthorizationAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/AbstractAuthorizationAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/AdministerSecurityAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/PublishAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/RepositoryCreateAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/RepositoryReadAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/SchedulerAction.java, repository/src/main/java/org/pentaho/platform/security/policy/rolebased/actions/SchedulerExecuteAction.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/AbstractAuthorizationActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/AdministerSecurityActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/PublishActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/RepositoryCreateActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/RepositoryReadActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/SchedulerActionTest.java, repository/src/test/java/org/pentaho/platform/security/policy/rolebased/actions/SchedulerExecuteActionTest.java
This pull request refactors the authorization action classes to improve code reuse and maintainability by introducing default methods for localization in the `IAuthorizationAction` interface and centralizing localization logic in the `AbstractAuthorizationAction` class. Additionally, redundant code in concrete action classes has been removed.
* Added default methods `getLocalizedDisplayName()` and `getLocalizedDescription()` to provide localized strings for the default locale, reducing the need for explicit implementations in subclasses.
* Refactored `AbstractAuthorizationAction` to include utility methods for parsing locales (`parseLocale`) and retrieving resource bundles (`getResourceBundle`). This centralizes and simplifies the handling of localization.
* Implemented the …
=> feat: add description property to authorization actions [PPUC-64]

api/src/main/java/org/pentaho/platform/scheduler2/recur/RecurrenceList.java
[BACKLOG-44147]-Schedule Job API fails schema validation due to missing @type and incorrect field types
[BACKLOG-44147]: https://hv-eng.atlassian.net/browse/BACKLOG-44147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44147]-Schedule Job API fails schema validation due to missing @type and incorrect field types

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java, extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java
- Extra Roles list would become polluted with all system roles, as many times as `getAllRoles()` was called
- Sorting for roles and users was only being applied to some of the operations
TODO:
/cc @pentaho/millenniumfalcon, please, review.
=> fix(UserRoleListService): list corruption and sorting [PPUC-123]

core/pom.xml, extensions/pom.xml
While these dependencies are marked as optional, vfs2 2.10.0 's default provider is Http5FileProvider that needs them
=> feat[PPP-5649]: add httpclient5 and httpcore5 dependencies

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml, extensions/src/main/java/org/pentaho/platform/web/http/security/Http401UnauthorizedEntryPoint.java, extensions/src/main/java/org/pentaho/platform/web/servlet/matchers/UserNavigationRequestMatcher.java, extensions/src/main/java/org/pentaho/platform/web/servlet/matchers/WebBrowserRequestMatcher.java, extensions/src/test/java/org/pentaho/platform/web/http/security/Http401UnauthorizedEntryPointTest.java, extensions/src/test/java/org/pentaho/platform/web/servlet/matchers/UserNavigationRequestMatcherTest.java, extensions/src/test/java/org/pentaho/platform/web/servlet/matchers/WebBrowserRequestMatcherTest.java
Issues: [PPUC-108](https://hv-eng.atlassian.net/browse/PPUC-108) (and [BISERVER-14841](https://github.com/pentaho/pentaho-platform-ee/pull/1852/commits/a68e67c65f1f85b712b9d47325ba5898f7a3a847))
To be merged with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1852
- https://github.com/pentaho/pentaho-analyzer/pull/2716
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/901
- https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1147
---
This pull request introduces significant changes to the security configuration in the Pentaho platform, focusing on improving authentication handling for web browser and non-browser clients. Key updates include replacing the `exceptionTranslationFilterForWS` with a unified `exceptionTranslationFilter`, …
=> feat: select User or API auth entry point based on Sec-Fetch-User request header [PPUC-108][BISERVER-14841]

extensions/src/it/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperIT.java
-
This PR fix the MondrianCatalogHelperIT tests that are breaking at compiling time
=> fix: fix integration tests that were failing

extensions/src/it/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperIT.java
Fix failing tests.
The majority of the tests was fixed by defining the mock for the `IUnifiedRepository` before instantiating the `MondrianCatalogHelper` class, that needs that dependency to be present in the system.
Also added mock for `IPasswordService`.
=> test: Fix MondrianCatalogHelperIT tests [SME-1164] 

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/DatabaseConnection.java
The root cause of the issue lies in the stricter enforcement introduced by the jakarta.xml.bind API.
Pentaho attempts to load all sample data source configurations as part of the default-content. These configurations, including JDBC resources, are defined within the exportManifest.xml files inside the default-content ZIP archives. While processing each ZIP file, the export XML content is unmarshalled into Java DTOs using JAXB.
The problem arises specifically due to the @XmlElement annotation on the databaseType field in DatabaseConnection.java. This annotation includes a schema URL reference. However, the corresponding databaseType element in the exportManifest.xml does not provide a matching schema URL. As a result, JAXB fails to bind the value correctly, setting databaseType to null. …
=> [BACKLOG-45029] - Missing Data Source SampleData of type JDBC

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java, extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties, user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordByUserDialog.java, user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java, user-console/src/main/java/org/pentaho/mantle/client/admin/UserDialog.java
This pull request updates the allowed password characters, expanding it to include the hyphen (`-`). It also improves error messaging by showing users which specific characters in their password are not permitted, rather than simply displaying the whole password. 
Additionally, the behaviour added to user creation dialog in https://github.com/pentaho/pentaho-platform/pull/5839 and https://github.com/pentaho/pentaho-platform/pull/5849 restricting allowed username characters was reverted.
=> fix[BISERVER-15341]: revert username char validation, add "-" to allowed password chars and fix error message

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml
- the scope had been lost when moving configs from Browse Files plugin
To be merged with: https://github.com/pentaho/pentaho-platform-ee/pull/1892
=> fix: change bean scope of GFS providers to session [PPUC-124]

assemblies/pom.xml
To be merged with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1893
- https://github.com/pentaho/pentaho-generic-file-system/pull/34
- https://github.com/pentaho/pentaho-generic-file-system-ee/pull/26
=> fix: incorrect GFS snapshot version number [PPUC-124]

pom.xml, user-console/pom.xml
This pull request contains minor updates to the Maven build configuration files. The changes focus on dependency version management and the configuration of build tasks.
Build configuration improvements:
* Removed the `byte-buddy.version` property from the main `pom.xml`, likely because it is no longer needed or has been centralized elsewhere.
* Updated the Ant plugin configuration in `user-console/pom.xml` by replacing the deprecated `<tasks>` element with `<target>`, improving compatibility and clarity in the build process.
=> [BACKLOG-43902]-Java 21 : compatibility check for Pentaho and fix Build and Run time issues while building / testing

.gitignore, extensions/src/it/resources/repository.spring.xml, extensions/src/test/resources/repository.spring.xml, repository/pom.xml, repository/src/it/java/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryAuthorizationIT.java, repository/src/main/resources/repository.spring.xml, repository/src/test/java/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryBase.java
- Fixed missing dependencies
- Restored `ApplicationContextPentahoSystemRegisterer` bean in `repository.spring.xml` test files so that it is possible to use `pen:bean` and `pen:list`
- Extensions:
- Before: Tests run: 542, Failures: 24, Errors: 41, Skipped: 2
- After: Tests run: 1774, Failures: 4, Errors: 4, Skipped: 1
- Repository:
- Before: Tests run: 24, Failures: 0, Errors: 0, Skipped: 0
- After: Tests run: 151, Failures: 1, Errors: 0, Skipped: 0
=> fix: many broken integration tests due to systemic issues [BACKLOG-45385]
