core/pom.xml
extensions/pom.xml
repository/pom.xml

@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186

[BACKLOG-13306] GAV change

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleFileDescriptor.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleFilesProcessor.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/LocaleFilesProcessorTest.java

@e-cuellar, @smaring, @mbatchelor, @pamval, could you please take a look?

[BISERVER-13813] - "1. Hello ETL" sample report not present in "Public/BI Developer Examples/Data Integration with Kettle/" folder

---

scheduler/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/ws/test/DefaultSchedulerServiceTest.java

Added accessing filter for returning jobs

[PDI-16794]-Regular users can view and delete scheduled jobs belonging to other users

---

api/pom.xml
core/pom.xml
extensions/pom.xml

@pentaho/2-1b gav change
for pentaho/pentaho-actionsequence-dom/pull/16

[BACKLOG-12713] GAV change

---

scheduler/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/ws/test/DefaultSchedulerServiceTest.java

[SP-4082] Backport of PDI-16794 - Regular users can view and delete scheduled jobs belonging to other users (8.0 Suite)

---

scheduler/pom.xml
scheduler/src/main/java/org/pentaho/platform/scheduler2/ws/DefaultSchedulerService.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/ws/test/DefaultSchedulerServiceTest.java

[SP-4081] Backport of PDI-16794 - Regular users can view and delete scheduled jobs belonging to other users (7.1 Suite)

---

pom.xml

[ENGOPS-3900] put api into separate profile

---

extensions/pom.xml

@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-reportwizard-core/pull/10

[BACKLOG-13972] Downstream updates

---

assemblies/pentaho-server/pom.xml

Reverts pentaho/pentaho-platform#4037
Requires further testing/validation. @pentaho/rogueone please review & process this PR revert

Revert "[BACKLOG-21349] Update Tomcat to 8.5.27"

---

core/src/main/java/org/pentaho/platform/engine/core/audit/MessageTypes.java
scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJob.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/quartz/BlockingQuartzJobTest.java

- checks for recreated jobs were added
- new log messages were added
- tests were updated

[BISERVER-13856] Duplicate records are written to the hibernate.pro_audit table, if scheduled report has failed during execution.

---

assemblies/pentaho-server/pom.xml

[BACKLOG-21349] reverting tomcat version change

---

assemblies/pentaho-solutions/pom.xml

after https://github.com/webdetails/cgg/pull/116

[BACKLOG-20486] mavenize cgg

---

api/pom.xml
assemblies/pentaho-war/pom.xml

@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149

[BACKLOG-20414] pentaho-commons-database downstream update

---

extensions/src/main/java/org/pentaho/platform/web/servlet/PluggableUploadFileServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/PluggableUploadFileServletTest.java

Reflected Cross-site Scripting (XSS) (8.0 Suite)

[SP-4086]-[PPP-3961]-PluggableUploadFileServlet.java vulnerable to

---

extensions/src/main/java/org/pentaho/platform/web/servlet/PluggableUploadFileServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/PluggableUploadFileServletTest.java

Reflected Cross-site Scripting (XSS) (7.1 Suite)

[SP-4085]-[PPP-3961]-PluggableUploadFileServlet.java vulnerable to

---

assemblies/pentaho-server/pom.xml
assemblies/pentaho-war/pom.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j.xml
pom.xml

- Map PDI log level to log4j threshold.
- Update format of the log entry.

[BACKLOG-21882] - Enable pdi log to roll to next day.

---

pom.xml

@duarteteixeira @pamval @mbatchelor @pedrofvteixeira @rmansoor

[PPP-4019] Use of vulnerable component Apache POI 3.15 CVE-2017-12626

---

user-console/src/main/java/org/pentaho/mantle/client/commands/AdhocRunInBackgroundCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java

Update Run in Background dialog to match schedule dialog

[BACKLOG-20930] Update Run in Background dialog to match schedule dialog

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryPublishResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/RepositoryPublishService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/RepositoryPublishResourceTest.java

[PRD-5569]-Published Report's Filename is Displayed instead of Title in

---

assemblies/pentaho-solutions/pom.xml

[CLEANUP] - MS Acess Plugins changed artifactId

---

extensions/src/main/java/org/pentaho/platform/web/servlet/UIServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/UIServletTest.java

[SP-4156] Backport of PPP-3963 - UIServlet.java needs to be removed from platform (8.0 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/servlet/UIServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/UIServletTest.java

[SP-4155] Backport of PPP-3963 - UIServlet.java needs to be removed from platform (7.1 Suite)

---

assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Dashboards/CTools_dashboard.cda
assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Dashboards/CTools_dashboard.cdfde
assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Dashboards/CTools_dashboard.wcdf
assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Dashboards/CTools_dashboard_files/js/steelwheels.require.js

- Created steelwheels require version
- Updated Dashboard to make the refresh silent
Related PR: https://github.com/webdetails/cde/pull/855

[BACKLOG-22634] CTools Dashboard sample file contains errors

---

extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/memory/UserRoleListEnhancedUserMap.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/RolePreprocessingMapperTests.java
extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/ldap/UnionizingLdapAuthoritiesPopulatorTests.java
extensions/src/test/java/org/pentaho/test/platform/plugin/services/security/userrole/memory/UserRoleListEnhancedUserMapFactoryBeanTests.java

- type mismatch were fixed
- tests were fixed
- new tests were added

[BISERVER-13916] Mondrian roles displaying errors with: Lorg.springframework.security.core.GrantedAuthority; cannot be cast to java.util.Collection

---

assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Dashboards/CTools_dashboard_files/css/steelwheels.css

@pentaho/millenniumfalcon @pamval please review
- UX changes to fix some issues with the dashboard styles

[BACKLOG-22856] fixed year selector, series toggle switches @ steelwheels

---

user-console/src/main/java/org/pentaho/mantle/client/commands/PentahoHomeCommand.java

[BACKLOG-23018] Update references to pentaho.com

---

core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListener.java
core/src/test/java/org/pentaho/platform/engine/core/system/PentahoSystemTest.java
core/src/test/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListenerTest.java
core/src/test/resources/log4j.xml

[SP-4237] Backport of BISERVER-13858 - Startup XActions called twice for each login (8.0 Suite)

---

core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListener.java
core/src/test/java/org/pentaho/platform/engine/core/system/PentahoSystemTest.java
core/src/test/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListenerTest.java
core/src/test/resources/log4j.xml

[SP-4236] Backport of BISERVER-13858 - Startup XActions called twice for each login (7.1 Suite)

---

assemblies/pentaho-war/pom.xml
core/pom.xml
pom.xml

[PDI-16908] Inspect Data, if you enter Japanese surrogate character as the data source name, "We couldn't connect" occurs.
- removed xalan dependency

[PDI-16908] Inspect Data, if you enter Japanese surrogate character as the data source name, "We couldn't connect" occurs.

---

user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-forums.html

[BACKLOG-23121] Updating links to the pentaho forums

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
user-console/src/main/resources/org/pentaho/mantle/public/home/js/favorites.js

[BACKLOG-22815] Updating the path to "spin.min.js"

---

core/src/main/java/org/pentaho/platform/engine/core/system/StandaloneApplicationContext.java

[BISERVER-13936] Pipe in username breaks reports

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java

[BACKLOG-23466] Add `webcontext.js?application=foo` query string parameter.

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilterTest.java

@pentaho/millenniumfalcon please squash and merge.
Merge with: pentaho/pentaho-platform-plugin-common-ui#1302.

[BACKLOG-23466] Refactor VizAPI module system.

---

user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-blogs.html
user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-documentation.html
user-console/src/main/resources-filtered/org/pentaho/mantle/public/home/content/welcome/ccp_sub-marketplace.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-forums.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-get-the-source.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-mailing-lists.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-report-bug.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/index.html

Reverts pentaho/pentaho-platform#4178

Revert "[SP-4411] Backport of BISERVER-13961 - Opening Forums throws the erro…"

---

user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-blogs.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-documentation.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-forums.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-get-the-source.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-mailing-lists.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-marketplace.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/ccp_sub-report-bug.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/welcome/index.html

Reverts pentaho/pentaho-platform#4179

Revert "[SP-4410] Backport of BISERVER-13961 - Opening Forums throws the erro…"

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/utils/EscapeUtils.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/utils/EscapeUtilsTest.java

[BACKLOG-24203] Saved CDE files should be properly formatted and "prettified"

---

extensions/src/it/java/org/pentaho/platform/web/http/api/resources/RepositoryImportResourceIT.java
user-console/src/main/resources/org/pentaho/mantle/public/browser/index.jsp

Modified per changes to `RepositoryImportResource` - `validateAccess `is changed to `validateImportAccess`

[BACKLOG-23730] As an admin I would like to have a user that could upload/download files using PUC outside of its home folder

---

assemblies/pentaho-solutions/pom.xml

Reverts pentaho/pentaho-platform#4209
@pentaho/r2d2 
@emartin-pentaho @pentaho-amessier

Revert "[BACKLOG-24588] Removing references to the kettle-json-plugin from assemblies"

---

extensions/src/main/java/org/pentaho/platform/plugin/action/pentahometadata/MetadataQueryComponent.java
extensions/src/test/java/org/pentaho/platform/plugin/action/pentahometadata/MetadataQueryComponentTest.java

Reverts pentaho/pentaho-platform#4211
Reverting the revert... @cravobranco

Revert "Revert "[SP-4489] - Backport of PDB-2016 - Dashboard Data Content Lin…"

---

extensions/src/main/java/org/pentaho/platform/web/http/ConfigurationAdminNonOsgiProxy.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/DirectoryResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryPublishResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SystemResource.java
repository/src/main/java/org/pentaho/platform/repository2/unified/fs/FileSystemRepositoryFileDao.java
repository/src/main/java/org/pentaho/platform/security/policy/rolebased/AllowAllAuthorizationPolicy.java

@pentaho/millenniumfalcon, @amartins23 and @pedrofvteixeira please review.
I recommend merging without squash, so the individual mostly unrelated commits are kept (for eventual cherry-picks and/or reverts).
~Don't forget https://github.com/pentaho/pentaho-platform-ee/pull/1273.~
**Note for the future:**
This PR removed the `/api/repo/files/generatedContentForSchedule` endpoint.
This endpoint just mirrored `/api/scheduler/generatedContentForSchedule` and was introduced in #1970 for no apparent reason.
It introduced a dependency with the scheduling features and related libs, that might be unavailable in some particular Pentaho platform assemblies.
Also see discussion bellow: https://github.com/pentaho/pentaho-platform/pull/4214#discussion_r209020930.

[BACKLOG-24896] Various fixes needed for the CDE on Foundry assembly

---

assemblies/pentaho-server/pom.xml

[BACKLOG-24949] Tomcat in 8.1 / 7.1 vulnerable to CVE-2018-8037

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactory.java
core/src/test/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactoryTest.java

@mbatchelor @pentaho-lmartins 
This pull request contains two commits, one for the fix and the other for checkstyle.

[PPP-4191] - Potential performance issue with OSGIObjectFactory

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactory.java
core/src/test/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactoryTest.java

@pentaho-lmartins @ricardosilva88 @cravobranco

[SP-4655] - Backport of PPP-4191 - Potential performance issue with OSGIObjectFactory (7.1 Suite)

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactory.java
core/src/test/java/org/pentaho/platform/engine/core/system/objfac/OSGIObjectFactoryTest.java

@pentaho-lmartins @ricardosilva88 @cravobranco

[SP-4656] - Backport of PPP-4191 - Potential performance issue with OSGIObjectFactory (8.1 Suite)

---

api/pom.xml
assemblies/pentaho-server/pom.xml
assemblies/pentaho-war/pom.xml
core/pom.xml
extensions/pom.xml
extensions/src/main/java/org/pentaho/platform/config/PentahoXml.java
extensions/src/test/java/org/pentaho/platform/config/PentahoXmlTest.java
pom.xml
repository/pom.xml

This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo

[PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

---

pom.xml

Reverts pentaho/pentaho-platform#4266

Revert "[CLEANUP] cleaning profiles"

---

extensions/src/main/java/org/pentaho/platform/osgi/KarafBoot.java
extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java

[PPP-4201] KarafBoot ignoring potential failures in various method calls

---

assemblies/pentaho-war/pom.xml
pom.xml

@pedrofvteixeira please review.
Merge with: https://github.com/pentaho/big-data-plugin/pull/1593

[BISERVER-14068] Remove Apache Axis axis-1.4.jar and axis-saaj-1.4.jar

---

repository/src/main/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebService.java

Correction of a NullPointerException

[BACKLOG-26593] - CLONE: Ability to Disable user folder creation under Home directory in PUC

---

extensions/pom.xml
pom.xml

This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/85

[SP-4828] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (8.2 Suite)

---

assemblies/pentaho-war/pom.xml

[BACKLOG-26908] Streaming Broken - Wrong rxjava version in pentaho-server

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDao.java

This reverts work done in #4317 and moves that fix to another place with an additional validation.
@mdamour1976 @pentaho/tatooine @ricardosilva88 please review

[BACKLOG-26863] - Fixed Cut and Paste actions cause error in PUC

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleImportHandler.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/LocaleImportHandlerTest.java

Cherry-pick of #4327 and #4340 into 8.2 branch.
@smmribeiro

[SP-4911] Backport of BISERVER-14070 - Language Translations Properties Files not picked up on Xactions running on Server (8.2 Suite)

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
pom.xml

[BACKLOG-27567] Centralize org.osgi dependencies management

---

assemblies/pentaho-war/pom.xml
pom.xml

[BACKLOG-27572] Remove felix-fileinstall dependency

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
pom.xml

[BACKLOG-27576] Remove unneeded Felix Utils dependency

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
pom.xml

[BACKLOG-27574] Centralize Felix HTTP dependency version

---

assemblies/pentaho-war/pom.xml
core/pom.xml
extensions/pom.xml
pom.xml
repository/pom.xml
scheduler/pom.xml

[BACKLOG-27575] Remove Felix Main dependency

---

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/SolutionBrowserPanel.java

text and right justify the OK button as per the UI Specs

 [BISERVER-13897] - Fixed the missing plugin dialog to left justify the

---

api/pom.xml
assemblies/pentaho-war/pom.xml
core/pom.xml
extensions/pom.xml
pom.xml
repository/pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/111
@graimundo

[BACKLOG-27566] Centralize SLF4J dependency

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/dialects/mysql5/audit_sql.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/dialects/oracle10g/audit_sql.xml

- correction for Oracle and MySQL

[BISERVER-13674] - pro_audit table throws exception on folders and report names that exceed 200 characters

---

build-utils/README.md
extensions/pom.xml
pom.xml

@lgrill-pentaho @emartin-pentaho @jmcrfp

[ENGOPS-4928] removed build-utils

---

extensions/pom.xml
pom.xml

@pentaho/tatooine @pentaho-lmartins

[PPP-4339] Use of Vulnerable Component: jsf-api-1.1.jar (CVE-2008-1285)

---

scheduler/pom.xml
scheduler/src/it/java/org/pentaho/platform/scheduler2/ws/test/JaxWsSchedulerServiceIT.java
scheduler/src/it/java/org/pentaho/platform/scheduler2/ws/test/ScheduleAuthorizationPolicy.java

@graimundo 
2 commits, need squash merge
CC: @jmcrfp @pentaho-lmartins

[PPP-4223] - Adding dependencies for IT testing and fixing Schedule IT

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml

[BACKLOG-28362] Remove angular directives. No longer exists in common-ui

---

pom.xml

…en-parent-poms)
Tested this version with pentaho-server locally and all seemed fine, let's hope we get it right this time around

[BACKLOG-28357] Updates Apache Derby, retrieves from parent POM

---

extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileUtils.java
extensions/src/test/java/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java

@pentaho/tatooine @pentaho-lmartins

[PPP-4394] Japanese character in the data source name causes error

---

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp

- corrected possible overlap of error messages, when one is shown, previous ones are removed.

[BACKLOG-28928] - Update login screen for Pentaho User Console

---

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp

Logging into Pentaho User Console after the "Session Expires", the locale becomes English (8.2 Suite)
[SP-5116] Adding logic from BISERVER-14220
@smmribeiro cc @pentaho-lmartins + @gryphendowre @wseyler

[SP-5116] Backport of BISERVER-14220

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoServices.spring.xml
extensions/src/main/java/org/pentaho/platform/web/WebUtil.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserConsoleResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserSettingsResource.java
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilter.java
extensions/src/main/java/org/pentaho/platform/web/servlet/ServletBase.java
extensions/src/test/java/org/pentaho/platform/web/WebUtilTest.java
extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilterTest.java
user-console/src/main/java/org/pentaho/mantle/client/MantleEntryPoint.java
user-console/src/main/java/org/pentaho/mantle/client/commands/CollapseBrowserCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/ShowBrowserCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/SwitchLocaleCommand.java
user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/SolutionBrowserPanel.java
user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/filepicklist/AbstractFilePickList.java
user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
user-console/src/main/resources/org/pentaho/mantle/public/browser/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.utils.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js
user-console/src/main/resources/org/pentaho/mantle/public/home/js/FavoritesController.js
user-console/src/main/resources/org/pentaho/mantle/public/home/js/favorites.js

This PR is part of a set: https://github.com/pentaho/pentaho-platform-ee/pull/1333.

[BACKLOG-29696] CSRF Marketo Use Case

---

extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfOrRequestMatcher.java

[BACKLOG-29696] Fix to 'filterChainProxy' initialization error

---

extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfTokenResponseHeaderFilterTest.java

Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1460

[BACKLOG-29696] Take into account when protection is disabled and token isn't created

---

assemblies/pentaho-server/pom.xml

This is a twin of https://github.com/pentaho/pentaho-platform-ee/pull/1342.
@ppatricio @bantonio82

[PDB-2048] Dashboard with Prompts Returns 400 (Bad Request)

---

user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

@pentaho/tatooine @RPAraujo @bcostahitachivantara

[SP-5210] Backport of ANALYZER-3802 - Error pressing Cancel in Select Data Source window when creating a new PAZ (8.3 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java

@pentaho/tatooine @RPAraujo @pentaho-lmartins 
* [BISERVER-14294] Putting in a fix that protects the integrity of the ACL owner when setting the ACL from the Web API.
* [BISERVER-14294] Added test file and updated copyright

[BISERVER-14294] "Browse File" crashes when changing the owner of a folder/file with "<script>alert(999)</script>"

---

assemblies/pentaho-server/pom.xml
assemblies/pentaho-war/pom.xml
core/pom.xml
pom.xml
repository/pom.xml
scheduler/pom.xml

@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
* [PDI-17794] Removing dependency due to being marked as unused and declared via dependency:analyze (scheduler/pom.xml)
* [PDI-17794] Removed the version information for apache-log4j-extras, allowing top-level maven-parent-poms to handle it
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- …

[PDI-17794] Warnings in Spoon console due to wrong version of log4j

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java

[SP-5251] Backport of BISERVER-14294 - "Browse File" crashes when changing the owner of a folder/file with "<script>alert(999)</script>" (8.3 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/FileResourceTest.java

[SP-5250] Backport of BISERVER-14294 - "Browse File" crashes when changing the owner of a folder/file with "<script>alert(999)</script>" (7.1 Suite)

---

extensions/src/main/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java
extensions/src/test/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperTest.java

[PPP-4192] - Inconsistent synchronization MondrianCatalogHelper.java

---

extensions/src/main/java/org/pentaho/platform/osgi/KarafBoot.java
extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java

[CLEANUP] reuse logger variables

---

assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Enterprise Edition/DashboardDesigner.html
assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Enterprise Edition/InteractiveReport.html
assemblies/pentaho-samples/src/main/resources/samples/public/Steel Wheels/Enterprise Edition/PentahoAnalyzer.html
user-console/src/main/resources/org/pentaho/mantle/public/home/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/home/js/gettingStarted.js
user-console/src/main/resources/org/pentaho/mantle/public/home/properties/config.properties
user-console/src/main/resources/org/pentaho/mantle/public/home/properties/config_de.properties
user-console/src/main/resources/org/pentaho/mantle/public/home/properties/config_fr.properties
user-console/src/main/resources/org/pentaho/mantle/public/home/properties/config_ja.properties
user-console/src/main/resources/org/pentaho/mantle/public/home/properties/config_zh_CN.properties

[BISERVER-14040] - Welcome and Tutorial videos do not play

---

core/src/main/java/org/pentaho/platform/engine/security/event/PentahoLoggerListener.java

@pentaho/tatooine @pentaho-lmartins @ssamora 
* [BISERVER-14295] Reversed logic of checking for class assignment.

[BISERVER-14295] PentahoLoggerListener doesn't log authentication events

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileSid.java

[CLEANUP] Updating copyright year on 'RepositoryFileSid.java'

---

user-console/src/main/java/org/pentaho/mantle/client/commands/PurgeMondrianSchemaCacheCommand.java

Merge with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1365

[BACKLOG-31897] MARKETO - CSFR - /api/system/refresh

---

user-console/src/main/java/org/pentaho/mantle/client/commands/SaveCommand.java
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
user-console/src/main/resources/org/pentaho/mantle/public/home/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/home/js/favorites.js

Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1486

[BACKLOG-31795] Layout Editor CRUDL

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfToken.java
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfUtil.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorTest.java
extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfUtilTest.java
user-console/src/main/java/org/pentaho/mantle/client/dialogs/ImportDialog.java

[BACKLOG-31896] MARKETO - CSFR - /api/repo/files/import

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessor.java
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfUtil.java

[BACKLOG-31893] - [MARKETO] CSRF - /data-access/api/mondrian

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js

- by doing this, the extra `,` was also removed

[BACKLOG-29696] Remove csrf service dependency, because it is not being used.

---

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/drilldown-profile.xml

Additional PR to complete what was done in: https://github.com/pentaho/pentaho-reporting/pull/1299
Change is similar, please check that PR.
@pentaho-lmartins @pentaho/tatooine

[PRD-6069] Pentaho Report Designer Hyperlink adds ? automatically

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml

https://jira.pentaho.com/browse/BACKLOG-32449

[BACKLOG-32449]  Making cluster test accessible to authenticated users

---

user-console/src/main/java/org/pentaho/mantle/client/commands/OpenFileCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/SaveCommand.java

- only includes code cleanup
Merge with:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/749

[BACKLOG-32839] Fix SaveAs dialog's file tree not refreshing after a Save

---

core/src/main/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListener.java
core/src/test/java/org/pentaho/platform/engine/security/event/PentahoSessionStartupAuthenticationSuccessListenerTest.java

Reverts pentaho/pentaho-platform#4561

Revert "[BISERVER-14269] - KTR triggered by Session Start up X-Action does no…"

---

extensions/src/main/java/org/pentaho/platform/osgi/KarafBoot.java
extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java

merge with:
- https://github.com/pentaho/pentaho-karaf-assembly/pull/620
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/279

[BACKLOG-32957] Karaf logs under pentaho Server are created under pentaho-solutions

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelper.java
repository/src/main/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebService.java
repository/src/test/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebServiceTest.java

[BISERVER-14305] - Admin doesn't see deleted file in the trash folder

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleImportHandler.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/LocaleImportHandlerTest.java

@pentaho/tatooine @pentaho-lmartins @ppatricio 
* [BISERVER-14371] Add in a check to ensure that the locale file being checked is not a recognized non-locale/property file (children files registered under the unified registry). No need to check these report files to see if they have a parent locale/property file with another report file.
* [BISERVER-14371] Adding test method

[BISERVER-14371] PRPT reports with similar titles have a mismatch in the UI when uploaded to the Server

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IPlatformImportBundle.java
api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileExtraMetaData.java
extensions/src/it/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PDIImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundle.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ExportManifestRepositoryException.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ImportSession.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestEntity.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaData.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntry.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestProperty.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.xsd
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundleTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntryTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryFileProxy.java
repository/src/main/resources/com/pentaho/pdi/messages/messages.properties

[BISERVER-12300] - Metadata on files/folders erased during export/import

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

Merge After:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/761
Changed the execute now button, to check if it can execute the selected jobs, before the actual execution. In case it can not execute, a prompt will appear asking if the user want to remove those schedules.

[BISERVER-13065] Scheduled task with deleted/renamed source report

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelper.java
repository/src/main/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebService.java
repository/src/main/resources/org/pentaho/platform/repository2/messages/messages.properties
repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelperTest.java
repository/src/test/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebServiceTest.java

Backport of:
- [pentaho-platform#4618](https://github.com/pentaho/pentaho-platform/pull/4618)
- [pentaho-platform#4628](https://github.com/pentaho/pentaho-platform/pull/4628)
@pentaho-lmartins

[SP-5394] Backport of BISERVER-14305 - Admin doesn't see deleted file in the trash folder (8.3 Suite)

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelper.java
repository/src/main/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebService.java
repository/src/main/resources/org/pentaho/platform/repository2/messages/messages.properties
repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/DefaultDeleteHelperTest.java
repository/src/test/java/org/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebServiceTest.java

Backport of:
- [pentaho-platform#4618](https://github.com/pentaho/pentaho-platform/pull/4618)
- [pentaho-platform#4628](https://github.com/pentaho/pentaho-platform/pull/4628)
@pentaho-lmartins

[SP-5395] Backport of BISERVER-14305 - Admin doesn't see deleted file in the trash folder (9.0 Suite)

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleaner.java
repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleanerTest.java

Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-platform/commit/785a8e31bf3e280581d28eb1e63d929cb0d09ee7
* https://github.com/Pentaho/pentaho-platform/commit/68828d2a509551569a67b42d65a1ef8f2ea58e83

[SP-5398] Backport of BISERVER-14373 - RepositoryCleaner GC job terminates early allowing uncontrolled Repository DB growth (8.3 Suite)

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IPlatformImportBundle.java
api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileExtraMetaData.java
extensions/src/it/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PDIImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundle.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ExportManifestRepositoryException.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ImportSession.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestEntity.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaData.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntry.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestProperty.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.xsd
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundleTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntryTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryFileProxy.java
repository/src/main/resources/com/pentaho/pdi/messages/messages.properties

Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-platform/commit/639b7e8f9e823432f9e51ac4a8742848f9d0d247

[SP-5413] Backport of BISERVER-12300 - Metadata on files/folders erased during export/import (8.3 Suite)

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IPlatformImportBundle.java
api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileExtraMetaData.java
extensions/src/it/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PDIImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundle.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ExportManifestRepositoryException.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ImportSession.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestEntity.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaData.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntry.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestProperty.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.xsd
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundleTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntryTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryFileProxy.java
repository/src/main/resources/com/pentaho/pdi/messages/messages.properties

Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-platform/commit/639b7e8f9e823432f9e51ac4a8742848f9d0d247

[SP-5414] Backport of BISERVER-12300 - Metadata on files/folders erased during export/import (9.0 Suite)

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleaner.java
repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleanerTest.java

Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-platform/commit/785a8e31bf3e280581d28eb1e63d929cb0d09ee7
* https://github.com/Pentaho/pentaho-platform/commit/68828d2a509551569a67b42d65a1ef8f2ea58e83

[SP-5399] Backport of BISERVER-14373 - RepositoryCleaner GC job terminates early allowing uncontrolled Repository DB growth (9.0 Suite)

---

extensions/pom.xml
pom.xml
repository/pom.xml
repository/src/main/java/org/pentaho/platform/repository/solution/filebased/MondrianVfs.java

This reverts commit 6b0378c4b575204234cdbd2ae51ec8763927b575, reversing
changes made to ac0d1699a98757cf81e9c8d6c13703e09181747b.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …

Revert "Merge pull request #4651 from gryphendowre/SP-5370"

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IPlatformImportBundle.java
api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileExtraMetaData.java
extensions/src/it/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PDIImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundle.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ExportManifestRepositoryException.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ImportSession.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestEntity.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaData.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntry.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestProperty.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.xsd
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundleTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntryTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryFileProxy.java
repository/src/main/resources/com/pentaho/pdi/messages/messages.properties

@ssamora 
@ppatricio 
@smmribeiro

[SP-5413] - Backport of BISERVER-12300 - Metadata on files/folders erased during export/import (8.3 Suite)

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

@pentaho/r2d2 
@pminutillo 
@wseyler 
@e-cuellar 
@cseverino789

[BACKLOG-30159] Implement lazy loading for the Browse perspective in PUC

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IPlatformImportBundle.java
api/src/main/java/org/pentaho/platform/api/repository2/unified/RepositoryFileExtraMetaData.java
extensions/src/it/java/org/pentaho/platform/web/http/api/resources/services/FileServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/PDIImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundle.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportFileHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ExportManifestRepositoryException.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/ImportSession.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestEntity.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaData.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntry.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestProperty.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.xsd
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/RepositoryFileImportBundleTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/ImportSessionTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataEntryTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/EntityExtraMetaDataTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryFileProxy.java
repository/src/main/resources/com/pentaho/pdi/messages/messages.properties

@pentaho-lmartins
@ssamora
@ppatricio
@smmribeiro

[SP-5414] - Backport of BISERVER-12300 - Metadata on files/folders erased during export/import (9.0 Suite)

---

repository/src/main/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStream.java
repository/src/test/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileIoTest.java
repository/src/test/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStreamTest.java

@ssamora 
@ppatricio 
@smmribeiro

[BISERVER-14290] - Schedules created on the User Console runs twice if  the user scheduling does not have "Create Content" permission.

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@ssamora 
@ppatricio 
@smmribeiro

[BACKLOG-34399] - PUC - Edit Schedule create a new Schedule in the list of Schedules

---

extensions/src/main/java/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProvider.java
extensions/src/test/java/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProviderTest.java

@pentaho-lmartins
@ssamora
@ppatricio
@smmribeiro

[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml
extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/PentahoEhCacheBasedUserCache.java
extensions/src/test/java/org/pentaho/platform/plugin/services/security/userrole/PentahoEhCacheBasedUserCacheTest.java

@ssamora 
@ppatricio 
@smmribeiro

[BISERVER-14417] - cachingUserDetailsService fails to cache user information based on case sensitivity

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/IStreamListener.java
core/src/main/java/org/pentaho/platform/util/ActionUtil.java
core/src/main/java/org/pentaho/platform/util/Emailer.java
core/src/main/java/org/pentaho/platform/util/web/MimeHelper.java
core/src/test/java/org/pentaho/platform/util/web/MimeHelperTest.java
repository/src/main/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStream.java
repository/src/test/java/org/pentaho/platform/repository2/unified/fileio/RepositoryFileOutputStreamTest.java
scheduler/src/main/java/org/pentaho/platform/scheduler2/action/ActionRunner.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/action/ActionRunnerTest.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/email/EmailerTest.java

[BISERVER-14534] - Running jobs or transformations via Schedules created on PUC stop running after multiple executions

---

user-console/src/main/java/org/pentaho/mantle/client/admin/ContentCleanerPanel.java

[BISERVER-14520] - GeneratedContent does not delete content as scheduled because age for deletion does not match with create date

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

[SP-5823] - Backport of BISERVER-14332 - Cannot Change User Password When Admin User's Password Contains a Special Character (8.3 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

[BISERVER-13833] - createUser transmits password in clear text

---

assemblies/pentaho-server/src/main/resources-filtered/Encr.bat
assemblies/pentaho-server/src/main/resources-filtered/encr.sh

@bcostahitachivantara @smmribeiro @pentaho-lmartins

[BACKLOG-34973] Copyright data (year) not updated after applying SP

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

[SP-5839] - Backport of BISERVER-13833 - createUser transmits password in clear text (9.1 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

[SP-5840] - Backport of BISERVER-13833 - createUser transmits password in clear text (8.3 Suite)

---

assemblies/pentaho-server/pom.xml

Changes for new CDPDC 7.1 Shim

BACKLOG-34725 Cdpdc71 Shim integration

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java

[BISERVER-14075] - api userRoleManagement \ deleteUsers put - wrong response code it is always 200

---

repository/src/main/java/org/pentaho/platform/security/userroledao/DefaultTenantedPrincipleNameResolver.java
repository/src/test/java/org/pentaho/test/platform/security/userroledao/DefaultTenantedPrincipleNameResolverTest.java

[BISERVER-14423] - Roles in lowercase/UPPERCASE are different for Creation/Deletion Event Order Affects Outcome

---

repository/src/main/java/org/pentaho/platform/security/userroledao/DefaultTenantedPrincipleNameResolver.java
repository/src/test/java/org/pentaho/test/platform/security/userroledao/DefaultTenantedPrincipleNameResolverTest.java

Reverts pentaho/pentaho-platform#4808

Revert "[BISERVER-14423] - Roles in lowercase/UPPERCASE are different for Creation/Deletion Event Order Affects Outcome"

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java

Reverts pentaho/pentaho-platform#4810

Revert "[BISERVER-14075] - api userRoleManagement \ deleteUsers put - wrong response code it is always 200"

---

user-console/src/main/resources/org/pentaho/mantle/public/home/index.jsp

@smmribeiro @bcostahitachivantara 
Depends on:
https://github.com/pentaho/maven-parent-poms/pull/258
Other PRs for this issue:
https://github.com/pentaho/pentaho-osgi-bundles/pull/379
https://github.com/pentaho/pentaho-platform-ee/pull/1434

[PPP-4546] Use of Vulnerable Component: Components/jquery:3.4.1

---

user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java

[SP-5879] - Backport of BISERVER-14291 - Append Timestamp to generated content option does not work on reports with no parameters (8.3 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java

[SP-5880] - Backport of BISERVER-14291 - Append Timestamp to generated content option does not work on reports with no parameters (9.1 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicProcessingFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilterTest.java

[PPP-4635] - Security Vulnerability: Session-expiry and Server-time cookies are missing Secure and HTTPOnly flag, we need option to configure it

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-jdbc.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-memory.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-superuser.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml
extensions/src/main/java/org/pentaho/platform/config/AppConfigProperties.java
extensions/src/main/java/org/pentaho/platform/config/SpringSecurityHibernateConfig.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
extensions/src/test/java/org/pentaho/platform/config/AppConfigPropertiesTest.java
extensions/src/test/java/org/pentaho/platform/config/SpringSecurityHibernateConfigTest.java
repository/src/main/java/org/pentaho/platform/repository2/userroledao/jackrabbit/security/DefaultPentahoPasswordEncoder.java
repository/src/main/java/org/pentaho/platform/security/userroledao/ws/ProxyPentahoUserRoleHelper.java
repository/src/test/java/org/pentaho/platform/security/userroledao/jackrabbit/DefaultPentahoPasswordEncoderTest.java
repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java

to address security issues in older versions.  Minor changes needed to
accommodate api updates.

[BACKLOG-35047] Update to Spring framework 5.3 and Spring security 5.4

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-jdbc.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-memory.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-superuser.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml
extensions/src/main/java/org/pentaho/platform/config/AppConfigProperties.java
extensions/src/main/java/org/pentaho/platform/config/SpringSecurityHibernateConfig.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
extensions/src/test/java/org/pentaho/platform/config/AppConfigPropertiesTest.java
extensions/src/test/java/org/pentaho/platform/config/SpringSecurityHibernateConfigTest.java
repository/src/main/java/org/pentaho/platform/repository2/userroledao/jackrabbit/security/DefaultPentahoPasswordEncoder.java
repository/src/main/java/org/pentaho/platform/security/userroledao/ws/ProxyPentahoUserRoleHelper.java
repository/src/test/java/org/pentaho/platform/security/userroledao/jackrabbit/DefaultPentahoPasswordEncoderTest.java
repository/src/test/java/org/pentaho/test/platform/security/userroledao/ws/UserRoleWebServiceBase.java

Reverts pentaho/pentaho-platform#4828

Revert "[BACKLOG-35047] Update to Spring framework 5.3 and Spring security 5.4"

---

assemblies/pentaho-server/pom.xml

[BACKLOG-35047] Need windows x64 tomcat build in pom file and

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java

[BISERVER-14628] - createUser and updatePassword don´t allowed in password the character '%'

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIRuntimeObjectFactory.java

[BISERVER-12846] Exceptions thrown on BA or DI server is shutdown

---

repository/src/main/java/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

@ssamora 
@smmribeiro
@moraesvc

[SP-5917] - Backport of BISERVER-14423 - Roles in lowercase/UPPERCASE are different for Creation/Deletion Event Order Affects Outcome (9.1 Suite)

---

repository/src/main/java/org/pentaho/platform/security/userroledao/jackrabbit/AbstractJcrBackedUserRoleDao.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5916] - Backport of BISERVER-14423 - Roles in lowercase/UPPERCASE are different for Creation/Deletion Event Order Affects Outcome (8.3 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@ssamora 
@smmribeiro 
@moraesvc

[PPP-4649] - Endpoint Scheduler/Job JobName open to Cross Site Scripting

---

user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFileCommand.java

@ssamora 
@smmribeiro 
@moraesvc

[PPP-4650] - Move to Trash open to Cross Site Scripting after renaming existing file

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIRuntimeObjectFactory.java

[SP-5943] - Backport of BISERVER-12846 - Exceptions thrown on BA or DI server is shutdown (8.3 Suite)

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/OSGIRuntimeObjectFactory.java

[SP-5944] - Backport of BISERVER-12846 - Exceptions thrown on BA or DI server is shutdown (9.1 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFileCommand.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5948] - Backport of PPP-4650 - Move to Trash open to Cross Site Scripting after renaming existing file (8.3 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFileCommand.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5949] - Backport of PPP-4650 - Move to Trash open to Cross Site Scripting after renaming existing file (9.1 Suite)

---

extensions/src/main/java/org/pentaho/platform/plugin/action/chartbeans/DefaultChartBeansGenerator.java

[BACKLOG-35181] system/tmp directory needs to be created before files

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5959] - Backport of PPP-4649 - Endpoint Scheduler/Job JobName open to Cross Site Scripting (9.1 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5958] - Backport of PPP-4649 - Endpoint Scheduler/Job JobName open to Cross Site Scripting (8.3 Suite)

---

core/src/main/java/org/pentaho/platform/util/ManifestUtil.java

JBoss; react to changes in JBoss 7.3 VFS classes.  Also cleans up some
minor code style issues.

[BACKLOG-35188] Updates needed to read manifest files from jars on

---

extensions/src/main/java/org/pentaho/platform/plugin/action/chartbeans/DefaultChartBeansGenerator.java

can be created in it.
This commit is a cherry-pick from master ed8c84ab60

[SP-5964] system/tmp directory needs to be created before files

---

extensions/src/main/java/org/pentaho/platform/plugin/action/chartbeans/DefaultChartBeansGenerator.java

can be created in it.
This commit is a cherry-pick from master ed8c84ab60

[SP-5963] system/tmp directory needs to be created before files

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java

transformations in order for all references to be resolved propertly.

[PDI-19087] Shared databases need to be imported before jobs or

---

user-console/src/main/java/org/pentaho/mantle/client/MantleEntryPoint.java
user-console/src/main/java/org/pentaho/mantle/client/commands/SwitchLocaleCommand.java
user-console/src/main/resources/org/pentaho/mantle/public/Mantle.jsp
user-console/src/main/resources/org/pentaho/mantle/public/MantleDebug.jsp

This PR partially reverts the changes of https://github.com/pentaho/pentaho-platform/pull/4904.

[ANALYZER-3942] Restoring ?locale query string parameter modifying session locale

---

user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFileCommand.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5950] - Backport of PPP-4650 - Move to Trash open to Cross Site Scripting after renaming existing file (9.2 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5960] - Backport of PPP-4649 - Endpoint Scheduler/Job JobName open to Cross Site Scripting (9.2 Suite)n to Cross Site Scripting (9.2 Suite)

---

extensions/pom.xml
pom.xml

(cherry picked from commit 0abd095ea26e3277882238527b71be16c42a334a)

[SP-5969][BISERVER-14200] Upgrade Janino jar

---

extensions/pom.xml
pom.xml

(cherry picked from commit 0abd095ea26e3277882238527b71be16c42a334a)

[SP-5968][BISERVER-14200] Upgrade Janino jar

---

extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java

… job executed on Pentaho server
(cherry picked from commit 3256735152fe87388fa93796de6d5f8f8ead04f5)

[SP-5989][PDI-19055] CLIENT column in PDI job log table records "unknown" when job executed on Pentaho server

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java

transformations in order for all references to be resolved propertly.
This commit is a cherry-pick from master afe88a984

[SP-6012] Shared databases need to be imported before jobs or

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java

transformations in order for all references to be resolved propertly.
This commit is a cherry-pick from master afe88a984

[SP-6011] Shared databases need to be imported before jobs or

---

extensions/pom.xml

[BACKLOG-35260] Pull in commons-compiler jar file to satisfy janino

---

extensions/pom.xml

[SP-5968] [BACKLOG-35260] Pull in commons-compiler jar file to satisfy janino

---

assemblies/pentaho-server/pom.xml
assemblies/pentaho-war/pom.xml

[PDI-18966] Text File output does not write to named staging area with  latest snowflake jdbc 3.12.x driver

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/web.xml
assemblies/pentaho-war/src/main/webapp/js/pentaho-ajax.js
extensions/src/main/java/org/pentaho/platform/web/http/filters/PentahoWebContextFilter.java
extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSPluginServlet.java
extensions/src/main/java/org/pentaho/platform/web/servlet/JAXRSServlet.java
extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileServlet.java
extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileUtils.java
user-console/build-resources/WEB-INF/web.xml
user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java
user-console/src/main/java/org/pentaho/mantle/client/dialogs/ImportDialog.java
user-console/src/main/resources/org/pentaho/mantle/MantleApplication.gwt.xml
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

Depends on:
- https://github.com/pentaho/maven-parent-poms/pull/301.
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/797
- https://github.com/pentaho/pentaho-commons-xul/pull/201
See PR set: https://github.com/pentaho/security-web/pull/10.
@bennychow, @ddiroma please review and merge.

[BACKLOG-35298] CSRF - ImportDialog should specify the CSRF token as a form parameter

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileUtils.java
extensions/src/test/java/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java
repository/src/main/java/org/pentaho/platform/repository/webservices/DatabaseConnectionAdapter.java

Original PRs:
- https://github.com/pentaho/pentaho-platform/pull/4888
- https://github.com/pentaho/pentaho-platform/pull/4895
- https://github.com/pentaho/pentaho-platform/pull/4927
@smmribeiro 
@renato-s

[CUST-258] - Requesting a CUST for the Critical Flaws Uncovered in Pentaho

---

extensions/pom.xml
repository/pom.xml

[CUST-258] - Update Pom Versions

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
extensions/pom.xml
extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileUtils.java
extensions/src/test/java/org/pentaho/platform/web/servlet/UploadFileUtilsTest.java
repository/pom.xml
repository/src/main/java/org/pentaho/platform/repository/webservices/DatabaseConnectionAdapter.java

@smmribeiro 
@ssamora 
@renato-s

[CUST-259] - Requesting a CUST for the Critical Flaws Uncovered in Pentaho (v9.0.0.7)

---

extensions/pom.xml
repository/pom.xml

[CUST-259] - Update Pom Versions

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/osgi/log4j2.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
core/src/test/resources/log4j2.xml
extensions/src/main/resources/log4j/log4j2.xml
extensions/src/test/resources/log4j2.xml
repository/src/test/resources/log4j2.xml

[BISERVER-14794] Upgrade log4j2

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/osgi/log4j2.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
core/src/test/resources/log4j2.xml
extensions/src/main/resources/log4j/log4j2.xml
extensions/src/test/resources/log4j2.xml
repository/src/test/resources/log4j2.xml

[SP-6107] [BISERVER-14794] Upgrade log4j2

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/osgi/log4j2.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
core/src/test/resources/log4j2.xml
extensions/src/main/resources/log4j/log4j2.xml
extensions/src/test/resources/log4j2.xml
repository/src/test/resources/log4j2.xml

[SP-6106] [BISERVER-14794] Upgrade log4j2

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml

[BACKLoG-30660] : CSRF - /api/system/refresh added missing '/'

[BACKLoG-30660] : CSRF - /api/system/refresh added missing '/'

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml

[BACKLOG-30659] : CSRF - /api/session related changes

[BACKLOG-30659] : CSRF - /api/session related changes

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml

[BACKLOG-30664] CSRF - /api/repo/publish changes

[BACKLOG-30664] CSRF - /api/repo/publish changes

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml

[BACKLOG-30665] - CSRF - /api/emailconfig changes

[BACKLOG-30665] - CSRF - /api/emailconfig changes

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml

This fixes a syntax issue that I introduced, when, upon merging https://github.com/pentaho/pentaho-platform/pull/5037, I attempted to resolve conflicts with the base branch by using github's conflicts editor...
FYI: @PawanPonugupati

[BACKLOG-30665] Fix merge issue in applicationContext-spring-security-csrf.xml

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
assemblies/pentaho-war/src/main/webapp/js/parameters.js
user-console/src/main/java/org/pentaho/mantle/client/admin/ContentCleanerPanel.java
user-console/src/main/java/org/pentaho/mantle/client/commands/RunInBackgroundCommand.java
user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[BACKLOG-30667] - CSRF - /api/scheduler changes

[BACKLOG-30667] CSRF - /api/scheduler changes

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SystemResource.java

@smmribeiro
@andreramos89
@renato-s

[BACKLOG-35440] - In PUC when scheduling a file - the scheduling window time zone drop down has repeated time zones

---

assemblies/pentaho-server/src/main/resources-filtered/import-export.bat
assemblies/pentaho-server/src/main/resources-filtered/import-export.sh

Reverts pentaho/pentaho-platform#5047

Revert "Backlog 35632"

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/MondrianImportHandler.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importer/MondrianImportHandlerTest.java

@smmribeiro 
@andreramos89 
@renato-s

[BISERVER-14717] - Manage Data Sources option breaks after importing a corrupt Mondrian schema file.

---

repository/src/test/java/org/pentaho/platform/repository2/unified/UnifiedRepositoryTestUtils.java

[BACKLOG-35752] - Address failing tests in platform-user-console

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

The “>” button adjacent to Trash in PUC is misleading

---

extensions/src/main/java/org/pentaho/platform/osgi/SystemPackageExtrapolator.java
extensions/src/test/java/org/pentaho/platform/osgi/SystemPackageExtrapolatorTest.java

not an instance of URLClassLoader (PMR on JDK9+).

[BACKLOG-35814] Handle karaf startup when the application classloader is

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/deeplink_allowed_urls.properties
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho-spring-beans.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoServices.spring.xml
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/MantleResource.java
user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java

[PPP-4745] - Security Scan vulnerability - Insecure Object Rendering in PUC

---

api/src/main/java/org/pentaho/platform/api/data/IDBDatasourceService.java
api/src/main/java/org/pentaho/platform/api/data/IPooledDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/BaseDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledOrJndiDatasourceService.java
core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledOrJndiDatasourceServiceTest.java
extensions/src/main/java/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProvider.java
extensions/src/test/java/org/pentaho/platform/plugin/action/kettle/KettleSystemListenerTest.java
extensions/src/test/java/org/pentaho/platform/plugin/action/kettle/PlatformKettleDataSourceProviderTest.java
repository/src/main/java/org/pentaho/platform/repository/DatabaseHelper.java
repository/src/test/java/org/pentaho/platform/repository/DatabaseHelperTest.java

connections when the connection is defined using variables.

[PDI-18826] Pentaho platform needs to be able to provide pooled DB

---

api/src/main/java/org/pentaho/platform/api/data/IPooledDatasourceService.java

[PDI-18826] Remove redundant method declaration; method is provided by

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledOrJndiDatasourceService.java

[BISERVER-14682] - Database connections from different pools mixed up when using SQL Server

---

assemblies/pentaho-server/pom.xml
assemblies/pentaho-server/src/assembly/assembly.xml
pom.xml
tomcat-logs/pom.xml

[PDI - 18988]: Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

[PDI - 18988]: Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/axis/axis2_config.xml
extensions/src/it/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelperIT.java
extensions/src/it/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerNamingIT.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/RepositoryResourceIT.java
extensions/src/main/java/org/pentaho/platform/plugin/services/webservices/SystemSolutionAxisConfigurator.java
extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java
extensions/src/main/java/org/pentaho/platform/web/http/security/HttpSessionReuseDetectionFilter.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
repository/src/it/java/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryAuthorizationIT.java
repository/src/it/java/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryContentIT.java
repository/src/it/java/org/pentaho/platform/repository2/unified/DefaultUnifiedRepositoryVersioningIT.java
repository/src/it/java/org/pentaho/platform/repository2/unified/jcr/JcrRepositoryFileDaoIT.java
repository/src/it/java/org/pentaho/platform/repository2/unified/webservices/jaxws/DefaultUnifiedRepositoryJaxwsWebServiceIT.java
repository/src/it/java/org/pentaho/test/platform/security/userroledao/UserRoleDaoUserRoleListServiceIT.java

The repository module IT tests are not compiling, due to both JUnit version upgrade and Log4J upgrade.
Also, some typos I had around to fix.
And one of those "always true" ifs which I removed.
@ricksjames, @peterrinehart, @ddiroma one of you, please review and merge.

[CLEANUP] Fixing tests which did not compile, and typos and one minor simplification

---

core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicConnectionDatasourceServiceTest.java

@smmribeiro 
@renato-s 
@peterrinehart

[BISERVER-14682] Fixing problem with unit test testUseNonPoolingConnectionServices

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfProtectedUsernamePasswordAuthenticationFilter.java
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfValidationAuthenticationException.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PreventBruteForceUsernamePasswordAuthenticationFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfProtectedUsernamePasswordAuthenticationFilterTest.java

Please ignore the commit [[BACKLOG-35003] Change security-web to latest version](https://github.com/pentaho/pentaho-platform/commit/31b11327f582830a6c4488b7f3f65920f9d5b476), which belongs to a base PR, https://github.com/pentaho/pentaho-platform/pull/5075, still not merged.
Related PRs:
- https://github.com/pentaho/pentaho-platform-ee/pull/1527
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/810
- https://github.com/pentaho/pentaho-kettle/pull/8300

[BACKLOG-35624] CSRF - /j_spring_security_check - Explicit Login

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
extensions/src/main/java/org/pentaho/platform/web/http/security/RequestParameterAuthenticationFilter.java
extensions/src/test/java/org/pentaho/test/platform/web/http/security/RequestParameterAuthenticationFilterTest.java

[BACKLOG-35904] CSRF - Protect the Request Parameters authentication mechanism

---

assemblies/pentaho-solutions/pom.xml
assemblies/pentaho-war/pom.xml

[BACKLOG-35888] Add kettle plugins for metastore locator and repository

---

core/src/main/java/org/pentaho/platform/util/messages/LocaleHelper.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SystemResource.java
user-console/src/main/resources/org/pentaho/mantle/public/Mantle.jsp

Adding property in repository to account for locale change

[BISERVER-12830] - As a user I would like PUC to remember the language switching after relogin

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
extensions/src/main/java/org/pentaho/platform/web/http/security/CsrfProtectedUsernamePasswordAuthenticationFilter.java
extensions/src/main/java/org/pentaho/platform/web/http/security/RequestParameterAuthenticationFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/security/CsrfProtectedUsernamePasswordAuthenticationFilterTest.java
extensions/src/test/java/org/pentaho/test/platform/web/http/security/RequestParameterAuthenticationFilterTest.java

Depends on https://github.com/pentaho/maven-parent-poms/pull/343.

[BACKLOG-35980] Adapt to new CSRF API with CsrfValidator

---

api/src/main/java/org/pentaho/platform/api/engine/IServiceOperationAwareContentGenerator.java
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoServices.spring.xml
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/AbstractJaxRSResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/GeneratorStreamingOutput.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryResource.java
extensions/src/main/java/org/pentaho/platform/web/servlet/GenericServlet.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/RepositoryResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/servlet/GenericServletTest.java

Needs rebasing once BACKLOG-35980 is merged (https://github.com/pentaho/pentaho-platform/pull/5104).
PR set:
- https://github.com/pentaho/pentaho-platform-ee/pull/1534
- https://github.com/pentaho/pentaho-analyzer/pull/2256
- https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/541

[BACKLOG-35982] Dynamic CSRF protection for content generators

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicallyPooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/NonPooledOrJndiDatasourceService.java
core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/DynamicConnectionDatasourceServiceTest.java

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5073/

[SP-6149] - Backport of BISERVER-14682 - Database connections from different pools mixed up when using SQL Server (9.3 Suite)

---

assemblies/pentaho-war/pom.xml
pom.xml

this is for the backporting from the original commit - c1b7afc79c4b5f1df801e1ad785aedb6677aa957

[PPP-4654] Get commons-io version from parent pom

---

extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicProcessingFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/security/PentahoBasicProcessingFilterTest.java

- removed impossible to use constructor
- added always missing unit tests
@smmribeiro @bcostahitachivantara @renato-s @andreramos89 please review and merge.
Note: this PR replaces https://github.com/pentaho/pentaho-platform/pull/5126.

[BISERVER-14840] Cannot perform Basic HTTP Authentication with Cookie's SameSite=None and HTTPS after log-off

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/HttpSessionPentahoSessionIntegrationFilter.java

@bcostahitachivantara @renato-s @andreramos89

[BISERVER-14869] Misconfiguration on "session-expiry" and "server-time" cookies

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/CustomSessionTimeoutFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/filters/CustomSessionTimeoutFilterTest.java

@rmansoor @bcostahitachivantara @renato-s @andreramos89

[BISERVER-14819] Errors Opening Jobs After Repository Import

---

extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileServlet.java
extensions/src/main/resources/org/pentaho/platform/web/servlet/messages/messages.properties

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4761] - File Upload Path Disclosure exposed on Pentaho Server when file_name parameter uses special character

---

extensions/src/main/java/org/pentaho/platform/web/http/filters/CustomSessionTimeoutFilter.java

@smmribeiro 
@andreramos89 
@renato-s

[BISERVER-14819] - Errors Opening Jobs After Repository Import

---

extensions/src/test/java/org/pentaho/platform/web/http/api/resources/SystemResourceTest.java

- set mock for IUserSettingService.class in PentahoSystem

[CLEANUP] fix unit test SystemResourceTest.java

---

repository/pom.xml

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml

[PPP-4794] Refine URL filters to prevent users from appending require-js

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserConsoleResource.java

@smmribeiro 
@renato-s 
@andreramos89

[PPP-4767] - Reflected Cross-Site Scripting (XSS) on parameter value of session-variable

---

repository/pom.xml

Reverts pentaho/pentaho-platform#5149

Revert "[PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978"

---

extensions/src/main/java/org/pentaho/platform/web/servlet/UploadFileServlet.java
extensions/src/main/resources/org/pentaho/platform/web/servlet/messages/messages.properties

SP-6203 Backport of PPP-4761 - File Upload Path Disclosure exposed on Pentaho Server when file_name parameter uses special character (9.3 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserConsoleResource.java

[SP-6239] - Backport of PPP-4767 - Reflected Cross-Site Scripting (XSS) on parameter value of session-variable (9.3 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

[BISERVER-14590] - Fix or Remove the option to "Create deep link"

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml

where not appropriate.
This commit is a cherry-pick from master cd2f19d3

[SP-6220] Refine URL filters to prevent users from appending require-js

---

repository/src/test/java/org/pentaho/platform/repository/RepositoryFilenameUtilsTest.java

[TEST] Fix unit test

---

assemblies/pentaho-war/pom.xml
pom.xml

[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/plugin/action/kettle/PoolingManagedDataSource.java

[PDI-19604] - Connection related issues when Connection Pooling is enabled in transformations.

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.templates.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js

https://jira.pentaho.com/browse/BACKLOG-36964
@pentaho/hoth please review.

[BACKLOG-36964] Add basic dialog-related ARIA roles to base dialog classes of Browse Files perspective

---

extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicAuthenticationEntryPoint.java
extensions/src/main/java/org/pentaho/platform/web/http/security/PentahoBasicProcessingFilter.java
extensions/src/test/java/org/pentaho/platform/web/http/security/PentahoBasicProcessingFilterTest.java

[SP-6284] - Backport of BISERVER-14840 - Cannot perform Basic HTTP Authentication with Cookie's SameSite=None and HTTPS after log-off (9.3 Suite)

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

@pentaho/wcag  - Please review.

[BACKLOG-36721]-Accessibility-PUC Home Page-Toolbar.

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml
extensions/src/it/resources/repository-test-override.spring.xml
extensions/src/it/resources/repository.spring.xml
extensions/src/test/resources/ldapIntegrationTestContext.xml
extensions/src/test/resources/repository-test-override.spring.xml
extensions/src/test/resources/repository.spring.xml
repository/pom.xml
repository/src/it/resources/repository-test-override.spring.xml
repository/src/main/resources/repository.spring.xml

[SP-6264] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.3 Suite)

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml
extensions/src/it/resources/repository-test-override.spring.xml
extensions/src/it/resources/repository.spring.xml
extensions/src/test/resources/ldapIntegrationTestContext.xml
extensions/src/test/resources/repository-test-override.spring.xml
extensions/src/test/resources/repository.spring.xml
repository/pom.xml
repository/src/it/resources/repository-test-override.spring.xml
repository/src/main/resources/repository.spring.xml

[SP-6265] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.4 Suite)

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/repository.spring.xml
extensions/src/it/resources/repository-test-override.spring.xml
extensions/src/it/resources/repository.spring.xml
extensions/src/test/resources/ldapIntegrationTestContext.xml
extensions/src/test/resources/repository-test-override.spring.xml
extensions/src/test/resources/repository.spring.xml
repository/src/it/resources/repository-test-override.spring.xml
repository/src/main/resources/repository.spring.xml

@smmribeiro
@andreramos89
@renato-s

[PPP-4827] - Vulnerable Component: Spring Security - CVE-2022-31692

---

core/pom.xml
core/src/main/java/org/pentaho/platform/engine/security/PentahoJsonValidator.java
core/src/test/java/org/pentaho/platform/engine/security/PentahoJsonValidatorTest.java
pom.xml
user-console/pom.xml

[PPP-4801] - GeoJson service is vulnerable to deserialization attacks

---

user-console/src/main/java/org/pentaho/mantle/client/commands/NewFolderCommand.java

[BACKLOG-36952] - Page Zoom (AA) - Browse Files -New Folder

---

core/src/main/resources/org/pentaho/platform/EmailSupport.gwt.xml
user-console/pom.xml
user-console/src/main/resources/org/pentaho/mantle/MantleApplication.gwt.xml

[BACKLOG-37094] GWT SuperDevMode fails due to unknown class EmailConstants

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserConsoleResource.java

[SP-6240] - Backport of PPP-4767 - Reflected Cross-Site Scripting (XSS) on parameter value of session-variable (9.4 Suite)

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
pom.xml
repository/pom.xml

@bcostahitachivantara @renato-s @andreramos89

[PPP-4783] Vulnerable Component: nekohtml

---

assemblies/pentaho-war/pom.xml
pom.xml

[PPP-4610] - Use of Vulnerable Component: Components/snakeyaml:1.25

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.templates.js

[BACKLOG-36974] - Page Zoom (AA) - Browse Files - Rename File

---

user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5165

[SP-6252] - Backport of BISERVER-14590 - Fix or Remove the option to "Create deep link" (9.3 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5165

[SP-6253] - Backport of BISERVER-14590 - Fix or Remove the option to "Create deep link" (9.4 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/commands/NewDropdownCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/NewFolderCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/UrlCommand.java
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.js

Part of PR set: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1617.

[BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] GWT/XUL Dialogs Default, Trap and Restore Focus

---

extensions/pom.xml
pom.xml

[PPP-4828] - Component Rome is outdated

---

core/pom.xml
core/src/main/java/org/pentaho/platform/engine/security/PentahoJsonValidator.java
core/src/test/java/org/pentaho/platform/engine/security/PentahoJsonValidatorTest.java
pom.xml
user-console/pom.xml

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5220

[SP-6303] - Backlog of PPP-4801 - GeoJson service is vulnerable to deserialization attacks (9.3 Suite)

---

core/pom.xml
core/src/main/java/org/pentaho/platform/engine/security/PentahoJsonValidator.java
core/src/test/java/org/pentaho/platform/engine/security/PentahoJsonValidatorTest.java
pom.xml
user-console/pom.xml

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5220

[SP-6304] - Backlog of PPP-4801 - GeoJson service is vulnerable to deserialization attacks (9.4 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/dialogs/ImportDialog.java

[BACKLOG-36949] Page Zoom (AA) - Browse Files - Select Folder - Upload File

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js

[BACKLOG-36843]-Accessibility-Browse Files Perspective-Folders

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.dialogs.js

@pentaho/wcag, please review.
Depends on: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1625

[BACKLOG-37033][BACKLOG-37034] Fix default and restore focus for BootstrapJS dialogs

---

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp

[BACKLOG-37137] Added a function for keyboard navigation and fixed 'onClick' behaviour

---

user-console/src/main/java/org/pentaho/mantle/client/ui/CustomDropDown.java
user-console/src/main/resources/org/pentaho/mantle/public/home/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/home/js/home.js

@pentaho/wcag , please review.

[BACKLOG-37107][BACKLOG-37109]-Closing of 'Create New' popup and Home/admin popup on TAB

---

assemblies/pentaho-war/pom.xml
pom.xml
user-console/pom.xml

@smmribeiro 
@andreramos89 
@renato-s

[PPP-3713] - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510

---

assemblies/pentaho-war/pom.xml
pom.xml

[SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js

[BACKLOG-36843]-Accessibility-Browse Files Perspective-Files List

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

[BACKLOG-36973] - fix for user dropdown in header getting out of screen

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

[BACKLOG-36848] WCAG changes for Schedules grid

---

user-console/src/main/java/org/pentaho/mantle/client/ui/CustomDropDown.java

[BACKLOG-37219]-FIREFOX-In PUC Home page, the keyboard keys aren't working under 'Home' and 'admin' dropdowns.

---

user-console/src/main/resources/org/pentaho/mantle/public/home/content/getting_started_tab2_content.html
user-console/src/main/resources/org/pentaho/mantle/public/home/content/getting_started_tab3_content.html
user-console/src/main/resources/org/pentaho/mantle/public/home/css/home.css
user-console/src/main/resources/org/pentaho/mantle/public/home/js/gettingStarted.js

@pentaho/wcag Please review
This has to be merged with https://github.com/pentaho/pentaho-commons-gwt-modules/pull/871

[BACKLOG-36894] Page Zoom (AA) - Home Page perspective

---

user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordByUserDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/RoleDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserDialog.java
user-console/src/main/java/org/pentaho/mantle/client/dialogs/ImportDialog.java

@pentaho/wcag, please, review.
Part of PR set: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/873

[BACKLOG-37104][BACKLOG-36972] Page Zoom (AA) - Base XUL/GWT Dialog Classes

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[BACKLOG-37317] WCAG Space keypress Fix for SchedulesPanel Grid

---

user-console/src/main/resources-filtered/org/pentaho/mantle/public/browser/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
user-console/src/main/resources/org/pentaho/mantle/public/home/index.jsp

@pentaho/wcag, please review.
Depends on: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/878.

[BACKLOG-37296] Text Zoom (AA) - Browse Files - Multiple issues

---

user-console/src/main/resources/org/pentaho/mantle/public/Mantle.jsp
user-console/src/main/resources/org/pentaho/mantle/public/MantleDebug.jsp
user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

@pentaho/wcag, please review.
First two commits are just refactoring. No functionality changes. May be easier to review commit by commit, or to unselect those from the commit filter.
Part of PR set: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/881

[BACKLOG-37325] Text Zoom (AA) - PUC header basic responsiveness

---

user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFileCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/DeleteFolderCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/DeletePermanentFileCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/OpenURLCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/RestoreFileCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/SaveCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/SwitchThemeCommand.java
user-console/src/main/java/org/pentaho/mantle/client/commands/UrlCommand.java
user-console/src/main/java/org/pentaho/mantle/client/dialogs/ImportDialog.java
user-console/src/main/java/org/pentaho/mantle/client/dialogs/OverwritePromptDialog.java
user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/PermissionsPanel.java
user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java
user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[BACKLOG-36996] PUC Dialogs - Fix semantics of all PUC Message Dialog box instances

---

core/pom.xml
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledOrJndiDatasourceService.java
core/src/main/java/org/pentaho/platform/plugin/action/kettle/PoolingManagedDataSource.java

[CUST-273] - Requesting CUST for PDI-19604 on top of 9.3.0.2

---

assemblies/pentaho-war/src/main/webapp/jsp/PUCLogin.jsp

[BACKLOG-37006] - PUC Notifications - Name and Role

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
user-console/src/main/resources/org/pentaho/mantle/public/home/js/favorites.js

@pentaho/wcag , Please review.
Merge with - https://github.com/pentaho/pentaho-commons-gwt-modules/pull/888

[BACKLOG-37324] - JS changes for Listox implementation.

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/css/browser.css
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

@pentaho/wcag , Please review
Issues Addressed:
1. Text Zoom
2. Support for Ctrl + A
3. Support for type-ahead
Merge with - https://github.com/pentaho/pentaho-commons-gwt-modules/pull/890

[BACKLOG-37324] - Listox implementation

---

assemblies/pentaho-war/pom.xml
pom.xml

[BACKLOG-37368] Update bouncycastle dependencies to match license

---

assemblies/pentaho-war/pom.xml

[BACKLOG-37531] Update BC dependencies to use the same version across

---

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/SelectUserOrRoleDialog.java

[BACKLOG-37557] Added KeyDownHandlers for listbox

---

user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordByUserDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/RoleDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserDialog.java

[BACKLOG-37246] Page Zoom (AA) - Base XUL/GWT Dialog Classes - XML Attributes

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

[BACKLOG-37603] - WCAG Shift-Tab to go back and forth between folders and files impacts being able to select files

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

[BACKLOG-37610] - Browse Files - Properties option doesn't load anything

---

user-console/src/main/java/org/pentaho/mantle/client/ui/BurgerMenuBar.java

Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/920.
@pentaho/wcag, please, review.

[BACKLOG-37059] Fixed bug occurring when clicking a menu item

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

[BACKLOG-37694] Fixing focus ring giving bounce effect on schedules grid

---

repository/src/test/resources/solution/system/hibernate/hsql.hibernate.cfg.xml

This reverts commit e38a6e468ffec561673d458ec51d6ca1d07e4d2d.
@bcostahitachivantara @renato-s @andreramos89

Revert "[PPP-4802] Fix unit tests"

---

extensions/pom.xml
pom.xml

[SP-6350] - Backport of PPP-4828 - Component Rome is outdated (9.3 Suite)

---

core/src/main/java/org/pentaho/platform/engine/core/solution/ActionInfo.java
core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/services/connection/PentahoConnectionFactory.java

[PPP-4787] - Security Vulnerability: JNDI Injection in /pentaho/ServiceAction

---

extensions/pom.xml
pom.xml

Already getting pulled as a transitive dependency from kettle

[PDI-19803] Remove unused jsch

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java

@smmribeiro 
@andreramos89 
@renato-s

[PDI-19601] - PDI - Unable to edit, test, explore, or use a connection created in PUC

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[BISERVER-14539] - Start/Pause Scheduler Tooltip with faulty description

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
pom.xml
repository/pom.xml
user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

[PDI-18433] Upgrade commons-vfs2 to 2.9.0

---

core/src/main/java/org/pentaho/platform/engine/core/solution/ActionInfo.java
core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/services/connection/PentahoConnectionFactory.java

@andreramos89 
@smmribeiro 
Original PRs:
- https://github.com/pentaho/pentaho-platform/pull/5336
- https://github.com/pentaho/pentaho-platform/pull/5337

[SP-6361] - Backport of PPP-4787 - Security Vulnerability: JNDI Injection in /pentaho/ServiceAction (9.3 Suite)

---

core/src/main/java/org/pentaho/platform/engine/core/solution/ActionInfo.java
core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/services/connection/PentahoConnectionFactory.java

@andreramos89 
@smmribeiro 
Original PRs:
- https://github.com/pentaho/pentaho-platform/pull/5336
- https://github.com/pentaho/pentaho-platform/pull/5337

[SP-6362] - Backport of PPP-4787 - Security Vulnerability: JNDI Injection in /pentaho/ServiceAction (9.5 Suite)

---

user-console/src/main/resources/org/pentaho/mantle/public/MantleStyle.css

@pentaho/wcag , Please review
This PR is part of
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/950
https://github.com/pentaho/data-access/pull/1217
https://github.com/pentaho/pentaho-commons-xul/pull/255

[BACKLOG-37741] Page Zoom (AA) - Data Source Wizard Dialog-CSV file type & Sql File type Subsequent Dialogs

---

api/src/main/java/org/pentaho/platform/api/engine/IPlatformPlugin.java
extensions/src/it/java/org/pentaho/test/platform/plugin/pluginmgr/DefaultPluginManagerIT.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/PlatformPlugin.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/SystemPathXmlPluginProvider.java

Reverts pentaho/pentaho-platform#5356

Revert "[BACKLOG-38038] - Allow plugin to initialize multiple lifecycle liste…"

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

@andreramos89 
Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5349

[SP-6377] - Backport of BISERVER-14539 - Start/Pause Scheduler Tooltip with faulty description (9.3 Suite)

---

core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java

Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5344

[SP-6387] - Backport of PDI-19601 - PDI - Unable to edit, test, explore, or use a connection created in PUC (9.5 Suite)

---

api/pom.xml
assemblies/pentaho-data/pom.xml
assemblies/pentaho-plugin-samples/pom.xml
assemblies/pentaho-samples/pom.xml
assemblies/pentaho-server-manual/pom.xml
assemblies/pentaho-server/pom.xml
assemblies/pentaho-solutions/pom.xml
assemblies/pentaho-style/pom.xml
assemblies/pentaho-user-console/pom.xml
assemblies/pentaho-war/pom.xml
assemblies/pom.xml
build-utils/pom.xml
core/pom.xml
extensions/pom.xml
pom.xml
repository/pom.xml
scheduler/pom.xml
tomcat-logs/pom.xml
user-console/pom.xml

[CLEANUP] updated versions via release version merger

Merging master into wcag

---

api/src/main/java/org/pentaho/platform/api/util/IPdiContentProvider.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtil.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/SchedulerServiceTest.java

variables and default values for vars and params.
Update SchedulerResourceUtil to only put ktr/kjb vars and params in the pdi parameters sub map.

[BACKLOG-38073] Update API to allow PdiContentProvider to provide

---

api/src/main/java/org/pentaho/platform/api/engine/IPlatformPlugin.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestUtil.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/ExportManifestDto.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/DefaultPluginManager.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/PentahoSystemPluginManager.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/PlatformPlugin.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/SystemPathXmlPluginProvider.java
extensions/src/main/java/org/pentaho/platform/web/http/context/PentahoSystemReadyListener.java
scheduler/src/main/java/org/pentaho/platform/api/scheduler2/IJobScheduleRequest.java

BACKLOG-38036 - Additional code to deal with class loading issues and fixed problem with multiple 

---

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java

Added condition for not picking up the manual scheduled job execution twice
----------
@smmribeiro 
@renato-s

[BISERVER-14971] - Schedule runs twice if using 'Run Now' after the time that a daily (every weekday) schedule is due to run

---

assemblies/pentaho-war/pom.xml

[PPP-4747]-Vulnerable Component : batik:1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747]-Vulnerable Component :batik:1.19

---

repository/src/main/java/org/pentaho/platform/repository/RepositoryFilenameUtils.java

Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5410

[SP-6427] - Backport of PDI-19835 - API to create files on the Pentaho server repository fails on Windows (9.3 Suite)

---

assemblies/pentaho-war/pom.xml
pom.xml

Reverts pentaho/pentaho-platform#5407

Revert "[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho"

---

user-console/pom.xml

Reverts pentaho/pentaho-platform#5430

Revert "[BACKLOG-38801] SCHEDULER - Change developer mode options to production ready."

---

assemblies/pentaho-war/pom.xml

[PPP-4747] -Vulnerable Component :batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747] -Vulnerable Component :batik-1.19

---

scheduler/src/main/java/org/pentaho/platform/scheduler2/quartz/QuartzScheduler.java
scheduler/src/test/java/org/pentaho/platform/scheduler2/quartz/test/ComplexTriggerTest.java

[BISERVER-14992] Not showing the repeats with every day and setting the value to 0 in edit mode

---

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/SolutionBrowserPanel.java
user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/filelist/FileCommand.java
user-console/src/main/java/org/pentaho/mantle/client/ui/PerspectiveManager.java

/cc @pentaho/hoth. @pentaho/r2d2, @pentaho/millenniumfalcon
To be merged with:https://github.com/pentaho/pentaho-scheduler-plugin/pull/47

[BACKLOG-37872] Fixed not being able to use OBF or SuperDevMode mode

---

assemblies/pentaho-solutions/pom.xml

pentaho-streaming-kafka-plugin-zip to pentaho-streaming-kafka-plugin

renamed the artifact name from

---

extensions/src/main/java/org/pentaho/platform/plugin/services/connections/PentahoSystemDriver.java

Fixing the error. A new issue will be created to address the cached list of drivers solution.
@smmribeiro 
@renato-s

[BAD-1930] - When Cloudera HIVE driver is used, a side effect in the LOGs with error messages start to show

---

user-console/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java

file name; updated to only strip off a file extension, if any.

[BISERVER-14241] Source name logic assumed only one . would ever be in a

---

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml

Reverts pentaho/pentaho-platform#5409
We need to put all scheduler configuration in either pentaho-scheduler-plugin or if enterprise in the enterprise repository

Revert "[BACKLOG-37897] - Update of  pentaho.xml to support email sources"

---

assemblies/pentaho-war/src/main/webapp/js/themeResources.js

@pentaho/wcag Please review and merge along with
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1020

[BACKLOG-37991] WCAG - Manage Data souces dialog on Safari - bad ui format

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

Addresses BACKLOG-39950: fix zoom after 400% hides content

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/crystal/mantleCrystal.css
user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css
user-console/src/main/resources/org/pentaho/mantle/public/themes/sapphire/mantleSapphire.css

Related PRs:
- https://github.com/pentaho/pentaho-scheduler-plugin/pull/127
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/182

feat: rearrange schedule table toolbar icons [BACKLOG-39963]

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/RepositoryResource.java

Original PRs:
- https://github.com/pentaho/pentaho-platform/pull/5547
- https://github.com/pentaho/pentaho-platform/pull/5549
@smmribeiro 
@renato-s

[SP-6498] - Backport of BISERVER-15031 - Limit the PIR Export via REST API to the allowed types (9.3 Suite)

---

user-console/src/main/resources/org/pentaho/mantle/public/themes/ruby/mantleRuby.css

fix: Blockout table records have shrunk in size [BACKLOG-40143]

---

core/src/main/java/org/pentaho/platform/engine/services/solution/SimpleContentGenerator.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/GeneratorStreamingOutput.java
extensions/src/test/java/org/pentaho/platform/plugin/services/webservices/content/AxisServiceExecutorTest.java
extensions/src/test/java/org/pentaho/test/platform/plugin/services/webservices/AxisServiceWsdlGeneratorTest.java
extensions/src/test/java/org/pentaho/test/platform/plugin/services/webservices/WsdlPageTest.java

Added permission validation to content generation

[PPP-5053] - Intercepting few Get request with Burp Suite allows un-athorised user to access data

---

user-console/src/main/java/org/pentaho/mantle/client/ui/PerspectiveManager.java

Depends on 
https://github.com/pentaho/pentaho-scheduler-plugin/pull/144
https://github.com/pentaho/pentaho-platform/pull/5560

Addresses BACKLOG-40051: new endpoint execute schedule permission

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
repository/pom.xml

[PPP-4865] - Vulnerable Component: snakeyaml

---

extensions/pom.xml

[BACKLOG-40255] Sub in patched axis2-kernel jar to resolve byte code

---

extensions/src/it/java/org/pentaho/test/platform/web/ProxyServletIT.java
extensions/src/main/java/org/pentaho/platform/web/servlet/ProxyServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/ProxyServletTest.java

Addresses BACKLOG-402904: Review ProxyServlet POST header and body propagation

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

Original PR:
- https://github.com/pentaho/pentaho-platform/pull/5054

[SP-6522] - Backport of BISERVER-15052 - NPE on Pentaho Server when clicking on Arrow icon next to Trash to expand it (9.3 Suite)

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ssrf.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho-spring-beans.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/server.properties
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/system.properties
extensions/src/main/java/org/pentaho/platform/config/PentahoSsrfConfigurationPojo.java

[PPP-5004]-Tomcat Configuration vulnerable to Server-Side Request Forgery
[PPP-5004]: https://hv-eng.atlassian.net/browse/PPP-5004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5004]-Tomcat Configuration vulnerable to Server-Side Request Forgery

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java

**Attention: merge should NOT squash commits!**
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/229.
JIRA subtask: https://hv-eng.atlassian.net/browse/BACKLOG-40305

[BACKLOG-40063] Added the /api/userrolelist/adminRole endpoint

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserRolesAdminPanelController.java

Added URL  encoding to handle special characters before b64 encoding

[BISERVER-14644] - Users with password having certain special characters, or strings of characters, are not allowed to login to PUC

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/MondrianImportHandler.java
extensions/src/main/java/org/pentaho/platform/web/servlet/PentahoXmlaServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/PentahoXmlaServletTest.java

Addresses BACKLOG-40539: validates EnableXmla property

---

user-console/src/main/resources-filtered/org/pentaho/mantle/public/browser/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

This PR is part of https://github.com/pentaho/pentaho-scheduler-plugin/pull/176

[BACKLOG-40444] Browse Perspective: Improve folder tree model depth variable and related API call

---

user-console/src/main/java/org/pentaho/mantle/client/MantleUtils.java

fix: race condition loading GWT JS [BACKLOG-40418]

---

user-console/src/main/java/org/pentaho/mantle/client/ui/xul/MantleController.java

[PDB-2096] - View Mode wrong tooltip text

---

user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js

To be merged with: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1038

[BACKLOG-41033] PUC - Browse Files - VFS connection root folders appear in random order

---

core/src/test/java/org/pentaho/platform/util/versionchecker/PentahoVersionCheckReflectHelperTest.java

[TEST] Ignore version checker tests; URL to receive version data no

---

user-console/src/main/java/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

[ANALYZER-4102] - PUC - "Save" "Save as" buttons not present when user navigates between the PAZ tabs

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleListResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListService.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/UserRoleListResourceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleListServiceTest.java

Jira - https://hv-eng.atlassian.net/browse/BACKLOG-41048

[BACKLOG-41048] Added code changes for excluding anonymous role from BA roles in a VFS connection create/edit page.

---

pom.xml

[PPP-5077]-Vulnerable Component: mina-core
[PPP-5077]: https://hv-eng.atlassian.net/browse/PPP-5077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5077]-Vulnerable Component: mina-core

---

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml
core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
core/src/main/resources/org/pentaho/platform/engine/services/messages/messages.properties
core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelperTest.java

Issue: https://hv-eng.atlassian.net/browse/PPP-4772
Merge with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1773

[PPP-4772] RCE injection via connection's JNDI database name

---

pom.xml

[REVERT] PPP-5077-Vulnerable Component: mina-core

[REVERT] PPP-5077-Vulnerable Component: mina-core

---

extensions/src/main/java/org/pentaho/platform/osgi/KarafBoot.java
extensions/src/test/java/org/pentaho/platform/osgi/KarafBootTest.java

[PDI-20086] Add a kettle parameter to control whether we wait for a lock

---

assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/classic-engine.properties

[PIR-1523] - SQL queries for the prompts In Interactive reports are executed twice

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml

connection pool for hibernate, and tomcat handles that.

[PPP-4391] Remove c3p0 dependency; was never really used except as a

---

extensions/src/main/java/org/pentaho/platform/web/servlet/PluginDispatchServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/PluginDispatchServletTest.java

fix: get dispatch key from path with forward slash [BACKLOG-41364]

---

core/src/main/java/org/pentaho/platform/engine/services/runtime/RuntimeContext.java
core/src/main/java/org/pentaho/platform/uifoundation/chart/DashboardWidgetComponent.java
core/src/main/java/org/pentaho/platform/uifoundation/component/xml/FilterPanelComponent.java
core/src/main/java/org/pentaho/platform/uifoundation/component/xml/WidgetGridComponent.java
core/src/main/java/org/pentaho/platform/util/xml/XMLParserFactoryProducer.java
core/src/main/java/org/pentaho/platform/util/xml/dom4j/XmlDom4JHelper.java
core/src/main/java/org/pentaho/platform/util/xml/w3c/XmlW3CHelper.java
extensions/src/main/java/org/pentaho/platform/config/PentahoObjectsConfig.java
extensions/src/main/java/org/pentaho/platform/plugin/action/kettle/KettleSystemListener.java
extensions/src/main/java/org/pentaho/platform/plugin/action/mondrian/catalog/MondrianCatalogHelper.java
extensions/src/main/java/org/pentaho/platform/plugin/action/xml/xquery/XQueryBaseComponent.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleFilesProcessor.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/LocaleImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importer/XActionImportHandler.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifest.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/FileSystemXmlPluginProvider.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/SystemPathXmlPluginProvider.java
extensions/src/main/java/org/pentaho/platform/web/html/themes/PluginThemeResolver.java
extensions/src/main/java/org/pentaho/platform/web/html/themes/ServletContextThemeResolver.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/FileResource.java
extensions/src/main/java/org/pentaho/platform/web/http/context/PentahoSolutionSpringApplicationContext.java
extensions/src/main/java/org/pentaho/platform/web/servlet/ContextDiscoveryServlet.java
extensions/src/main/java/org/pentaho/platform/web/servlet/SolutionEngineInteractivityService.java

[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

---

extensions/src/main/java/org/pentaho/platform/web/servlet/PluginDispatchServlet.java
extensions/src/test/java/org/pentaho/platform/web/servlet/PluginDispatchServletTest.java

[SP-6589] Backport of PPP-5238 - Error when path ends with forward slash (10.2 Suite)

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-ssrf.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentaho-spring-beans.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/server.properties
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/system.properties
extensions/src/main/java/org/pentaho/platform/config/PentahoSsrfConfigurationPojo.java

[SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)
[SP-6584]: https://hv-eng.atlassian.net/browse/SP-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)

---

core/src/main/java/org/pentaho/platform/engine/security/PentahoJsonValidator.java
core/src/test/java/org/pentaho/platform/engine/security/PentahoJsonValidatorTest.java

[SP-6565]-Backport of PPP-5078 - Insecure deserialization in Pentaho Interactive Reporting (9.3 Suite)
[SP-6565]: https://hv-eng.atlassian.net/browse/SP-6565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6565]-Backport of PPP-5078 - Insecure deserialization in Pentaho Interactive Reporting (9.3 Suite)

---

assemblies/pentaho-war/pom.xml
extensions/pom.xml
repository/pom.xml

- replace 'org.hitachivantatar:safeyaml' with 'org.yaml:snakeyaml:[2.0,)'

[PPP-5163] Vulnerable Component: snakeyaml - part 2 ( Non OSGi upgrade)

---

extensions/pom.xml
repository/pom.xml

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

---

assemblies/pentaho-solutions/pom.xml

(cherry picked from commit 79a6aad68cf38d2789efea524f3e95496d6f1087)

[SP-6601] [PPP-4825] - Upgrade to drools 8.44.0.Final

---

api/src/main/java/org/pentaho/platform/api/scheduler2/IComplexJobTrigger.java
api/src/main/java/org/pentaho/platform/api/scheduler2/IJobTrigger.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestUtil.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobTrigger.java

job other than the server's time zone.

[BISERVER-14374] Add the ability for users to select a time zone for a

---

api/src/main/java/org/pentaho/platform/api/scheduler2/IComplexJobTrigger.java
api/src/main/java/org/pentaho/platform/api/scheduler2/IJobTrigger.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestUtil.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobTrigger.java

Reverts pentaho/pentaho-platform#5730

Revert "[BISERVER-14374] Add the ability for users to select a time zone for a"

---

api/src/main/java/org/pentaho/platform/api/scheduler2/IComplexJobTrigger.java
api/src/main/java/org/pentaho/platform/api/scheduler2/IJobTrigger.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/ExportManifestUtil.java
extensions/src/main/java/org/pentaho/platform/plugin/services/importexport/exportManifest/bindings/JobTrigger.java

Reverts pentaho/pentaho-platform#5746

Revert "Revert "[BISERVER-14374] Add the ability for users to select a time zone for a""

---

api/src/main/java/org/pentaho/platform/api/util/IPdiContentProvider.java

Reverts pentaho/pentaho-platform#5748

Revert "Revert "[BISERVER-15051] hide internal variables PUC side""

---

assemblies/pentaho-data/src/main/resources/data/oracle/create_quartz_ora.sql

[PPP-4776] Do not drop quartz user if it exists, but create it if it

---

assemblies/pentaho-solutions/src/main/resources-filtered/pentaho-solutions/system/pentaho.xml
core/src/main/java/org/pentaho/platform/engine/core/system/PentahoSystem.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
core/src/main/resources/org/pentaho/platform/engine/services/messages/messages.properties
core/src/test/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelperTest.java

Backport of: https://github.com/pentaho/pentaho-platform/pull/5674.
Merge with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1798
@pentaho/hoth, please review.

[SP-6642][PPP-4772] RCE injection via connection's JNDI database name

---

repository/src/main/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleaner.java
repository/src/test/java/org/pentaho/platform/repository2/unified/jcr/RepositoryCleanerTest.java

Reverts pentaho/pentaho-platform#5783

Revert "[BISERVER-15124] - Moving repository cleaner to scheduler plugin"

---

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java

[BISERVER-15155] - File size in KB is calculated through division by 1000 instead of 1024

---

core/src/main/java/org/pentaho/platform/engine/services/connection/PentahoConnectionFactory.java
core/src/main/java/org/pentaho/platform/engine/services/connection/datasource/dbcp/PooledDatasourceHelper.java
extensions/src/main/java/org/pentaho/platform/plugin/services/connections/sql/SQLConnection.java
extensions/src/test/java/org/pentaho/platform/plugin/services/connections/sql/SQLConnectionTest.java

Original PR: [pentaho-platform#5798](https://github.com/pentaho/pentaho-platform/pull/5798)

[SP-6724] Backport of BISERVER-15144 - Invalid database connection is saved AND used despite "CANCEL" (10.2 Suite)

---

user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/GeneralPanel.java

(cherry picked from commit b7ab326156e1dd94bb72e85fbe80482c7b3fee10)

[SP-6723] Backport of BISERVER-15155 - File size in KB is calculated through division by 1000 instead of 1024 (10.2 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java

[BISERVER-15145] - Prevent the Creation of Usernames with Leading/Trailing Whitespaces

---

api/src/main/java/org/pentaho/platform/api/util/IPdiContentProvider.java

This reverts commit 5cd171eec03a51107bcb4c6f809dba19c9a92831.

[BISERVER-15176] reverting reverted BISERVER-15051

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/h2.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/hsql.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/mysql5.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/oracle10g.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/postgresql.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/hibernate/sqlserver.hibernate.cfg.xml
assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml
extensions/src/main/java/org/pentaho/platform/plugin/services/cache/CacheManager.java
extensions/src/main/java/org/pentaho/platform/plugin/services/cache/HvCacheRegionFactory.java
extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/PentahoJCacheBasedUserCache.java
extensions/src/test/resources/cache-solution/system/hibernate/hsql.hibernate.cfg.xml
extensions/src/test/resources/cache-solution/system/hibernate/mysql5.hibernate.cfg.xml
extensions/src/test/resources/cache-solution/system/hibernate/oracle10g.hibernate.cfg.xml
extensions/src/test/resources/cache-solution/system/hibernate/postgresql.hibernate.cfg.xml
extensions/src/test/resources/cache-solution1/system/hibernate/mysql5.hibernate.cfg.xml
extensions/src/test/resources/cache-solution1/system/hibernate/oracle10g.hibernate.cfg.xml
extensions/src/test/resources/cache-solution1/system/hibernate/postgresql.hibernate.cfg.xml
extensions/src/test/resources/cache-solution2/system/hibernate/mysql5.hibernate.cfg.xml
extensions/src/test/resources/cache-solution2/system/hibernate/oracle10g.hibernate.cfg.xml
extensions/src/test/resources/cache-solution2/system/hibernate/postgresql.hibernate.cfg.xml
extensions/src/test/resources/solution/system/hibernate/hsql.hibernate.cfg.xml
extensions/src/test/resources/solution/test/ipreparedcomponents/HQL_Datasource.cfg.xml
extensions/src/test/resources/web-servlet-solution/system/hibernate/mysql5.hibernate.cfg.xml
extensions/src/test/resources/web-servlet-solution/system/hibernate/oracle10g.hibernate.cfg.xml
extensions/src/test/resources/web-servlet-solution/system/hibernate/postgresql.hibernate.cfg.xml
extensions/src/test/resources/web-solution/system/hibernate/hsql.hibernate.cfg.xml
extensions/src/test/resources/web-solution/system/hibernate/mysql5.hibernate.cfg.xml
extensions/src/test/resources/web-solution/system/hibernate/oracle10g.hibernate.cfg.xml
extensions/src/test/resources/web-solution/system/hibernate/postgresql.hibernate.cfg.xml

[BACKLOG-41596] - Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596] - Upgrading EhCache 2 to JCache and EhCache 3

---

extensions/src/main/java/org/pentaho/platform/plugin/services/cache/LastModifiedCache.java

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

---

extensions/pom.xml

[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43209]-OSGi Assembly Issues

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordByUserDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserDialog.java

Must be merged with: 
https://github.com/pentaho/pentaho-scheduler-plugin/pull/271
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/313
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1054

fix: add character restrictions to password in createUser and changePassword dialogs [BISERVER-15243]

---

assemblies/pentaho-war/src/main/webapp/js/options.js
assemblies/pentaho-war/src/main/webapp/js/utils.js

[PPP-5604]-XSS Findings For Pentaho-platform
[PPP-5604]: https://hv-eng.atlassian.net/browse/PPP-5604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5604]-XSS Findings For Pentaho-platform

---

user-console/pom.xml
user-console/src/main/resources-filtered/org/pentaho/mantle/public/browser/index.jsp
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/js/dialogs/browser.dialog.rename.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/lib/underscore/underscore-min.js
user-console/src/main/resources/org/pentaho/mantle/public/browser/lib/underscore/underscore.js

Reverts pentaho/pentaho-platform#5863

Revert "chore: use underscore webjar instead of hardcoded file [PPP-5515]"

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoServices.spring.xml
extensions/pom.xml
extensions/src/main/java/org/pentaho/platform/web/jaxws/spring/SpringBinding.java
extensions/src/main/java/org/pentaho/platform/web/jaxws/spring/SpringService.java
extensions/src/main/java/org/pentaho/platform/web/jaxws/spring/package-info.java
extensions/src/main/java/org/pentaho/platform/web/servlet/PentahoPluginWSSpringServlet.java
extensions/src/main/java/org/pentaho/platform/web/servlet/PentahoWSSpringServlet.java
pom.xml
repository/src/test/java/org/pentaho/platform/security/policy/rolebased/AuthorizationPolicyClient.java

[BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration
[BACKLOG-43612]: https://hv-eng.atlassian.net/browse/BACKLOG-43612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/SystemResource.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/TimeZoneEntry.java
extensions/src/main/java/org/pentaho/platform/web/http/api/resources/TimeZoneWrapper.java

[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41287]-Upgrading Pentaho platform from Java EE to Jakarta EE

---

assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.sh
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.sh

Reverts pentaho/pentaho-platform#5867

Revert "[BACKLOG-43025] Update startup scripts to include add-opens for"

---

core/pom.xml
core/src/test/java/org/pentaho/platform/util/EmailerTest.java
core/src/test/java/org/pentaho/test/platform/engine/core/BaseTest.java
extensions/pom.xml
extensions/src/it/java/org/pentaho/platform/web/servlet/JAXRSServletTest.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/DirectoryResourceIT.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/FilePerspectiveResourceIT.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/FileResourceIT.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/RepositoryPublishResourceIT.java
extensions/src/it/java/org/pentaho/test/platform/web/http/api/RepositoryResourceIT.java
extensions/src/test/java/org/pentaho/platform/plugin/services/email/EmailServiceTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/importexport/CommandLineProcessorTest.java
extensions/src/test/java/org/pentaho/platform/plugin/services/security/userrole/PentahoJCacheBasedUserCacheTest.java
extensions/src/test/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoServiceTest.java
extensions/src/test/java/org/pentaho/platform/web/http/filters/PentahoAwareCharacterEncodingFilterTest.java
extensions/src/test/java/org/pentaho/platform/web/http/security/UsernameSubstringPreAuthenticatedProcessingFilterTest.java
extensions/src/test/java/org/pentaho/platform/web/servlet/ProxyServletTest.java
pom.xml
repository/pom.xml
repository/src/test/java/org/pentaho/test/platform/repository/RepositoryTestCase.java
repository/src/test/resources/ehcache.xml
repository/src/test/resources/solution/system/hibernate/hsql.hibernate.cfg.xml
repository/src/test/resources/solution/system/hibernate/mysql5.hibernate.cfg.xml
repository/src/test/resources/solution/system/hibernate/oracle10g.hibernate.cfg.xml
repository/src/test/resources/solution/system/hibernate/postgresql.hibernate.cfg.xml

[BACKLOG-41693]-Fix all the broken testcases in pentaho platform
[BACKLOG-41693]: https://hv-eng.atlassian.net/browse/BACKLOG-41693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41693]-Fix all the broken testcases in pentaho platform

---

user-console/src/main/resources/org/pentaho/mantle/public/home/js/favorites.js

[BACKLOG-43636]-PUC - Can't click on File on the Recents and Favorites on Homepage
[BACKLOG-43636]: https://hv-eng.atlassian.net/browse/BACKLOG-43636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43636]-PUC - Can't click on File on the Recents and Favorites on Homepage

---

core/src/main/java/org/pentaho/platform/engine/core/system/SystemSettings.java
core/src/main/resources/org/pentaho/platform/engine/core/messages/messages.properties
core/src/test/resources/org/pentaho/platform/engine/core/messages/messages.properties

Backport of PPP-5594, workaround for a potential xpath vulnerability

[SP-6836][PPP-5594] handle potentially unsafe XPath queries

---

api/src/main/java/org/pentaho/platform/api/engine/IPentahoObjectFactory.java
api/src/main/java/org/pentaho/platform/api/engine/IPentahoObjectReference.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/StandaloneSpringPentahoObjectFactory.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/ApplicationContextPentahoSystemRegisterer.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/BeanBuilder.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/BeanListBuilder.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/BeanListParser.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/BeanParser.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/Const.java
core/src/main/java/org/pentaho/platform/engine/core/system/objfac/spring/SpringPentahoObjectReference.java
core/src/test/java/org/pentaho/platform/engine/core/system/objfac/spring/SpringPentahoObjectReferenceTest.java
extensions/src/it/java/org/pentaho/test/platform/plugin/pluginmgr/DefaultPluginManagerIT.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/DefaultPluginManager.java
extensions/src/main/java/org/pentaho/platform/plugin/services/pluginmgr/PentahoSystemPluginManager.java

- a joint work between the plugin manager and the object factory
Please, "ignore" the commit dedicated to linting.
https://hv-eng.atlassian.net/browse/PPUC-64
@pentaho/millenniumfalcon, please review.

feat(plugin-manager): add publisher-plugin-id attribute to published beans [PPUC-64]

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileDtoWrapper.java

[BACKLOG-44092]-Resolve Issues as part of Practitest Results
[BACKLOG-44092]: https://hv-eng.atlassian.net/browse/BACKLOG-44092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44092]-Trash is not displaying the deleted files/folders

---

extensions/src/it/java/org/pentaho/test/platform/plugin/pluginmgr/DefaultPluginManagerIT.java

This piece of code got lost on a "last minute" code split / rebase ...
@pentaho/millenniumfalcon, please review.

fix(plugin-manager): broken IT test [PPUC-64]

---

api/src/main/java/org/pentaho/platform/api/repository2/unified/webservices/RepositoryFileAclAceDto.java

[BACKLOG-44133]-API Response Does Not Match Expected Permissions Format
[BACKLOG-44133]: https://hv-eng.atlassian.net/browse/BACKLOG-44133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44133]-API Response Does Not Match Expected Permissions Format

---

assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.sh
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.sh

For reference, https://protobuf.dev/news/2025-01-23/

[PPP-5759] Orc libraries Incompatibility due to protobuf-java-3.25.6 library

---

extensions/src/main/java/org/pentaho/platform/plugin/services/cache/CacheManager.java

[BACKLOG-44735]-Server Startup issues related to Cachemanager
[BACKLOG-44735]: https://hv-eng.atlassian.net/browse/BACKLOG-44735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44735]-Server Startup issues related to Cachemanager

---

assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho-debug.sh
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.bat
assemblies/pentaho-server/src/main/resources-filtered/start-pentaho.sh

Reference PR: https://github.com/pentaho/pentaho-platform/pull/5955

[SP-6874] Backport of PPP-5643 - Vulnerable Component: protobuf (deep scan) - Hadoop (10.2 Suite)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java

feat: add methods for content permission [PPUC-25]

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml
core/src/main/java/org/pentaho/platform/engine/security/authorization/core/AuthorizationRequestBuilder.java

To be merged with: https://github.com/pentaho/pentaho-platform-ee/pull/1877
@pentaho/millenniumfalcon, please review.

fix: bean publish declaration [PPUC-122]

---

core/pom.xml
repository/pom.xml

[BACKLOG-45596]-Upgrade JDK properties from 11 to 17
[BACKLOG-45596]: https://hv-eng.atlassian.net/browse/BACKLOG-45596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-45596]-Upgrade JDK properties from 11 to 17

---

core/src/main/java/org/pentaho/platform/util/xml/XmlHelper.java
core/src/main/java/org/pentaho/platform/util/xml/dom4j/XmlDom4JHelper.java

fix: add proper initialization to XML parser [PPP-5719] (#5937)

---

extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/UserRoleDaoService.java
extensions/src/main/resources/org/pentaho/platform/plugin/services/messages/messages.properties
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordByUserDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/ChangePasswordDialog.java
user-console/src/main/java/org/pentaho/mantle/client/admin/UserDialog.java

original PRs: https://github.com/pentaho/pentaho-platform/pull/5994
https://github.com/pentaho/pentaho-platform/pull/6005

fix[SP-6928]: revert username char validation, add "-" to allowed password chars and fix error message

---

extensions/pom.xml

feat[PPP-5739]: replace ini4j with commons-configuration2

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml
assemblies/pentaho-war/pom.xml
assemblies/pom.xml

Part of PR set https://github.com/pentaho/pentaho-app-shell/pull/693.

feat: move generic-file-service to pentaho-platform [PPUC-124]

---

core/src/main/java/org/pentaho/platform/engine/core/system/objfac/AbstractSpringPentahoObjectFactory.java

- Apparently, another case not previously covered by the older fix https://github.com/pentaho/pentaho-platform/pull/5476

fix: session scope for spring beans from plugins [PPUC-124]

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/pentahoObjects.spring.xml

To be merged with:
- https://github.com/pentaho/pentaho-platform-ee/pull/1896
- https://github.com/pentaho/pentaho-generic-file-system/pull/38

feat: Generic File Service consume published Decorators [PPUC-124]

---

extensions/src/main/java/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java

prevents later uploads from incorrectly failing

[BACKLOG-43889] - reset partialImport with each upload

---

assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/osgi/log4j2.xml
assemblies/pentaho-war/src/main/webapp/WEB-INF/classes/log4j2.xml
core/src/test/resources/log4j2.xml
extensions/src/main/resources/log4j/log4j2.xml
extensions/src/test/resources/log4j2.xml
repository/src/test/resources/log4j2.xml

chore[PPP-5981]: add monitorInterval to log4j2 configuration

---

extensions/src/main/java/org/pentaho/platform/plugin/action/xmla/XMLABaseComponent.java
extensions/src/main/java/org/pentaho/platform/web/http/context/PentahoSolutionSpringApplicationContext.java
extensions/src/main/java/org/pentaho/platform/web/servlet/SolutionEngineInteractivityService.java

fix[PPP-5982]: add proper initialization to XML parser
